/* Architecture renders case decisions; definitions always come from Canonical Brain knowledge. */
(function(){
'use strict';
const steps=['Ausgangslage','Fragen klären','Bereitschaft prüfen','Möglichkeiten vergleichen','Entscheiden','Architektur'];
const data=window.ADB_CASE01_DATA_V1,refs=data.canonicalRefs;
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const symbols={ready:'🟢',partial:'🟡',blocked:'🔴',review:'⚫'};
const information={fact:'Bestätigte Angabe',assumption:'Annahme',open_question:'Offene Frage',specialist_review:'Fachprüfung'};
const componentLabels={confirmed:'Bestätigt',proposed:'Vorgeschlagen',optional:'Optional / Alternative',open:'Offen'};
const list=xs=>`<ul>${xs.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
const badge=(s,label)=>`<span class="ac-status ac-${s}">${symbols[s]} ${e(label||window.ADB_DECISION_MODEL_V1.statusText[s])}</span>`;
const help=(title,text)=>`<details class="ac-help"><summary>${e(title)}</summary><p>${e(text)}</p></details>`;
function create(api){
 const model=window.ADB_DECISION_MODEL_V1.create(data),nodes=new Map(window.AZURE_DIGITAL_BRAIN.nodes.map(n=>[n.id,n]));
 const ui={view:'home',step:0,topic:null,component:null,option:null,decisionArea:'compute',why:false,legend:false,scroll:0,question:'',answer:'',editor:null,focusQuestion:null,error:''};let root,routeFocusPending=false,returnFocusPending=false;
 const brain=(id,named=false)=>`<button type="button" data-ac-brain="${e(id)}">${named?e(title(id))+' im Brain':'Im Brain öffnen ↗'}</button>${api.openMindmap?`<button type="button" data-ac-mindmap="${e(id)}">${named?e(title(id))+' in Mindmap':'In Mindmap zeigen ↗'}</button>`:''}`;
 const definition=id=>nodes.get(id)?.description.simple||nodes.get(id)?.description.technical||'';
 const title=id=>nodes.get(id)?.title||id;
 function snapshot(){return {...ui,scroll:api.content.scrollTop};}
 function restore(value){if(value){Object.assign(ui,value);returnFocusPending=ui.step===1&&!!ui.focusQuestion;}}
 function focusCurrentQuestion(){if(ui.step!==1||!ui.focusQuestion)return;const target=root.querySelector('#question-'+ui.focusQuestion);if(!target)return;target.scrollIntoView({block:'start'});target.focus({preventScroll:true});ui.scroll=root.scrollTop;}
 function change(patch){if(!Object.hasOwn(patch,'focusQuestion')&&(Object.hasOwn(patch,'step')||Object.hasOwn(patch,'topic')||patch.view==='home'))ui.focusQuestion=null;Object.assign(ui,patch);routeFocusPending=false;returnFocusPending=false;ui.scroll=0;ui.answer='';ui.error='';api.hash(ui);api.render();requestAnimationFrame(()=>{if(ui.step===1&&ui.focusQuestion)focusCurrentQuestion();else root.querySelector('#ac-step-title')?.focus();});}
 function home(){change({view:'home',topic:null,component:null,editor:null});}
 function start(step=0){change({view:'case',step,component:null});}
 function legend(){return `<details class="ac-legend" ${ui.legend?'open':''}><summary>Was bedeutet das?</summary>${Object.keys(symbols).map(s=>`<p>${badge(s)}<span>${e({ready:'Für diese Entscheidung ausreichend geklärt. Die Entscheidung selbst muss ausdrücklich bestätigt werden.',partial:'Vorläufige Bewertung möglich, aber Bestätigung durch offene Angaben blockiert.',blocked:'Eine entscheidende Grundlage fehlt oder eine Eignungsprüfung spricht gegen die Option.',review:'Die zuständige Fachstelle muss ihre Prüfung und technischen Vorgaben dokumentieren.'}[s])}</span></p>`).join('')}</details>`;}
 function questionLinks(questions){return `<ul class="dm-blockers">${questions.map(q=>`<li><button type="button" data-ac-question="${q.id}">${e(q.prompt)}</button><small>${e(q.impact==='specialist'?'Zuständige Fachstelle erforderlich':q.impact==='blocking'?'Blockiert die Bestätigung':'Ergänzende Klärung')}</small></li>`).join('')}</ul>`;}
 function landing(){return `<header class="ac-intro"><span class="ac-kicker">Anforderungen verstehen · Entscheidungen erklären</span><h1>Architecture</h1><p class="ac-lead">Von einer Kundenanforderung zu einer nachvollziehbaren Azure-Architektur.</p><p>Das Tool hilft dabei, die richtigen Fragen zu stellen, fehlende Informationen zu erkennen und verschiedene Azure-Lösungen miteinander zu vergleichen.</p></header><section class="ac-hero"><span class="ac-kicker">CASE 01 · INTERAKTIVER DEMO-CASE · DECISION MODEL V1</span><h2>${e(data.title)}</h2><p>Bestehende Webanwendung, SQL-Datenbank, externe Partner und Verbindung zum eigenen Rechenzentrum.</p><button type="button" class="ac-primary" data-ac-start>Case starten →</button></section>`;}
 function outset(){return `<h2 id="ac-step-title" tabindex="-1">Was möchte der Kunde?</h2><blockquote class="ac-customer">Wir betreiben eine interne Webanwendung mit SQL-Datenbank auf Windows-Servern. Mitarbeiter und externe Partner sollen sie nutzen können. Wir möchten weniger Server selbst betreiben und die Kosten im vernünftigen Rahmen halten.</blockquote><section class="ac-card"><h3>Bekannte Ausgangslage</h3>${list(['app-baseline','sql-baseline','user-count','entra-present','erp-stays','vpn-present'].map(id=>model.state.answers[id].value||'Angabe noch offen'))}</section><section class="ac-card dm-goals"><h3>Ziele und Randbedingungen</h3>${list(['less-operations','private-db','personal-data','eu-constraint','budget'].map(id=>model.state.answers[id].value||'Angabe noch offen'))}<small>Bestätigungsstatus und Herkunft jeder Angabe sind in „Fragen klären“ sichtbar.</small></section><button type="button" class="ac-primary" data-ac-next>Mit der Analyse beginnen →</button>`;}
 function answerLabel(q){const a=model.state.answers[q.id];return `${information[a.type]} · ${a.origin==='demo_spec'?'Demo-Auftrag':a.origin==='local_demo'?'lokale Demo-Eingabe':'noch unbeantwortet'}${q.kind==='specialist'?' · '+(a.reviewStatus==='completed'?'Prüfung dokumentiert':'Prüfung offen'):''}`;}
 function editor(q){const a=model.state.answers[q.id];return `<details class="dm-edit" ${ui.editor===q.id?'open':''} data-ac-editor="${q.id}"><summary>Angabe im Demo-Modell bearbeiten</summary><form data-ac-answer-form="${q.id}"><p class="ac-hint">Nur lokale Simulation dieser Sitzung. Keine echte Kundenbestätigung oder rechtliche Freigabe. Leer bedeutet nicht „keine Abhängigkeit“.</p>${q.kind==='specialist'?`<label>Prüfstatus<select name="reviewStatus"><option value="open" ${a.reviewStatus!=='completed'?'selected':''}>Fachprüfung offen</option><option value="completed" ${a.reviewStatus==='completed'?'selected':''}>Prüfung durch Fachstelle dokumentiert</option></select></label><input type="hidden" name="type" value="specialist_review"><label>Zuständige Fachstelle<input name="reviewer" value="${e(a.reviewer)}"></label>`:`<label>Informationsstatus<select name="type">${['open_question','assumption','fact'].map(t=>`<option value="${t}" ${a.type===t?'selected':''}>${information[t]}</option>`).join('')}</select></label>`}<label>${q.kind==='specialist'?'Ergebnis / technische Anforderungen':'Antwort'}<textarea name="value" rows="2">${e(a.value)}</textarea></label>${q.kind==='assessment'?`<label>Eignungsbewertung<select name="verdict">${[['unknown','Noch offen'],['suitable','Geeignet – nach dokumentierter Prüfung'],['unsuitable','Nicht geeignet – nach dokumentierter Prüfung']].map(([v,l])=>`<option value="${v}" ${a.verdict===v?'selected':''}>${l}</option>`).join('')}</select></label>`:''}<label>Nachweis / Begründung<input name="evidence" value="${e(a.evidence)}" placeholder="Zum Beispiel dokumentierter Test oder Fachprüfung"></label><button type="submit">Im Demo-Modell übernehmen</button></form></details>`;}
 function question(q){const a=model.state.answers[q.id];const affected=data.areas.find(x=>x.id===q.areaId);return `<section class="dm-question${ui.step===1&&ui.focusQuestion===q.id?' dm-question-focused':''}" id="question-${q.id}" tabindex="-1"><h4>${e(q.prompt)}${q.optionId?' · '+e(title(refs[q.optionId])):''}</h4><span class="dm-info-type">${e(answerLabel(q))}</span><p>${e(a.value||'Noch keine Antwort vorhanden.')}</p>${q.id==='rto'?'<small>Fachbegriff: RTO – Recovery Time Objective · maximal tolerierte Ausfallzeit</small>':q.id==='rpo'?'<small>Fachbegriff: RPO – Recovery Point Objective · maximal tolerierter Datenverlust als Zeitraum</small>':''}<small>Entscheidung: ${e(affected.label)} · ${e(q.impact==='specialist'?'Fachprüfung erforderlich':q.impact==='blocking'?'Blockiert Bestätigung, solange ungeklärt':'Ergänzende Klärung')}</small>${q.kind==='assessment'?`<small>Bewertung: ${e({unknown:'Offen',suitable:'Geeignet',unsuitable:'Nicht geeignet'}[a.verdict])}</small>`:''}${help('Warum wird das gefragt?',q.why)}<details class="ac-help"><summary>Im Brain vertiefen</summary>${q.canonicalIds.map(id=>brain(id)).join('')}</details>${editor(q)}</section>`;}
 function discovery(){const selected=data.areas.find(a=>a.id===ui.topic);return `<h2 id="ac-step-title" tabindex="-1">Welche Informationen brauchen wir für die Entscheidungen?</h2><p>Sieben Entscheidungsbereiche. Angaben, Annahmen und Fachprüfungen sind getrennt; offene Punkte können im lokalen Demo-Modell bearbeitet werden.</p><div class="ac-topic-grid">${data.areas.map(a=>{const r=model.area(a.id);return `<button type="button" class="ac-topic ${ui.topic===a.id?'active':''}" data-ac-topic="${a.id}" aria-expanded="${ui.topic===a.id}"><b>${a.label}</b><small>${r.known} von ${r.total} relevanten Kriterien geklärt</small>${badge(r.status)}</button>`;}).join('')}</div>${selected?`<section class="ac-card ac-topic-detail"><h3>${selected.label}</h3><p>${selected.decisionQuestion}</p>${ui.error?`<p role="alert">${e(ui.error)}</p>`:''}${data.questions.filter(q=>q.areaId===selected.id).map(question).join('')}</section>`:'<p class="ac-hint">Wähle einen Entscheidungsbereich, um bekannte Angaben und offene Fragen zu sehen.</p>'}`;}
 function readiness(){return `<h2 id="ac-step-title" tabindex="-1">Welche Entscheidungen können wir bereits vorbereiten?</h2><p>Bekannte Ziele sind noch keine validierte Lösung. Die Kennzeichnung wird aus den relevanten Angaben, Annahmen und Prüfungen berechnet.</p><div class="ac-readiness">${data.areas.map(a=>{const r=model.area(a.id);return `<section class="ac-card"><div class="ac-card-head"><h3>${a.label}</h3>${badge(r.status)}</div><p>${e(r.reason)}</p><small>${e(a.decisionQuestion)}</small><details class="ac-help"><summary>Was blockiert die Bestätigung? (${r.blocking.length+r.specialist.length+r.incompatible.length})</summary>${questionLinks([...r.blocking,...r.specialist,...r.incompatible])}${r.notes.length?`<h4>Ergänzende Klärungen</h4>${questionLinks(r.notes)}`:''}</details><p><b>Nächster Schritt:</b> ${e(r.next)}</p>${a.id==='recovery'?`<small>Zielangaben: ${e(model.state.answers.rto.value||'RTO offen')} / ${e(model.state.answers.rpo.value||'RPO offen')}. Recovery-Strategie und Test werden separat bewertet.</small>`:''}</section>`;}).join('')}</div>`;}
 function compare(){return `<h2 id="ac-step-title" tabindex="-1">Welche Plattform passt zu denselben Kundenkriterien?</h2><p>Alle drei Optionen werden gegen dieselben Kriterien betrachtet. Eine Präferenz ist keine bestätigte Entscheidung.</p><div class="ac-options">${data.options.map(o=>{const a=model.state.answers[o.fitQuestion];const selected=model.state.decisions.compute.optionId===o.id;return `<section class="ac-card ${selected?'ac-preferred':''}"><span class="ac-kicker">${selected?'VORLÄUFIG FAVORISIERT':'PLATTFORMOPTION'}</span><h3>${e(title(o.canonicalId))}</h3><details class="ac-help"><summary>Einfach erklärt – aus dem Brain</summary><p>${e(definition(o.canonicalId))}</p></details>${data.comparisonCriteria.map(c=>`<h4>${c.label}</h4><p>${e(o.criteria[c.id])}</p>`).join('')}<div class="ac-open"><b>Voraussetzung: dokumentierte Anwendungseignung</b><p>${e(a.value||'Kompatibilität noch nicht nachgewiesen.')}</p><small>${e({unknown:'Prüfung offen',suitable:'Eignung dokumentiert',unsuitable:'Eignungsprüfung spricht gegen diese Option'}[a.verdict])}</small></div><button type="button" data-ac-question="${o.fitQuestion}">Offene Eignungsfrage ansehen</button><button type="button" data-ac-option="${o.id}">Als vorläufige Präferenz betrachten</button>${brain(o.canonicalId)}</section>`;}).join('')}</div><details class="ac-help"><summary>Welche gemeinsamen offenen Fragen beeinflussen den Vergleich?</summary>${questionLinks(model.area('compute').pending)}</details>`;}
 function preferenceRationale(d,o){
  const known=d.rationale.filter(r=>r.answer.type==='fact'&&model.resolved(r.question));
  // Only the existing original App Service rationale or an explicit suitable assessment supports a preference.
  // Other declared facts remain neutral context; no interpretation or new scoring of free-text answers.
  const supporting=o.id==='app'?known.filter(r=>r.answer.origin==='demo_spec'):[];
  const fit=model.questions.get(o.fitQuestion),fitAnswer=model.state.answers[fit.id];
  if(model.resolved(fit)&&fitAnswer.verdict==='suitable')supporting.push({question:fit,answer:fitAnswer});
  const neutral=known.filter(r=>!supporting.includes(r));
  return `${supporting.length?`<h4>Warum diese Option derzeit bevorzugt wird</h4>${list(supporting.map(r=>r.answer.value))}`:'<p class="ac-open">Aktuell nur manuell als vorläufige Präferenz ausgewählt. Eine belastbare unterstützende Begründung ist noch nicht dokumentiert.</p>'}${neutral.length?`<details class="ac-help"><summary>Bekannte Angaben für die weitere Prüfung – keine bestätigte Eignung</summary>${list(neutral.map(r=>r.answer.value))}</details>`:''}<details class="ac-help"><summary>Betriebsaufwand als Vergleichskriterium</summary><p>${e(o.criteria.operations)}</p></details>`;
 }
 function decisionView(){const id=ui.decisionArea,d=model.decision(id),a=data.areas.find(a=>a.id===id);const o=data.options.find(o=>o.id===d.optionId);return `<h2 id="ac-step-title" tabindex="-1">Was empfehlen wir – und was wurde tatsächlich entschieden?</h2><div class="dm-decision-areas">${data.areas.map(a=>`<button type="button" data-ac-decision="${a.id}" aria-pressed="${id===a.id}">${a.label}</button>`).join('')}</div><section class="ac-card ac-decision"><span class="ac-status ac-${d.status==='confirmed'?'ready':'partial'}">${d.status==='confirmed'?'🟢 Bestätigte Entscheidung im Demo-Modell':d.status==='needs_review'?'🟡 Bestätigung durch geänderte Angaben widerrufen':'🟡 Vorläufige Empfehlung – keine bestätigte Entscheidung'}</span><h3>${e(o?title(o.canonicalId):a.label)}</h3><p>${e(a.decisionQuestion)}</p>${id==='compute'?preferenceRationale(d,o):''}<p>${e(d.readiness.reason)}</p><details class="ac-help" open><summary>Vor einer Bestätigung noch zu klären</summary>${questionLinks([...d.readiness.pending,...d.readiness.incompatible])}</details>${id==='compute'?`<details class="ac-help"><summary>Abhängige Entscheidungen vor der Bestätigung</summary>${data.areas.filter(a=>a.id!=='compute'&&model.area(a.id).status!=='ready').map(a=>`<p>${a.label}: ${badge(model.area(a.id).status)}</p>`).join('')}</details>`:''}${id==='privacy'?'<p>Hier wird keine rechtliche Entscheidung getroffen. Prüfung und technische Vorgaben werden bei der zuständigen Fachstelle dokumentiert.</p>':`<form data-ac-confirm="${id}"><label>Dokumentierte Entscheidungsbegründung<textarea name="evidence" rows="2">${e(d.evidence)}</textarea></label><button type="submit" ${d.canConfirm?'':'disabled'}>Entscheidung ausdrücklich im Demo-Modell bestätigen</button><small>${d.canConfirm?'Kriterien geklärt; eine ausdrückliche Entscheidung ist weiterhin erforderlich.':'Bestätigung gesperrt: relevante Bedingungen sind noch offen oder widersprechen der Option.'}</small></form>`}${ui.error?`<p role="alert">${e(ui.error)}</p>`:''}</section>`;}
 function componentButton(id){const c=model.component(id);return `<button type="button" class="ac-component ${ui.component===id?'active':''}" data-ac-component="${id}" aria-pressed="${ui.component===id}"><span>${e(componentLabels[c.status])}${id==='entra'?' · vorhandener Dienst':''}</span><b>${e(title(c.canonicalId))}</b></button>`;}
 function diagram(){return `<section class="ac-diagram" aria-label="Vorläufiges Architektur-Zielbild"><div class="ac-auth"><b>Mitarbeiter und externe Partner</b><span>↔ Anmeldung / Token</span>${componentButton('entra')}</div><p class="ac-diagram-caption">Anmeldung und Webverkehr sind getrennt. „Bestätigt“ bei Entra ID meint den vorhandenen Dienst, keine bestätigte Zugriffslösung.</p><div class="ac-web-flow"><div class="ac-user">Benutzer<br>HTTPS-Webanfragen</div><span class="ac-arrow">→</span><div>${componentButton('gateway')}${componentButton('firewall')}</div><span class="ac-arrow">→</span>${componentButton('app')}</div><div class="ac-egress">↓ App Service → VNet-Integration für ausgehende private Zugriffe</div><div class="dm-db-layout"><div class="ac-network"><b>Azure Virtual Network · private Zugänge</b>${componentButton('vnet')}${componentButton('endpoint')}${componentButton('dns')}<div class="dm-net-branch">${componentButton('vpn')}<span>↔ Standortverbindung</span></div></div><div class="dm-sql-outside"><span>Privater Datenzugriff →</span><b>Verwalteter Dienst außerhalb des VNet</b>${componentButton('sql')}<small>${model.component('sql').status==='confirmed'?'Zielplattform im Demo-Modell bestätigt.':'Zielplattform vorgeschlagen; Migrationskompatibilität prüfen.'}</small></div></div><div class="ac-user dm-erp">Eigenes Rechenzentrum: ERP · über VPN verbunden</div><div class="ac-observe"><span>App Service → Betriebsdaten</span>${componentButton('monitor')}${componentButton('insights')}</div>${help('Welche Grenzen sind noch zu prüfen?','Das Bild zeigt vorgeschlagene logische Verbindungen. Private Endpoints ersetzen keine Zugriffskontrolle und deaktivieren öffentlichen SQL-Zugriff nicht automatisch. Eingang, DNS, Subnetze, ERP-Verbindung, Zugriffsregeln und Wiederherstellung bleiben an die offenen Case-Prüfpunkte gebunden.')}</section>`;}
 function causality(){const q=model.questions.get('private-db'),a=model.state.answers[q.id],c=model.component('endpoint'),d=model.decision('database');return `<details class="ac-causality" ${ui.why?'open':''}><summary>Warum sieht die Architektur so aus?</summary><ol>${[['Kundenangabe',a.value||'Private Erreichbarkeit noch offen'],['Bestätigungsstatus',answerLabel(q)],['Entscheidungskriterium','Private Erreichbarkeit der Datenbank'],['Entscheidung',d.status==='confirmed'?'Im Demo-Modell bestätigt':'Private Datenbankanbindung vorgeschlagen; Zielplattform noch zu prüfen'],['Architekturbaustein',`${title(c.canonicalId)} · ${componentLabels[c.status]}`]].map(([label,text])=>`<li><small>${label}</small><b>${e(text)}</b></li>`).join('')}</ol><div class="ac-brain-links">${['endpoint','vnet','dns','sql'].map(k=>brain(refs[k],true)).join('')}</div></details>`;}
 function waf(){return `<section class="ac-review"><h3>Architekturqualität prüfen</h3><p>Die fünf Perspektiven des bestehenden Architecture Quality Gate folgen den Case-Prüfpunkten. Kein automatisches „WAF bestanden“.</p>${help('Was ist WAF?','Azure Well-Architected Framework prüft Architekturqualität. Die Web Application Firewall im Diagramm ist ein anderer Begriff mit derselben Abkürzung.')}<div class="ac-review-grid">${data.reviewChecks.map(check=>{const r=model.review(check.id);return `<section class="ac-card"><h4>${check.label}</h4><small>${check.pillar}</small>${badge(r.status,r.status==='ready'?'Case-Prüfpunkte dokumentiert':r.status==='review'?'Fachprüfung erforderlich':'Review offen')}<p>${e(r.reason)}</p><details class="ac-help"><summary>Zugehörige Prüfpunkte (${r.pending.length})</summary>${questionLinks(r.pending)}</details></section>`;}).join('')}</div></section>`;}
 function adoption(){return `<section class="ac-card dm-adoption"><h3>Einführung und Verantwortung klären</h3><p>Wenige relevante Fragen aus dem vorhandenen CAF-/Adoption-Kontext, keine zusätzliche Theorie-Seite.</p>${data.adoptionChecks.map(c=>{const q=model.questions.get(c.questionId),a=model.state.answers[q.id];return `<div><b>${c.label}</b><p>${e(a.value||'Noch offen')}</p><button type="button" data-ac-question="${q.id}">Case-Frage klären</button>${brain(c.canonicalId)}</div>`;}).join('')}</section>`;}
 function architecture(){const preference=data.options.find(o=>o.id===model.state.decisions.compute.optionId);return `<h2 id="ac-step-title" tabindex="-1">Welche Architektur wird derzeit vorgeschlagen?</h2><p>Jeder Baustein zeigt seinen Status. Vorschläge sind keine fertig freigegebene Architektur.</p><section class="ac-card dm-diagram-context"><p><b>Aktuelle Compute-Präferenz:</b> ${e(title(preference.canonicalId))}</p><p><b>Gezeigtes Architektur-Referenzbild:</b> App-Service-basierte Baseline</p><p>Das Referenzbild wird bei einem Präferenzwechsel nicht automatisch neu entworfen. Es ist noch keine freigegebene Zielarchitektur.</p></section><div class="dm-component-legend">Bestätigt · Vorgeschlagen · Optional / Alternative · Offen</div>${diagram()}${causality()}${waf()}${adoption()}`;}
 function assistant(){const t=ui.step===1?data.areas.find(a=>a.id===ui.topic):null,c=ui.step===5&&ui.component?model.component(ui.component):null;const areaId=t?.id||(ui.step===4?ui.decisionArea:ui.step===3?'compute':null);const a=areaId?model.area(areaId):null;const selectedOption=ui.step===3?data.options.find(o=>o.id===model.state.decisions.compute.optionId):null;const stepHelp=['Wir beginnen bei Kundenproblem und Randbedingungen, bevor wir Dienste auswählen.','Eine Angabe kann bestätigt, angenommen, offen oder fachprüfpflichtig sein.','Readiness bezieht sich auf konkrete Entscheidungen, nicht nur auf bekannte Ziele.','Alle Optionen werden gegen dieselben Case-Kriterien betrachtet.','Eine Empfehlung wird nur durch eine ausdrückliche dokumentierte Bestätigung zur Entscheidung.','Vorgeschlagene Architekturbausteine bleiben mit ihren offenen Entscheidungen verbunden.'][ui.step];return `<aside class="ac-assistant"><span class="ac-kicker">${e(c?'ARCHITEKTURBAUSTEIN':t?t.label:steps[ui.step])}</span><h3>${e(c?title(c.canonicalId):'Assistent')}</h3><small>Deterministische Hilfe · keine KI</small>${c?`<h4>Einfach erklärt – aus dem Brain</h4><p>${e(definition(c.canonicalId))}</p><h4>Warum hier?</h4><p>${e(c.role)}</p><h4>Kundenangabe / Constraint</h4><p>${e(c.rationale.answer.value||'Noch offen')}</p><small>${e(information[c.rationale.answer.type])}</small><h4>Entscheidungskontext</h4><p>${e(data.areas.find(a=>a.id===c.areaId).decisionQuestion)}</p><span class="dm-info-type">${componentLabels[c.status]}</span><p>${e(c.readiness.reason)}</p>${brain(c.canonicalId)}`:`<p>${e(stepHelp)}</p>${selectedOption?`<h4>Aktuelle Präferenz: ${e(title(selectedOption.canonicalId))}</h4><p>${e(model.state.answers[selectedOption.fitQuestion].value||'Eignung noch offen; keine bestätigte Plattformentscheidung.')}</p>${brain(selectedOption.canonicalId)}`:''}${a?`<h4>Was muss noch geklärt werden?</h4><p>${e(a.next)}</p>${badge(a.status)}`:''}${t?brain(refs[t.brainKey]):''}`}<form class="ac-question-form" data-ac-help-form><label for="ac-own-question">Eigene Frage stellen …</label><textarea id="ac-own-question" rows="2">${e(ui.question)}</textarea><button type="submit">Demo-Hilfe anzeigen</button><p role="status">${e(ui.answer)}</p></form></aside>`;}
 function caseView(){const summary=model.summary();return `<header class="ac-case-head"><div><button type="button" class="ac-back" data-ac-home>← Architecture-Startseite</button><h1>${e(data.title)}</h1><small>Case 01 · Decision Model V1</small></div><div>${badge(summary.status)}${legend()}</div></header><div class="ac-demo-note">${e(data.provenance)} · Änderungen bleiben nur in dieser Sitzung.</div><nav class="ac-steps" aria-label="Case-Ablauf">${steps.map((s,i)=>`<button type="button" data-ac-step="${i}" ${ui.step===i?'aria-current="step"':''}><span>${i+1}</span>${s}</button>`).join('')}</nav><div class="ac-progress">Schritt ${ui.step+1} von 6 <span>${steps[ui.step]}</span></div><div class="ac-case-layout"><main class="ac-body">${[outset,discovery,readiness,compare,decisionView,architecture][ui.step]()}<nav class="ac-pagination">${ui.step>0?'<button type="button" data-ac-prev>← Zurück</button>':''}${ui.step>0&&ui.step<5?`<button type="button" class="ac-primary" data-ac-next>Weiter: ${steps[ui.step+1]} →</button>`:ui.step===5?'<small>MANUAL HUMAN REVIEW REQUIRED</small>':''}</nav><details class="ac-help"><summary>Lokale Demo zurücksetzen</summary><button type="button" data-ac-reset>Alle simulierten Angaben und Entscheidungen zurücksetzen</button><p>Die Demo-Vorgaben werden wiederhergestellt. Brain und andere Modi bleiben unverändert.</p></details></main>${assistant()}</div>`;}
 function render(){root=api.content;api.view.classList.toggle('ac-demo-view',ui.view!=='reference');if(ui.view==='reference')return false;api.sidebar.hidden=true;root.classList.add('ac-root');root.innerHTML=ui.view==='home'?landing():caseView();bind();root.scrollTop=ui.scroll;if(routeFocusPending){routeFocusPending=false;requestAnimationFrame(focusCurrentQuestion);}else if(returnFocusPending){returnFocusPending=false;requestAnimationFrame(()=>root.querySelector('#question-'+ui.focusQuestion)?.focus({preventScroll:true}));}api.status.textContent=ui.view==='home'?'Architecture · Decision Model V1':`Case 01 · Schritt ${ui.step+1} von 6`;return true;}
 function update(patch){ui.scroll=root.scrollTop;Object.assign(ui,patch);api.hash(ui);api.render();}
 function bind(){
  root.querySelectorAll('[data-ac-start]').forEach(b=>b.onclick=()=>start());root.querySelectorAll('[data-ac-home]').forEach(b=>b.onclick=home);
  root.querySelectorAll('[data-ac-step]').forEach(b=>b.onclick=()=>change({step:Number(b.dataset.acStep),component:null,editor:null}));
  root.querySelectorAll('[data-ac-next]').forEach(b=>b.onclick=()=>change({step:Math.min(5,ui.step+1),component:null,editor:null}));root.querySelectorAll('[data-ac-prev]').forEach(b=>b.onclick=()=>change({step:Math.max(0,ui.step-1),component:null,editor:null}));
  root.querySelectorAll('[data-ac-topic]').forEach(b=>b.onclick=()=>change({topic:ui.topic===b.dataset.acTopic?null:b.dataset.acTopic,editor:null}));
  root.querySelectorAll('[data-ac-question]').forEach(b=>b.onclick=()=>{const q=model.questions.get(b.dataset.acQuestion);change({step:1,topic:q.areaId,editor:q.id,focusQuestion:q.id,component:null});});
  root.querySelectorAll('[data-ac-component]').forEach(b=>b.onclick=()=>{update({component:b.dataset.acComponent});if(innerWidth<850)root.querySelector('.ac-assistant')?.scrollIntoView({block:'start'});});
  root.querySelectorAll('[data-ac-brain]').forEach(b=>b.onclick=()=>api.openBrain(b.dataset.acBrain));root.querySelectorAll('[data-ac-mindmap]').forEach(b=>b.onclick=()=>api.openMindmap(b.dataset.acMindmap));root.querySelectorAll('[data-ac-scenario]').forEach(b=>b.onclick=()=>api.openScenario(b.dataset.acScenario));
  root.querySelectorAll('[data-ac-option]').forEach(b=>b.onclick=()=>{model.selectOption(b.dataset.acOption);update({option:b.dataset.acOption});});root.querySelectorAll('[data-ac-decision]').forEach(b=>b.onclick=()=>change({decisionArea:b.dataset.acDecision}));
  root.querySelectorAll('[data-ac-editor]').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)ui.editor=d.dataset.acEditor;else if(ui.editor===d.dataset.acEditor)ui.editor=null;}));
  root.querySelectorAll('[data-ac-answer-form]').forEach(form=>form.addEventListener('submit',ev=>{ev.preventDefault();const values=Object.fromEntries(new FormData(form).entries());try{model.updateAnswer(form.dataset.acAnswerForm,values);update({error:'',editor:form.dataset.acAnswerForm});}catch(error){const alert=document.createElement('p');alert.setAttribute('role','alert');alert.textContent=error.message;form.querySelector('[role="alert"]')?.remove();form.append(alert);}}));
  root.querySelectorAll('[data-ac-confirm]').forEach(form=>form.addEventListener('submit',ev=>{ev.preventDefault();try{model.confirm(form.dataset.acConfirm,new FormData(form).get('evidence'));update({error:''});}catch(error){update({error:error.message});}}));
  root.querySelector('.ac-legend')?.addEventListener('toggle',ev=>{ui.legend=ev.target.open;});root.querySelector('.ac-causality')?.addEventListener('toggle',ev=>{ui.why=ev.target.open;});root.querySelector('#ac-own-question')?.addEventListener('input',ev=>ui.question=ev.target.value);
  root.querySelector('[data-ac-help-form]')?.addEventListener('submit',ev=>{ev.preventDefault();ui.answer='Demo-Hilfe für '+steps[ui.step]+': '+(ui.step===1&&ui.topic?model.area(ui.topic).next:'Offene Case-Kriterien prüfen; keine automatische Entscheidung.');root.querySelector('[role="status"]').textContent=ui.answer;});
  root.querySelector('[data-ac-reset]')?.addEventListener('click',()=>{model.reset();change({editor:null});});
 }
 return {ui,model,snapshot,restore,render,home,start,refs,reference(){ui.view='reference';api.view.classList.remove('ac-demo-view');api.sidebar.hidden=false;api.content.classList.remove('ac-root');},fromHash(params){if(params.get('case')==='case-01'){ui.view='case';const step=Number(params.get('step'));ui.step=Number.isFinite(step)?Math.max(0,Math.min(5,Math.trunc(step||1)-1)):0;const topic=({application:'compute',access:'identity',availability:'recovery',data:'database',cost:'operations'})[params.get('topic')]||params.get('topic');ui.topic=data.areas.some(a=>a.id===topic)?topic:null;ui.component=data.components.some(c=>c.id===params.get('component'))?params.get('component'):null;ui.option=data.options.some(o=>o.id===params.get('option'))?params.get('option'):null;const target=model.questions.get(params.get('question'));ui.focusQuestion=target?.id||null;if(target){ui.step=1;ui.topic=target.areaId;ui.editor=target.id;routeFocusPending=true;}}else if(params.get('scenario'))ui.view='reference';else ui.view='home';}};
}
window.ADB_ARCHITECTURE_CASE_V34={create,refs,steps};
})();
