// Learning presentation only. IDs refer to existing knowledge; arrows illustrate roles, not new canonical relations.
window.ADB_DEMO_LEARNING_V34 = (() => {
  const item=(label,note='',id=null)=>({label,note,id});
  function render(chapter,index,button){
    const overview=index===(chapter===1?6:chapter===3?4:chapter===6?8:5);
    const box=n=>`<div class="demo-node">${n.id?button(n.id,n.label):`<b>${n.label}</b>`}${n.note?`<small>${n.note}</small>`:''}</div>`;
    const flow=(nodes,label='Datenverkehr',focus=true)=>`<div class="demo-flow${focus&&!overview?' demo-focus':''}${label==='Namensauflösung'?' demo-resolution':''}" data-didactic-flow><span class="demo-action">${label}</span><div class="demo-chain">${nodes.map((n,i)=>box(n)+(i<nodes.length-1?`<span class="demo-arrow" aria-hidden="true">${label==='Zuweisung → wirksame Berechtigung'&&i<2?'+':label==='Messung ↔ Ziel ↔ Vereinbarung'?'↔':'→'}</span>`:'')).join('')}</div></div>`;
    const section=(title,body,note='')=>`<section class="demo-section${overview?' demo-overview':''}"><h2>${title}</h2>${body}${note?`<p class="demo-note">${note}</p>`:''}</section>`;
    const more=(title,body)=>`<details class="demo-more"><summary>${title}</summary>${body}</details>`;
    const app=item('Unsere Anwendung','Dasselbe Unternehmen aus Kapitel 1');
    const resource=item('Azure-Ressource','z. B. App Service, SQL oder Storage');
    const sql=item('Azure SQL Database','strukturierte Daten, z. B. Aufträge · SQL: Structured Query Language, eine Abfragesprache','azure-0731');
    const nsg=item('Network Security Group (NSG)','prüft: Darf diese Verbindung stattfinden?','azure-0864');
    const route=item('Route Table / UDR','Eigene Routen: User Defined Routes · entscheiden: wohin?','azure-0871');
    const vnet=item('Virtual Network (VNet)','unser privater Netzwerkraum','azure-0442');
    const monitor=item('Azure Monitor','Beobachtungsplattform für Ressourcen und Anwendungen','azure-0983');
    if(chapter===1){
      if(index!==2)return'';
      return section('Wie folgt die Kapazität unserem Bedarf?',flow([item('Bedarf steigt oder sinkt'),item('Kapazität anpassen','Skalierbarkeit: die Fähigkeit, Leistung zu verändern','azure-0014')],'Bedarf → passende Ressourcen')+
        more('Wie kann unsere Anwendung größer oder kleiner werden?',flow([item('Eine kleine Ressource'),item('Eine größere Ressource','Vertikale Skalierung: mehr Leistung pro Instanz','azure-0015')],'Größe ändern')+flow([item('Eine Instanz unserer Anwendung'),item('Mehrere Instanzen','Horizontale Skalierung: Anzahl erhöhen oder verringern','azure-0020')],'Anzahl ändern')+flow([item('Tatsächlicher Bedarf','wenig → viel → wenig'),item('Kapazität folgt dynamisch','Elastizität (Elasticity): automatisch passend anpassen','azure-0066')],'Bedarf beobachten → anpassen'))+
        more('Was verändert sich bei den Ausgaben?',flow([item('Eigene Hardware anschaffen'),item('Investitionsausgabe','Capital Expenditure (CapEx): Geld für Anschaffung','azure-0128')],'Eigene Server')+flow([item('Cloud-Leistung nach Nutzung beziehen'),item('Laufende Betriebsausgabe','Operational Expenditure (OpEx): Geld für laufenden Betrieb','azure-0132')],'Cloud-Ressourcen'))+
        flow([item('Bedarf und Kosten prüfen'),item('Nicht dauerhaft mehr bezahlen als benötigt','Kostenoptimierung (Cost Optimization) – Anforderungen weiter erfüllen','azure-1073')],'Passende Kapazität spart Leerlaufkosten'), 'Die Möglichkeit zur Anpassung ersetzt keine geeignete Architektur. Abrechnung und Skalierung hängen vom Dienst ab.');
    }
    if(chapter===2){
      const chosen=flow([app,item('Web App','Unsere Webanwendung'),item('Azure App Service','Azure betreibt die Webplattform; wir betreiben Anwendung und Daten','azure-0351')],'Wo läuft unsere Anwendung?',index===1);
      const data=flow([app,sql],'Wo liegen strukturierte Daten?',index===1)+flow([item('Dateien und Objekte','z. B. Bilder und Dokumente'),item('Storage Account','Verwaltungsrahmen für die Speicherdienste','azure-0579'),item('Azure Blob Storage','speichert die Objekte im Account','azure-0571')],'Wo liegen Dateien?',index===1);
      const resources=section('Unsere Anwendung braucht Ausführung und Daten',chosen+(index===1?more('Andere Ausführungsformen für dieselbe Aufgabe',more('Wenn wir einen virtuellen Computer selbst verwalten',flow([app,item('Azure Virtual Machines','Ein virtueller Computer (VM): Betriebssystem und Software bei uns','azure-0322'),item('Azure Managed Disks','Datenträger dieses Computers','azure-0567')],'Wenn wir den Computer selbst verwalten'))+more('Wenn wir Anwendung und Laufzeit gemeinsam verpacken',flow([app,item('Container Image','Anwendung und benötigte Laufzeit zusammen verpackt','azure-0413'),item('Azure Container Apps','verwaltete Ausführungsplattform startet das Paket','azure-1062')],'Wenn unsere Anwendung als Paket läuft'))+more('Wenn Code nur bei einem Ereignis benötigt wird',flow([item('Ereignis','z. B. eine neue Datei trifft ein'),item('Azure Functions','startet den passenden Anwendungscode','azure-0772'),item('Code wird ausgeführt','keine dauerhaft selbst betriebene Anwendung nötig')],'Wenn Code nur auf ein Ereignis reagieren soll')+'<p class="demo-note" data-learning-focus-for="azure-0771">Serverless Computing: Azure betreibt die Ausführung; wir konzentrieren uns auf Code und Ereignisse. Server gibt es weiterhin. Abrechnung hängt vom Hostingplan ab.</p>')):'')+data);
      const physical=section('Auch diese Ressourcen laufen auf realer Technik',flow([resource,item('Azure-Infrastruktur','physische Rechenzentren und Netzwerke'),item('Hardware im Rechenzentrum','Computer, Datenträger, Netzwerktechnik')],'Ressource → reale Infrastruktur',index===2));
      const zones=section('Wo ist die Infrastruktur getrennt?',flow([item('Azure-Region','geografischer Bereich mit Rechenzentren','azure-0237'),item('Availability Zones','getrennte Infrastruktur innerhalb einer unterstützten Region','azure-0007')],'Region enthält Zonen',index===3)+'<div class="demo-zones"><span>Zone 1<br>eigene Infrastruktur</span><span>Zone 2<br>eigene Infrastruktur</span><span>Zone 3<br>eigene Infrastruktur</span></div>'+flow([item('Zone 1 fällt aus','diese Instanz nicht erreichbar'),item('Geeignete Architektur nutzt Zone 2','die Anwendung kann weiterarbeiten'),item('Hohe Verfügbarkeit','High Availability: trotz eines Teilausfalls möglichst nutzbar bleiben','azure-0003')],'Teilausfall → weiterarbeiten',index===3), 'Das geschieht nicht allein durch die Wahl einer Region. Dienst, Konfiguration und Abhängigkeiten müssen dafür geeignet sein. Nicht jede Region und jeder Dienst unterstützen Zonen.');
      const management=section('Wie sagen wir Azure, was entstehen soll?',flow([item('Unser Team'),item('Portal / CLI / PowerShell / API','Portal: Weboberfläche · CLI: Command Line Interface (Befehlszeile) · API: Application Programming Interface (Programmschnittstelle)'),item('Azure Resource Manager (ARM)','gemeinsame Verwaltungsebene für Azure-Ressourcen','azure-0284'),resource],'Anfordern → bereitstellen und verwalten',index===4)+more('Auch ohne jede Ressource einzeln anzuklicken',flow([item('Gewünschten Zustand als Code beschreiben','Infrastructure as Code (IaC)','azure-0301'),item('Azure Resource Manager','setzt die Ressourcenbeschreibung um','azure-0284'),resource],'Beschreibung → Bereitstellung',index===4)+'<p class="demo-note">CLI und PowerShell sind ebenfalls Verwaltungszugänge: '+button('azure-0810','Azure CLI')+' · '+button('azure-0809','Azure PowerShell')+'</p>'));
      if(index===0)return section('Aus dem Prinzip wird eine konkrete Plattform',flow([item('Cloud Computing','IT bei Bedarf beziehen','azure-1101'),item('Microsoft Azure','Cloud-Plattform von Microsoft')],'Prinzip → Plattform'),'Microsoft Azure ordnen wir hier über die bestehenden Cloud- und Azure-Grundlagen ein: '+button('azure-1100','Cloud & Azure Foundations'));
      if(index===1)return resources;
      const context=section('Bereits aufgebaut: unsere Anwendung in Azure',chosen+data,'Die drei Aufgaben gehören zu derselben Anwendung. Die Pfeile zeigen Aufgaben und Zuordnung, keinen durchgehenden Datenweg zwischen den Ressourcen.');
      if(index===2)return context+physical;
      if(index===3)return context+physical+zones;
      if(index===4)return context+more('Bereits gelernt: physische Infrastruktur, Regionen und Zonen',physical+zones)+management;
      return section('Cloud → Azure → konkrete Ressourcen',flow([item('Cloud-Prinzip'),item('Microsoft Azure','stellt Ressourcen bereit','azure-1100'),resource],'Plattform im Zusammenhang',false))+resources+physical+zones+management+more('Geplante Ressourcen grob kalkulieren',flow([item('Geplante Ressourcen','Region, Größe und Nutzung annehmen'),item('Pricing Calculator','Kostenschätzung vor Bereitstellung','azure-1032')],'Planung → grobe Schätzung',false)+'<p class="demo-note">Eine Schätzung ist kein verbindlicher Endpreis.</p>');
    }
    if(chapter===4){
      const actor=section('Menschen und Anwendungen möchten zugreifen',flow([item('Mitarbeiter oder Administrator'),resource],'Mensch → Zugriffswunsch',index===0)+flow([item('Unsere Azure-Anwendung'),resource],'Anwendung → Zugriffswunsch',index===0));
      const identity=section('Welche Identität gehört zu welchem Akteur?',flow([item('Mitarbeiter'),item('Entra User','Benutzerkonto repräsentiert eine Person','azure-1068')],'Person → Benutzerkonto',index===1)+flow([item('Team'),item('Entra Group','Gruppe bündelt Personen für gemeinsame Zuweisungen','azure-1068')],'Team → Gruppe',index===1)+flow([item('Azure-Anwendung'),item('Managed Identity','eigene, automatisch verwaltete Anwendungsidentität','azure-0947')],'Anwendung → verwaltete Identität',index===1),button('azure-0904','Microsoft Entra ID')+' bildet die Identitätsbasis. Eine Gruppe ist noch keine Berechtigung. Die Anwendung muss für ihre verwaltete Identität kein Passwort im Code speichern.');
      const authentication=section('Wer bist du wirklich?',flow([item('Identität des Mitarbeiters'),item('Anmeldung prüfen','Authentifizierung bestätigt die Identität','azure-0903'),item('Bei Bedarf: zusätzlichen Nachweis verlangen','Multi-Factor Authentication (MFA): mehrere unabhängige Faktoren','azure-0928')],'Identität → Nachweis',index===2)+more('Wann reicht eine einfache Anmeldung nicht?',flow([item('Mitarbeiter meldet sich an'),item('Bedingungen prüfen','Conditional Access (bedingter Zugriff)','azure-0912'),item('z. B. MFA oder verwaltetes Gerät','die verlangte Bedingung muss erfüllt sein'),item('Anmeldung / Zugriff unter diesen Bedingungen möglich','Azure-Ressourcenrechte prüft anschließend RBAC')],'Anmeldebedingungen',index===2)), 'Dieses Anmeldebeispiel gilt für Menschen. Eine Managed Identity nutzt keine interaktive Mitarbeiter-Anmeldung. Erfolgreich angemeldet heißt nicht: jede Aktion erlaubt.');
      const authorization=section('Was darf die bestätigte Identität tun?',flow([item('Bestätigte Identität'),item('Azure RBAC','Role-Based Access Control: Autorisierungssystem für Azure-Ressourcen','azure-0964'),item('Rolle beschreibt die Aktionen','In unserem Beispiel: Ansehen ✓ · Ändern –','azure-0967')],'Identität → erlaubte Aktionen',index===3));
      const assignment=section('Wo sollen diese Rechte gelten?',flow([item('Identität','wer?'),item('Rolle','welche Aktionen?','azure-0967'),item('Scope','wo? Hier: Resource Group unserer Anwendung','azure-0968'),item('Role Assignment','verbindet Identität + Rolle + Scope innerhalb von Azure RBAC','azure-0965')],'Zuweisung → wirksame Berechtigung',index===4)+flow([item('Ansehen als nötige Aufgabe'),item('Nur unsere Resource Group','keine Rechte in ganz Azure'),item('Least Privilege','nur nötige Rechte – nur dort und so lange wie benötigt','azure-0966')],'Berechtigung passend begrenzen',index===4), 'Die bekannte Hierarchie ist der Geltungsbereich: Management Group → Subscription → Resource Group → Ressource. Identität, Rolle und Scope sind Bestandteile einer Zuweisung, keine aufeinanderfolgenden Prüfsysteme.');
      if(index===0)return actor;
      if(index===1)return more('Bekannter Kontext: Menschen und Anwendung',actor)+identity;
      if(index===2)return more('Bekannter Kontext: Identitäten in Entra ID',identity)+authentication;
      if(index===3)return section('Bereits bestätigt',flow([item('Mitarbeiter'),item('Entra-Identität'),item('Authentifizierung','Nachweis erfolgreich')],'Bekannter Anmeldekontext',false))+authorization;
      if(index===4)return authorization+assignment;
      return '<div class="access-synthesis">'+section('Menschen und Anwendungen: Identität prüfen, passende Rechte zuweisen',flow([item('Mitarbeiter'),item('Microsoft Entra ID','Identität','azure-0904'),item('Authentifizierung','Wer bist du?','azure-0903'),item('Azure RBAC','Rolle + Scope per Role Assignment','azure-0964'),resource],'Zugriff eines Menschen',false)+flow([item('Unsere Azure-Anwendung'),item('Managed Identity','Anwendungsidentität','azure-0947'),item('Identität nachweisen','ohne interaktive Mitarbeiter-Anmeldung'),item('Azure RBAC','passende Zielberechtigung','azure-0964'),resource],'Zugriff einer Anwendung',false), 'Die Identität ersetzt keine Berechtigung. Auch der Netzwerkzugriff zum Ziel muss möglich sein.')+'</div>'+more('Optionale Vertiefung: Wie nutzt eine Anwendung das praktisch?',flow([item('App Service','unsere Anwendung','azure-0351'),item('Managed Identity','Anwendungsidentität','azure-0947'),item('Azure RBAC','passende Zielberechtigung','azure-0964'),item('Azure Key Vault','speichert Geheimnisse, Schlüssel und Zertifikate zentral','azure-0944')],'Zugriff unserer Anwendung',false)+flow([item('Anwendung braucht ein Geheimnis'),item('Kontrolliert aus Key Vault abrufen','Secrets Management: Geheimnisse nicht im Anwendungscode speichern','azure-0945')],'Sicherer Umgang mit Geheimnissen',false))+more('Rolle = was? · Scope = wo?',assignment);
    }
    if(chapter===5){
      if(index!==3&&index!==5)return'';
      return section('Was kostet unsere Anwendung – und wer bemerkt eine Überschreitung?',flow([resource,item('Tags','Umgebung oder Kostenstelle zuordnen','azure-0980'),item('Microsoft Cost Management','Kosten beobachten und auswerten','azure-1034')],'Ressourcen → Kostenzuordnung',index===3)+more('Von der Zuordnung zur Kostenwarnung',flow([item('Microsoft Cost Management','wertet die verfügbaren Kosten aus','azure-1034'),item('Cost Analysis','Kosten einer Umgebung / Kostenstelle filtern und prüfen','azure-1072'),item('Budget','Welchen Kostenrahmen wollen wir einhalten?','azure-0033'),item('Cost Alert','Bei erreichter Ist- oder Prognoseschwelle informieren','azure-0033'),item('Verantwortliches Team','prüft die Kosten und reagiert')],'Auswertung → Rahmen → Benachrichtigung',index===3)), 'Tags sind Metadaten und keine Sicherheitsgrenze. Kostenanalysen nutzen verfügbare Tag- und Kostendaten. Ein Budget meldet Schwellen; es stoppt Ressourcen nicht automatisch.');
    }
    if(chapter===6){
      if(index===0)return'';
      if(index===1)return section('Erlaubnis und Weg beantworten verschiedene Fragen',flow([item('Verbindung aus dem Subnet'),nsg,item('Erlaubt oder blockiert','prüft Kommunikation, wählt keinen Weg')],'Darf die Verbindung stattfinden?')+flow([item('Verkehr aus dem Subnet'),route,item('Gewählter nächster Weg')],'Wohin wird der Verkehr geleitet?')+more('Wenn unsere private Ressource ins Internet muss',flow([item('Private Ressource im Subnet'),item('Azure NAT Gateway','Network Address Translation: ausgehenden Internetzugang bereitstellen','azure-1059'),item('Internet','Antworten auf ausgehende Verbindungen sind möglich')],'Optionaler Ausgang')+'<p class="demo-note">NAT stellt den Ausgang bereit. Es ist keine zentrale Prüfung von Netzwerk- oder Webregeln.</p>')+more('Wenn Verkehr zentral geprüft werden soll',flow([item('Subnet'),route,item('Azure Firewall','prüft und protokolliert anhand zentraler Regeln','azure-0841'),item('Internet oder anderes Netz')],'Weg zur zentralen Kontrolle')), 'NAT und Firewall sind unterschiedliche Ansätze; sie müssen nicht beide als Pflichtkette in jeder Architektur vorkommen.');
      if(index===2)return section('Ein Name hilft beim Finden – transportiert aber keine Anwendungsdaten',flow([app,item('DNS: Domain Name System','Anwendung fragt einen Namen an'),item('Adresse erhalten','DNS ermittelt die passende Internet-Protocol-Adresse (IP-Adresse)')],'Namensauflösung')+flow([app,item('Ziel an dieser Adresse','direkte Verbindung nach der Auflösung')],'Datenverkehr')+more('Wer verwaltet die Namen in Azure?',flow([item('Öffentliche Dienstnamen'),item('Azure DNS','hostet öffentliche DNS-Zonen und deren Einträge','azure-0545')],'Öffentliche Namensräume')+flow([item('Interne Dienstnamen im privaten Netz'),item('Azure Private DNS','private Zonen für verknüpfte VNets','azure-0558'),item('Private Zieladresse')],'Namensauflösung')), 'Azure DNS verwaltet Zoneneinträge. Die Namensauflösung nutzt solche Einträge, um eine Adresse zu ermitteln. Anschließend verbindet sich die Anwendung direkt zum Ziel.');
      if(index===3)return section('Der Name findet den privaten Zugang; die Daten nehmen ihren eigenen Weg',flow([item('Name des Datendienstes'),item('Private DNS','passender Namenseintrag','azure-0558'),item('Private Adresse des Private Endpoint')],'Namensauflösung')+flow([app,item('Private Endpoint','private IP-Adresse im VNet','azure-0881'),sql],'Datenverkehr')+'<p class="demo-note">'+button('azure-0882','Azure Private Link')+' ist die Technik hinter der Verbindung vom Private Endpoint zur Dienstressource. Private DNS leitet keine Anwendungsdaten weiter.</p>'+more('Warum gibt es unterschiedliche Zugriffsmodelle?',flow([app,item('Public Endpoint','öffentlicher Dienstendpunkt; Zugriffskontrollen weiterhin nötig','azure-0884'),sql],'Öffentlicher Zugang')+flow([item('Unser Subnet'),item('Service Endpoint','Azure-Backbone; Dienstzugriff auf zugelassene VNets begrenzen','azure-0878'),item('Öffentlicher Dienstendpunkt','bleibt öffentlich adressiert; keine private IP im VNet')],'Zugang mit Subnet-Zuordnung')+flow([item('Unser VNet'),item('Private Endpoint','privater Zugang im VNet','azure-0881'),sql],'Privater Zugang')), 'Wir wählen den Private Endpoint für unsere Beispieldatenbank. Der öffentliche Zugriff des Dienstes wird dadurch nicht automatisch abgeschaltet.');
      if(index===4)return section('Ein weiteres Netz braucht eine passende Verbindung',flow([item('Zweites Azure-VNet'),item('VNet Peering','verbindet passende Azure-Netzwerke','azure-0887'),vnet],'Azure-Netz ↔ Azure-Netz')+flow([item('Lokales Rechenzentrum','On-Premises'),item('Verschlüsselter Tunnel','Site-to-Site (S2S) Virtual Private Network (VPN)'),item('VPN Gateway','Azure-Seite des Tunnels','azure-0462'),vnet],'Standort ↔ Azure über öffentliche Infrastruktur')+more('Alternative: eine private Verbindung statt des Internet-Tunnels',flow([item('Lokales Rechenzentrum'),item('ExpressRoute','private Verbindung über einen Anbieter','azure-0478'),item('ExpressRoute Gateway','bindet diese Verbindung an das VNet an','azure-0493'),vnet],'Privater Verbindungsweg')+'<p class="demo-note">ExpressRoute ist die Verbindung; das Gateway ist der Anschluss des VNets. Die Verbindung ist nicht allein deshalb verschlüsselt.</p>')+more('Wenn viele Standorte zusammenkommen',flow([item('Standorte A, B und C'),item('Azure Virtual WAN','zentral verwaltete Hubs für Verbindungen und Transit','azure-1058'),item('Azure-Netze')],'Viele Standorte → zentraler Transit'))+more('Wie finden beide Seiten private Dienstnamen?',flow([item('DNS im lokalen Netz'),item('Azure DNS Private Resolver','ermöglicht hybride Namensauflösung über konfigurierte Weiterleitung','azure-1060'),item('Azure Private DNS','private Azure-Namen','azure-0558')],'Namensauflösung')+'<p class="demo-note">Mit passenden Ein- und Ausgangspfaden lassen sich Namen zwischen lokalem Netz und Azure auflösen. Das ist kein Pfad für die eigentlichen Anwendungsdaten.</p>'));
      if(index===5)return section('Welche Aufgabe hat der Einstieg zur Anwendung?',flow([item('Benutzer'),item('Application Gateway + WAF','regionaler Einstieg und Schutz für Webanfragen','azure-0519'),app],'Regionaler Webzugriff')+'<p class="demo-note">Webkommunikation: Hypertext Transfer Protocol (HTTP), verschlüsselt Hypertext Transfer Protocol Secure (HTTPS). '+'Layer-7-Routing'+' wählt anhand von Webinformationen: Hostname oder Pfad der Webadresse (Uniform Resource Locator, URL). '+button('azure-0863','Web Application Firewall (WAF)')+' prüft typische Angriffsmuster direkt an diesem Webzugriff.</p>'+more('Mehrere passende Instanzen innerhalb des Netzes erreichen',flow([item('Netzwerkverbindungen'),item('Load Balancer','verteilt auf gesunde, passende Instanzen','azure-0505'),item('Instanz 1 / Instanz 2 / Instanz 3','die gleiche Anwendung läuft mehrfach')],'Verbindungen verteilen'))+more('Benutzer weltweit vor regionalen Webanwendungen empfangen',flow([item('Benutzer weltweit'),item('Azure Front Door','globaler Web-Proxy: Anfragen laufen durch diesen Einstieg','azure-0562'),item('Region A oder Region B','gesunde regionale Anwendung')],'Globaler Webzugriff'))+more('Nur per DNS das Ziel auswählen lassen',flow([item('DNS-Anfrage des Benutzers'),item('Traffic Manager','wählt ein geeignetes öffentliches Ziel','azure-0560'),item('Antwort mit ausgewähltem Ziel')],'Namensauflösung')+flow([item('Benutzer'),item('Ausgewähltes Ziel','direkte Verbindung; kein Traffic Manager im Datenpfad')],'Datenverkehr')+'<p class="demo-note">Traffic Manager ist kein Web-Proxy. DNS-Caching kann beeinflussen, wann ein neues Ziel verwendet wird.</p>'), 'Diese Rollen beantworten unterschiedliche Anforderungen. Sie sind keine Pflichtkette aus vier Produkten.');
      if(index===6)return section('Beobachten → verstehen → reagieren',flow([item('Anwendung · SQL · Gateway · Netzwerk','bekannte Umgebung liefert passende Beobachtungsdaten'),monitor],'System beobachten')+flow([monitor,item('Metrics','Messwerte über Zeit: Prozessorlast, Antwortzeit, Anzahl Anfragen','azure-1074')],'Messwerte verstehen')+flow([monitor,item('Logs','detaillierte Ereignisse und Protokolle','azure-0986')],'Ereignisse verstehen')+more('Was erlebt die Anwendung selbst?',flow([app,item('Application Insights','Anfragen, Fehler, Antwortzeiten und Abhängigkeiten','azure-0987'),monitor],'Anwendung verstehen'))+more('Wie erfährt unser Team, dass es handeln muss?',flow([item('Messwert oder Log'),item('Bedingung erfüllt?','z. B. ungewöhnlich viele fehlgeschlagene Anfragen'),item('Azure Monitor Alert','technisches Signal einer erfüllten Regel','azure-0984'),item('Unser Team','wird informiert und reagiert')],'Bedingung → Signal → Reaktion')), 'Metrics und Logs sind parallele Beobachtungsformen, nicht zwei hintereinander laufende Datenspeicher. Welche Daten gesammelt werden, muss passend eingerichtet sein.');
      if(index===7)return section('Unsere Anwendung funktioniert – was passiert bei einem Ausfall?',flow([item('Ein Teil fällt aus'),item('Geeigneter anderer Teil arbeitet weiter','High Availability aus Kapitel 2','azure-0003'),item('Anwendung bleibt möglichst nutzbar')],'Teilausfall abfangen')+'<p class="demo-note">'+button('azure-0070','Reliability / Resilience')+': zuverlässig funktionieren und Fehler verkraften beziehungsweise wieder arbeitsfähig werden. Eine einzelne redundante Komponente garantiert nicht das ganze System.</p>'+more('Welche Grenzen setzt unser Geschäft für den Wiederanlauf?',flow([item('Wie lange darf die Anwendung maximal ausfallen?'),item('Recovery Time Objective (RTO)','Ziel für die maximal tolerierte Wiederanlaufzeit','azure-1076')],'Akzeptierte Ausfallzeit')+flow([item('Wie viele Daten dürfen maximal verloren gehen?'),item('Recovery Point Objective (RPO)','zeitlicher Rückstand des wiederhergestellten Datenstands','azure-1076')],'Akzeptierter Datenverlust'))+more('Wie bekommen wir Daten und Betrieb zurück?',flow([item('Unterstützte Daten / Workloads'),item('Azure Backup','gesicherte Wiederherstellungspunkte','azure-0116'),item('Wiederherstellung','früheren Datenstand zurückbringen')],'Daten sichern → wiederherstellen')+flow([item('Größerer Ausfall'),item('Vorbereiteter Wiederanlauf','Disaster Recovery (DR)','azure-0114'),item('Andere Umgebung / anderer Standort','Abhängigkeiten und Daten müssen vorbereitet sein')],'Betrieb wieder aufnehmen')+'<p class="demo-note">Backup hält den laufenden Dienst nicht automatisch verfügbar. Wiederherstellung und Wiederanlauf müssen geplant und getestet werden.</p>')+more('Wie vergleichen wir tatsächliche und zugesagte Leistung?',flow([item('Was messen wir tatsächlich?','Service Level Indicator (SLI): z. B. Anteil erfolgreicher Anfragen','azure-1042'),item('Welches Ziel setzen wir uns?','Service Level Objective (SLO): internes messbares Ziel','azure-1042'),item('Was wurde verbindlich zugesichert?','Service Level Agreement (SLA): vertragliche Leistung','azure-1042')],'Messung ↔ Ziel ↔ Vereinbarung')+'<p class="demo-note">Die Vereinbarung wird nicht automatisch aus Messung und Ziel erzeugt. Ein Azure-Dienst-SLA ist keine Garantie für unsere gesamte Anwendung.</p>'));
      return section('Beobachtung und Wiederanlauf wirken auf die ganze Umgebung',flow([item('Unser aufgebautes Gesamtsystem'),monitor,item('Team','bewertet Signale und reagiert')],'Betrieb beobachten',false)+flow([item('Teilausfall oder größerer Ausfall'),item('Reliability / Resilience','weiterarbeiten oder geplant wiederherstellen','azure-0070'),item('Unsere Anwendung','Ziele und Wiederanlauf überprüfen')],'Ausfälle beherrschen',false))+section('Mehrere Schutzschichten ergänzen einander', '<div class="demo-layers">'+[item('Identität + RBAC','Wer darf was und wo?','azure-0964'),item('WAF am Web-Einstieg','Webangriffsmuster prüfen','azure-0863'),item('Firewall / NSG am Netzwerk','Verbindungen kontrollieren','azure-0841'),item('Private Endpoint am Datendienst','privater Netzwerkzugang','azure-0881')].map(box).join('')+'</div>',button('azure-0817','Defense in Depth')+': Sicherheit entsteht durch mehrere Schutzschichten. Diese Kontrollen sind keine einzelne lineare Transportkette.')+'<p class="demo-conclusion">Die konkrete Architektur hängt von Benutzern, Standorten, Sicherheit, Verfügbarkeit, Leistung, Kosten und Betrieb ab.</p>';
    }
    return'';
  }
  return {render};
})();
