import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonical = path.join(project, 'data/canonical');
const today = '2026-08-11';
const read = name => JSON.parse(fs.readFileSync(path.join(canonical, name), 'utf8'));
const write = (name, value) => fs.writeFileSync(path.join(canonical, name), `${JSON.stringify(value, null, 2)}\n`);

const nodesDocument = read('nodes.json');
const relationsDocument = read('relations.json');
const sourcesDocument = read('sources.json');
const typesDocument = read('relation-types.json');
const nodeById = new Map(nodesDocument.nodes.map(node => [node.id, node]));

const officialSources = [
  {id:'ms-vm-overview',title:'Virtual machines in Azure',url:'https://learn.microsoft.com/en-us/azure/virtual-machines/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vm-sizes',title:'Sizes for virtual machines in Azure',url:'https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-managed-disks',title:'Introduction to Azure Managed Disks',url:'https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-availability-sets',title:'Availability sets overview',url:'https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vmss-overview',title:'What are Virtual Machine Scale Sets?',url:'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vmss-autoscale',title:'Overview of autoscale with Virtual Machine Scale Sets',url:'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-autoscale-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vmss-repair',title:'Automatic instance repairs for Virtual Machine Scale Sets',url:'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-instance-repairs',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-app-service',title:'App Service overview',url:'https://learn.microsoft.com/en-us/azure/app-service/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-app-service-plan',title:'What are Azure App Service plans?',url:'https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-app-service-patching',title:'Azure App Service OS and runtime patching',url:'https://learn.microsoft.com/en-us/azure/app-service/overview-patch-os-runtime',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-app-service-slots',title:'Set up staging environments in Azure App Service',url:'https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-aci-overview',title:'What is Azure Container Instances?',url:'https://learn.microsoft.com/en-us/azure/container-instances/container-instances-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-aci-groups',title:'Container groups in Azure Container Instances',url:'https://learn.microsoft.com/en-us/azure/container-instances/container-instances-container-groups',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-aks-overview',title:'What is Azure Kubernetes Service (AKS)?',url:'https://learn.microsoft.com/en-us/azure/aks/what-is-aks',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-aks-support',title:'Support policies for Azure Kubernetes Service',url:'https://learn.microsoft.com/en-us/azure/aks/support-policies',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-container-options',title:'Comparing AKS with other Azure container options',url:'https://learn.microsoft.com/en-us/azure/aks/compare-container-options-with-aks',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-vm',title:'Monitor virtual machines in Azure',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/vm/monitor-vm',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-log-analytics',title:'Overview of Log Analytics in Azure Monitor',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-aks',title:'Monitor Azure Kubernetes Service',url:'https://learn.microsoft.com/en-us/azure/aks/monitor-aks',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-servers',title:'Defender for Servers',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-servers-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-jit-vm',title:'Just-in-time virtual machine access',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/just-in-time-access-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vm-backup',title:'An overview of Azure VM backup',url:'https://learn.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-site-recovery',title:'About Azure Site Recovery',url:'https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-vm-maintenance',title:'Guest updates and host maintenance overview',url:'https://learn.microsoft.com/en-us/azure/virtual-machines/updates-maintenance-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'}
];

const extraRelationTypes = [
  {id:'deployed_in',label:'wird bereitgestellt in',inverse_type:'hosts',inverse_label:'hostet',description:'Eine Compute-Ressource wird innerhalb des Zielkontexts bereitgestellt.',color:'#43a6ff',priority:92,symmetric:false},
  {id:'hosts',label:'hostet',inverse_type:'deployed_in',inverse_label:'wird bereitgestellt in',description:'Ein Infrastruktur- oder Plattformkontext hostet die verbundene Compute-Ressource.',color:'#43a6ff',priority:92,symmetric:false},
  {id:'logs_to',label:'schreibt Logs nach',inverse_type:'receives_logs_from',inverse_label:'empfängt Logs von',description:'Das Quellobjekt sendet Protokoll- oder Telemetriedaten an das Ziel.',color:'#ff9c54',priority:86,symmetric:false},
  {id:'receives_logs_from',label:'empfängt Logs von',inverse_type:'logs_to',inverse_label:'schreibt Logs nach',description:'Das Objekt empfängt Protokoll- oder Telemetriedaten vom verbundenen Quellobjekt.',color:'#ff9c54',priority:86,symmetric:false}
];

const E = {
  'azure-0005': {title:'Availability Set',simple:'Ein Availability Set verteilt mehrere virtuelle Maschinen so, dass geplante Wartung oder ein einzelner Hardwarefehler nicht alle Instanzen gleichzeitig betrifft. Es wird für Hochverfügbarkeit innerhalb eines Rechenzentrums eingesetzt.',technical:'Azure ordnet VMs eines Availability Sets verschiedenen Fault Domains und Update Domains zu. Fault Domains trennen gemeinsame Strom- und Netzwerkkomponenten; Update Domains begrenzen gleichzeitige Plattformwartung. Die Anwendung benötigt mindestens zwei redundante Instanzen.',architecture:'Availability Sets sind sinnvoll für bestehende VM-Architekturen in Regionen oder Szenarien ohne Availability Zones und können geringe VM-zu-VM-Latenz bieten. Sie schützen nicht vor einem vollständigen Rechenzentrumsausfall und sind weniger resilient als zonenredundante Designs. Für neue hochverfügbare Plattformen sind zonenfähige VM Scale Sets häufig die bessere Wahl.',why:'Der Mechanismus reduziert korrelierte Ausfälle, ohne die Anwendung selbst hochverfügbar zu machen.',examples:['Zwei Webserver laufen in einem Availability Set hinter einem Load Balancer, damit Wartung nicht beide gleichzeitig stoppt.'],merksatz:'Availability Set trennt Fehler- und Wartungsdomänen, nicht Rechenzentren.',sources:['ms-availability-sets'],tags:['availability-set','high-availability','fault-domain']},
  'azure-0007': {title:'Availability Zones',simple:'Availability Zones sind physisch getrennte Standorte innerhalb einer Azure-Region. Mehrere Instanzen über Zonen hinweg schützen eine Anwendung vor dem Ausfall eines einzelnen Rechenzentrums.',technical:'Jede Zone besitzt unabhängige Stromversorgung, Kühlung und Netzwerkkomponenten, ist aber über regionale Netzwerke mit den anderen Zonen verbunden. Ressourcen können zonal in einer bestimmten Zone oder zonenredundant über mehrere Zonen bereitgestellt werden. Die Anwendung muss Daten, Netzwerkpfade und Zustände passend replizieren.',architecture:'Architekten wählen Zonen für geschäftskritische Workloads mit höherem Resilienzziel als ein Availability Set. Der Gewinn an Ausfallsicherheit steht zusätzlicher Architekturkomplexität, möglicher zonenübergreifender Latenz und Datentransferkosten gegenüber. Eine Zone schützt nicht vor einem kompletten Regionsausfall.',why:'Zonen verschieben die Fehlergrenze vom Rack oder Cluster auf ein getrenntes Rechenzentrum.',examples:['Drei VMSS-Instanzen werden über drei Availability Zones verteilt und über einen Load Balancer angesprochen.'],merksatz:'Zone schützt vor Datacenter-Ausfall; Regionenschutz braucht eine zweite Region.',sources:['ms-zones-overview','ms-vmss-overview'],tags:['availability-zone','resilience','region']},
  'azure-0015': {title:'Vertikale Skalierung (Scale up / down)',simple:'Vertikale Skalierung gibt einer einzelnen Instanz mehr oder weniger CPU, Arbeitsspeicher oder andere Leistung. Sie wird verwendet, wenn eine Anwendung nicht auf mehrere Instanzen verteilt werden kann oder kurzfristig mehr Kapazität benötigt.',technical:'Bei VMs bedeutet Scale up meist den Wechsel auf eine größere VM-Größe; bei App Service den Wechsel des Plan-Tiers. Die verfügbare Kapazität bleibt an eine Instanz oder einen Plan gebunden. Je nach Dienst kann die Größenänderung einen Neustart oder eine Unterbrechung auslösen.',architecture:'Vertikales Skalieren ist einfach und oft passend für zustandsbehaftete oder lizenzgebundene Systeme. Es besitzt jedoch eine obere SKU-Grenze, erhöht häufig den Ausfallradius einer Instanz und liefert keine Redundanz. Horizontale Skalierung ist für elastische, hochverfügbare Anwendungen meist robuster.',why:'Die Wahl zwischen vertikal und horizontal beeinflusst Kosten, Verfügbarkeit und die notwendige Anwendungsarchitektur.',examples:['Eine speicherintensive Datenbank-VM wird von einer allgemeinen auf eine memory-optimierte VM-Größe umgestellt.'],merksatz:'Scale up macht eine Instanz stärker, aber nicht automatisch verfügbarer.',sources:['ms-vm-overview','ms-vm-sizes','ms-app-service-plan'],tags:['vertical-scaling','scale-up','capacity']},
  'azure-0020': {title:'Horizontale Skalierung (Scale out / in)',simple:'Horizontale Skalierung erhöht oder verringert die Anzahl gleichartiger Instanzen. Sie wird für elastische Lastverteilung und höhere Verfügbarkeit eingesetzt.',technical:'Ein Load Balancer oder Plattformrouter verteilt Anfragen auf mehrere Instanzen. Zustände müssen extern gespeichert, repliziert oder bewusst an Sitzungen gebunden werden. Scale-out und Scale-in können manuell, zeitgesteuert oder anhand von Metriken erfolgen.',architecture:'Horizontale Skalierung passt zu zustandsarmen Web- und Microservice-Workloads und vermeidet die Kapazitätsgrenze einer einzelnen Instanz. Dafür müssen Deployment, Datenhaltung, Session State, Health Checks und Scale-in-Verhalten verteilt entworfen werden. Sie ist eine Architekturentscheidung, kein bloßer Schieberegler.',why:'Sie verbindet Elastizität mit Redundanz, verlangt aber eine verteilungsfähige Anwendung.',examples:['Ein VM Scale Set erhöht bei anhaltend hoher CPU-Last die Zahl der Webserver von drei auf sechs.'],merksatz:'Scale out verteilt Last und Risiko auf mehrere Instanzen.',sources:['ms-vmss-overview','ms-vmss-autoscale','ms-app-service-plan'],tags:['horizontal-scaling','scale-out','elasticity']},
  'azure-0025': {title:'Azure Autoscale',simple:'Azure Autoscale passt die Anzahl oder Kapazität unterstützter Ressourcen automatisch an. Regeln reagieren beispielsweise auf CPU-Last, Warteschlangen oder einen Zeitplan.',technical:'Autoscale wertet Metriken und Zeitfenster aus und führt Scale-out- oder Scale-in-Aktionen innerhalb definierter Mindest-, Standard- und Höchstwerte aus. Cooldown-Phasen verhindern zu schnelle Gegenbewegungen. Bei VM Scale Sets ändert es typischerweise die Instanzzahl.',architecture:'Autoscale senkt Leerlaufkosten und erhöht Reaktionsfähigkeit, ersetzt aber keine Kapazitätsplanung. Schwellen, Aufwärmzeit, Abhängigkeiten und sichere Scale-in-Semantik müssen getestet werden. Vorhersehbare Spitzen können zeitgesteuert vorgewärmt werden; unvorhersehbare Last benötigt metrische Regeln.',why:'Fehlkonfiguriertes Autoscale kann zugleich Kosten erhöhen und Verfügbarkeit verschlechtern.',examples:['Ein Scale Set skaliert werktags vor Geschäftsbeginn auf vier Instanzen und danach anhand der CPU-Auslastung weiter.'],merksatz:'Autoscale automatisiert Kapazität innerhalb bewusst gesetzter Grenzen.',sources:['ms-vmss-autoscale'],tags:['autoscale','elasticity','azure-monitor']},
  'azure-0034': {title:'Compute-SKU und VM-Größe',simple:'Eine Compute-SKU legt Leistung, Funktionen und Preis einer Compute-Ressource fest. Bei VMs bestimmt die Größe unter anderem CPU, Arbeitsspeicher, Datenträger- und Netzwerkgrenzen; bei App Service übernimmt der Plan-Tier eine ähnliche Kapazitätsrolle.',technical:'VM-Serien sind für allgemeine, compute-, memory-, storage- oder GPU-intensive Anforderungen optimiert. Die konkrete Größe begrenzt vCPUs, RAM, Datenplatten, IOPS, Durchsatz und Netzwerkbandbreite. App-Service-Tiers steuern Instanzgröße, Skalierungsgrenzen und Plattformfunktionen.',architecture:'Die SKU muss anhand gemessener Last, Leistungsgrenzen, regionaler Verfügbarkeit, Quota und Kosten gewählt werden. Überdimensionierung erzeugt Leerlaufkosten, Unterdimensionierung Drosselung und instabile Latenz. Eine Größenänderung ist vertikale Skalierung und ersetzt weder Redundanz noch Autoscale.',why:'SKU-Grenzen wirken oft gleichzeitig auf Compute, Storage und Netzwerk und bestimmen damit die reale Systemleistung.',examples:['Eine API benötigt wenig CPU, aber hohen Netzwerkdurchsatz; die VM-Größe wird deshalb nach Netzwerkgrenze statt nur nach vCPU gewählt.'],merksatz:'Die SKU ist ein Bündel aus Leistung, Grenzen, Funktionen und Preis.',sources:['ms-vm-sizes','ms-app-service-plan'],tags:['vm-size','sku','capacity-planning']},
  'azure-0116': {title:'Azure Backup für VMs',simple:'Azure Backup erstellt unabhängige Wiederherstellungspunkte für virtuelle Maschinen. Damit lassen sich nach Löschung, Beschädigung oder Fehlkonfiguration ganze VMs oder Daten wiederherstellen.',technical:'Eine Backup Policy steuert Zeitplan und Aufbewahrung; Recovery Points werden in einem Vault verwaltet. Für anwendungs- oder dateisystemkonsistente Sicherungen koordiniert eine VM-Erweiterung Snapshots, danach werden geänderte Datenblöcke in den Vault übertragen. Backup-Konsistenz und Restore-Fähigkeit müssen zur Workload passen.',architecture:'Backup schützt gegen logische Fehler und Datenverlust, während Availability Zones laufende Verfügbarkeit und Site Recovery Disaster Recovery adressieren. Architekten definieren RPO, Aufbewahrung, Unveränderbarkeit, Zugriffsschutz und regelmäßige Restore-Tests. Backup ist ein eigener Kosten- und Betriebsbaustein, nicht im VM-Preis enthalten.',why:'Hochverfügbarkeit repliziert auch Fehler; ein unabhängiger Wiederherstellungspunkt bleibt deshalb notwendig.',examples:['Eine tägliche VM-Sicherung mit Langzeitaufbewahrung ermöglicht die Wiederherstellung vor einer fehlerhaften Anwendungsmigration.'],merksatz:'Backup macht Daten wiederherstellbar; Hochverfügbarkeit hält Dienste erreichbar.',sources:['ms-vm-backup'],tags:['azure-backup','vm','recovery']},
  'azure-0118': {title:'Azure Site Recovery für VM-Disaster-Recovery',simple:'Azure Site Recovery repliziert virtuelle Maschinen an einen zweiten Standort und orchestriert Failover und Failback. Es wird eingesetzt, um Anwendungen nach einem Standort- oder Regionsausfall wieder in Betrieb zu nehmen.',technical:'Site Recovery repliziert Änderungen kontinuierlich von der Primär- zur Zielumgebung und verwaltet Recovery Points. Recovery Plans ordnen abhängige Maschinen und Automatisierungsschritte. Bei einem Ausfall werden Ziel-VMs aus den replizierten Daten gestartet und Netzwerkpfade angepasst.',architecture:'Site Recovery adressiert RTO und RPO für Disaster Recovery, ersetzt aber weder lokale Hochverfügbarkeit noch Backup. Zielregion, Kapazität, IP- und DNS-Umschaltung, Datenkonsistenz, Runbooks und regelmäßige Test-Failovers gehören in das Design. Der Kunde verantwortet die anwendungsspezifische Wiederanlaufreihenfolge.',why:'Replikation allein garantiert nicht, dass eine mehrstufige Anwendung geordnet und testbar wiederanläuft.',examples:['Eine dreistufige VM-Anwendung repliziert in eine zweite Region und startet im Recovery Plan zuerst Datenbank, dann API und Webfrontend.'],merksatz:'Site Recovery hält einen Wiederanlaufpfad bereit; Backup hält Wiederherstellungspunkte bereit.',sources:['ms-site-recovery'],tags:['site-recovery','disaster-recovery','bcdr']},
  'azure-0198': {title:'Infrastructure as a Service (IaaS)',simple:'IaaS stellt virtuelle Rechen-, Netzwerk- und Speicherressourcen bereit, während der Kunde Betriebssystem und Anwendungen betreibt. Azure Virtual Machines sind das typische Azure-IaaS-Angebot.',technical:'Azure verwaltet physische Rechenzentren, Hosts und Virtualisierung. Der Kunde konfiguriert VM-Image, Gastbetriebssystem, Patches, Laufzeit, Daten, Identitäten und Netzwerkschutz. Ergänzende Dienste wie Managed Disks, VNet, Load Balancer, Backup und Monitor bilden die Betriebsplattform.',architecture:'IaaS ist passend bei Betriebssystemkontrolle, nicht unterstützten Laufzeiten, Appliances oder Lift-and-Shift. Gegenüber App Service bietet es mehr Freiheit, aber mehr Patch-, Sicherheits-, Skalierungs- und Verfügbarkeitsverantwortung. Ein Architekt sollte IaaS nicht wählen, wenn PaaS die Anforderungen mit geringerem Betriebsaufwand erfüllt.',why:'Das Servicemodell bestimmt die Grenze zwischen Azure- und Kundenverantwortung.',examples:['Eine ältere Fachanwendung mit Windows-Dienst und speziellen Registry-Abhängigkeiten wird zunächst auf Azure VMs migriert.'],merksatz:'IaaS liefert Infrastruktur; du betreibst das System darauf.',sources:['ms-vm-overview'],tags:['iaas','shared-responsibility','virtual-machines']},
  'azure-0322': {title:'Azure Virtual Machines',simple:'Azure Virtual Machines stellen Windows- oder Linux-Server als flexibel konfigurierbare Cloud-Ressourcen bereit. Sie werden genutzt, wenn eine Anwendung Kontrolle über Betriebssystem, Laufzeit oder installierte Software benötigt.',technical:'Eine VM kombiniert eine gewählte VM-Größe mit einem Betriebssystem-Image, Netzwerkschnittstelle, VNet-Anbindung und OS- sowie Daten-Datenträgern. Azure virtualisiert und betreibt die physische Infrastruktur; der Kunde konfiguriert, patcht und überwacht Gastbetriebssystem und Workload. Verfügbarkeit und Skalierung entstehen erst durch mehrere Instanzen und ergänzende Dienste.',architecture:'VMs passen zu Lift-and-Shift, Spezialsoftware, Appliances und strikten OS-Anforderungen. Gegenüber App Service oder Containerplattformen bieten sie maximale Kontrolle, verursachen aber den höchsten Betriebsaufwand für Patching, Backup, Hardening, Skalierung und Hochverfügbarkeit. Die Architektur sollte VNet, NSG, Managed Identity, RBAC, Managed Disks, Azure Monitor und eine Resilienzstrategie gemeinsam entwerfen.',why:'VMs sind selten ein isolierter Dienst; ihr Wert und Risiko entstehen aus den Architekturverbindungen zu Netzwerk, Identität, Sicherheit und Betrieb.',examples:['Eine Fachanwendung läuft auf zwei zonenverteilten VMs hinter einem Load Balancer, nutzt Managed Identity und sendet Gastlogs an Log Analytics.'],merksatz:'VM bedeutet volle Gastkontrolle und volle Gastverantwortung.',sources:['ms-vm-overview','ms-managed-disks','ms-monitor-vm'],tags:['azure-vm','iaas','architecture-bridge']},
  'azure-0324': {title:'Lift-and-Shift mit Azure VMs',simple:'Lift-and-Shift verschiebt eine bestehende Serveranwendung mit möglichst wenigen Änderungen in Azure. VMs eignen sich dafür, weil Betriebssystem und Softwareumgebung weitgehend erhalten bleiben können.',technical:'Die Anwendung wird als VM-Workload neu bereitgestellt oder migriert und mit Azure-Netzwerk, Identität, Storage und Betrieb verbunden. Abhängigkeiten, IP-Adressen, DNS, Latenz, Lizenzen, Datenträger und Startreihenfolgen müssen erfasst werden. Das Betriebsmodell bleibt zunächst IaaS.',architecture:'Lift-and-Shift beschleunigt eine Migration und reduziert kurzfristige Codeänderungen, übernimmt aber auch technische Schulden und Betriebsaufwand. Es sollte als bewusste Übergangs- oder Zielentscheidung mit Kosten-, Resilienz- und Modernisierungsplan behandelt werden. Replatforming zu App Service oder Container Apps kann später Verantwortung reduzieren, sofern die Anwendung kompatibel ist.',why:'Eine erfolgreiche Verschiebung ist noch keine Cloud-Optimierung.',examples:['Eine ältere .NET-Anwendung wird zunächst auf Windows-VMs migriert und später schrittweise auf App Service replatformed.'],merksatz:'Lift-and-Shift ändert den Standort, nicht automatisch das Betriebsmodell.',sources:['ms-vm-overview','ms-app-service'],tags:['lift-and-shift','migration','iaas']},
  'azure-0329': {title:'Kundenverantwortung bei Azure VMs',simple:'Bei Azure VMs verwaltet Azure die physische Infrastruktur und Virtualisierung. Der Kunde bleibt für Gastbetriebssystem, Patches, Anwendungen, Daten und die sichere Konfiguration verantwortlich.',technical:'Zur Kundenverantwortung gehören Image- und Patch-Lifecycle, Endpoint-Schutz, Identitäten, lokale Konten, NSG- und Firewallregeln, Datenträger, Backup, Telemetrie und Wiederherstellung. Azure liefert Plattformfunktionen, aktiviert und betreibt sie aber nicht automatisch in jeder VM. Automatisierung kann Aufgaben standardisieren, entfernt die Verantwortlichkeit jedoch nicht.',architecture:'Das VM-Betriebsmodell benötigt klare Owner, Baselines, Updatefenster, Backup- und Restore-Tests, Monitoring, Incident Response und Lifecycle-Prozesse. Fehlt diese Plattformdisziplin, wird IaaS schnell riskanter und teurer als PaaS. App Service übernimmt OS- und Plattformpatching, verlangt aber weiterhin sicheren Anwendungscode und Datenbetrieb.',why:'Die häufigste Fehlannahme bei IaaS ist, dass „in Azure“ zugleich „von Azure betrieben“ bedeutet.',examples:['Ein Plattformteam erzwingt VM-Baselines, Update Manager, Azure Monitor und Defender for Servers über zentrale Richtlinien.'],merksatz:'Azure betreibt den Host; du betreibst den Gast.',sources:['ms-vm-overview','ms-vm-maintenance','ms-defender-servers'],tags:['shared-responsibility','vm-operations','security']},
  'azure-0351': {title:'Azure App Service',simple:'Azure App Service hostet Webanwendungen, APIs und mobile Backends als verwaltete Plattform. Entwickler stellen Code oder Container bereit, ohne die zugrunde liegenden Server selbst zu verwalten.',technical:'Apps laufen auf Windows- oder Linux-Workern eines App Service Plans und nutzen integrierte Deployment-, Skalierungs-, TLS-, Identitäts- und Monitoringfunktionen. Azure verwaltet Host, Gastbetriebssystem und unterstützte Plattformlaufzeiten. Der Kunde verwaltet Anwendung, Konfiguration, Daten, Abhängigkeiten und Zugriffsmodell.',architecture:'App Service ist oft die erste PaaS-Wahl für HTTP-basierte Anwendungen mit unterstützten Laufzeiten. Gegenüber VMs reduziert es Patch- und Infrastrukturaufwand, bietet aber weniger OS-Kontrolle; gegenüber AKS ist es einfacher, aber weniger flexibel für komplexe Containerorchestrierung. Plan-Tier, Zonenunterstützung, VNet-Integration, Managed Identity, Deployment Slots und Observability bestimmen das Produktionsdesign.',why:'App Service verschiebt Arbeit von Serverbetrieb zu Anwendung und Plattformkonfiguration.',examples:['Eine REST-API läuft in App Service, greift per Managed Identity auf Key Vault zu und wird über Application Gateway veröffentlicht.'],merksatz:'App Service betreibt die Webplattform; du betreibst Anwendung und Daten.',sources:['ms-app-service','ms-app-service-plan'],tags:['app-service','paas','web-apps','architecture-bridge']},
  'azure-0354': {title:'Azure-Verantwortung in App Service',simple:'Bei App Service übernimmt Azure den Betrieb der physischen Infrastruktur, des Betriebssystems und des verwalteten Plattform-Stacks. Dadurch muss das Anwendungsteam keine Webserver-VMs patchen oder austauschen.',technical:'Azure patcht Hosts und Gast-VMs der App-Service-Plattform und pflegt unterstützte Laufzeiten nach dem jeweiligen Lifecycle. Die Plattform stellt Worker, Routing, Health- und Skalierungsmechanismen bereit. Eigene Containerimages, Anwendungspakete, Daten und Konfiguration bleiben in Kundenverantwortung.',architecture:'Die übernommene Plattformverantwortung ist der zentrale Grund für PaaS statt VM. Sie reduziert und standardisiert Infrastrukturarbeit, schränkt aber privilegierten OS-Zugriff und freie Systemanpassung ein. Architekten müssen prüfen, ob Laufzeit, Netzwerk, Compliance und Legacy-Abhängigkeiten innerhalb dieser Plattformgrenzen liegen.',why:'Die Servicewahl ist vor allem eine Wahl der Betriebs- und Verantwortungsgrenze.',examples:['Azure rollt OS-Patches auf den App-Service-Workern aus, während das Produktteam seine Laufzeitversion und Anwendungstests verantwortet.'],merksatz:'PaaS übernimmt Plattformbetrieb, nicht Produktverantwortung.',sources:['ms-app-service','ms-app-service-patching'],tags:['app-service','shared-responsibility','paas']},
  'azure-0357': {title:'App-Service-Patching und Updates',simple:'Azure aktualisiert das Betriebssystem und unterstützte Plattformlaufzeiten von App Service. Das Anwendungsteam muss dennoch seine Anwendung, Abhängigkeiten und gewählte Laufzeitversion testen und aktuell halten.',technical:'Host- und Gastbetriebssysteme der Plattform werden nach sicheren Rolloutverfahren gepatcht. Manche Runtime-Patches ersetzen vorhandene Versionen, während größere Versionen parallel installiert werden und eine bewusste Migration verlangen. Eigene Container oder mitgelieferte Laufzeiten aktualisiert der Kunde.',architecture:'Automatisches Plattformpatching reduziert Routinearbeit und Expositionszeit, kann aber Kompatibilitätsrisiken nicht vollständig beseitigen. Deployment Slots, automatisierte Tests und ein Runtime-Lifecycle-Prozess ermöglichen kontrollierte Updates. Wer vollständige Kontrolle über Patchzeitpunkt und OS-Komponenten benötigt, muss VM- oder spezialisierte Hostingoptionen bewerten.',why:'Managed bedeutet nicht, dass Anwendungskompatibilität und Runtime-Lifecycle ohne Kundenprozess funktionieren.',examples:['Eine neue Java-Runtime wird zunächst im Staging Slot getestet und erst danach durch Slot Swap produktiv gesetzt.'],merksatz:'Azure patcht die Plattform; du validierst deine Anwendung.',sources:['ms-app-service-patching','ms-app-service-slots'],tags:['app-service','patching','runtime']},
  'azure-0358': {title:'App-Service-Sicherheit und Plattformmonitoring',simple:'App Service bietet integrierte Sicherheits- und Monitoringanschlüsse für Webanwendungen. Diese Funktionen liefern eine Basis, müssen aber passend konfiguriert und betrieben werden.',technical:'Die Plattform stellt TLS, Authentifizierungsintegration, Managed Identity, Diagnoseprotokolle, Metriken und Anbindung an Azure Monitor bereit. Netzwerkzugriff kann über Access Restrictions, VNet-Integration oder Private Endpoints gestaltet werden. Anwendungstelemetrie und Schwachstellen im eigenen Code bleiben beim Kunden.',architecture:'Architekten kombinieren App Service mit Managed Identity, Key Vault, RBAC, Netzwerkgrenzen und zentralem Monitoring. Die integrierten Funktionen reduzieren Integrationsaufwand, ersetzen aber kein Threat Model, keine sichere Softwarelieferkette und keine Alarmreaktion. Sicherheits- und Telemetriedaten müssen in ein verantwortetes Betriebsmodell fließen.',why:'PaaS beseitigt Serverarbeit, aber nicht Identitäts-, Anwendungs- und Überwachungsrisiken.',examples:['Eine App Service API nutzt Managed Identity für Secrets, sendet Plattformlogs an Log Analytics und löst bei Fehlerraten einen Alert aus.'],merksatz:'Integriert heißt verfügbar, nicht automatisch fertig betrieben.',sources:['ms-app-service','ms-log-analytics','ms-managed-identities'],tags:['app-service','security','monitoring']},
  'azure-0362': {title:'Kundenverantwortung in App Service',simple:'In App Service entwickelt und betreibt der Kunde weiterhin die Anwendung und ihre Daten. Dazu gehören Codequalität, Konfiguration, Zugriffe, Abhängigkeiten und fachliche Verfügbarkeit.',technical:'Der Kunde liefert Anwendungscode oder Containerimage, wählt Runtime und Plan, verwaltet App Settings, Verbindungsdaten, Identitäten, Deployment und Datenhaltung. Er konfiguriert Skalierung, Netzwerkzugriff, Telemetrie, Backups und Alarmierung passend zum Dienst. Bei eigenen Containern liegt auch das Image-Patching beim Kunden.',architecture:'PaaS verkleinert die Betriebsfläche, verschiebt Verantwortung aber in Softwarearchitektur und Plattformkonfiguration. Stateless Design, externe Zustände, sichere Secrets, automatisierte Deployments und Observability bleiben notwendig. Ein Service-Level-Ziel muss die Anwendung samt Abhängigkeiten betrachten, nicht nur das Plattform-SLA.',why:'Unklare Restverantwortung führt trotz Managed Service zu unsicheren oder nicht betreibbaren Anwendungen.',examples:['Das Team aktualisiert NuGet-Abhängigkeiten, schützt App Settings, definiert Autoscale und reagiert auf Application-Insights-Alarme.'],merksatz:'Azure betreibt App Service; du verantwortest, was du darauf ausführst.',sources:['ms-app-service','ms-app-service-patching'],tags:['app-service','shared-responsibility','application-operations']},
  'azure-0363': {title:'App Service Plan',simple:'Ein App Service Plan stellt die Compute-Ressourcen bereit, auf denen eine oder mehrere App-Service-Apps laufen. Er bestimmt Region, Betriebssystem, Instanzgröße, Instanzanzahl, Preis und verfügbare Funktionen.',technical:'Apps in einem Plan teilen sich die konfigurierten Worker-Instanzen und deren Kapazität. Der Pricing Tier steuert unter anderem Skalierungsgrenzen, Deployment Slots, Backups und Netzwerkfunktionen. Scale up ändert Tier oder Instanzgröße; Scale out ändert die Zahl der Worker.',architecture:'Pläne sind eine Kosten-, Kapazitäts- und Isolationsgrenze. Mehrere Apps in einem Plan sparen Geld, teilen aber Ressourcen und Ausfallradius; getrennte Pläne isolieren Leistung und Skalierung. Region, Zonenfähigkeit, OS, Tier, Mindestinstanzen und Noisy-Neighbor-Risiko gehören in die Entscheidung.',why:'Die App ist das Deploymentobjekt, der Plan ist ihr tatsächlicher Compute- und Kostenunterbau.',examples:['Drei interne APIs teilen einen Premium-Plan; eine geschäftskritische API erhält wegen eigener Skalierung einen separaten Plan.'],merksatz:'App Service Plan bestimmt, worauf und mit wie viel Kapazität Apps laufen.',sources:['ms-app-service-plan'],tags:['app-service-plan','sku','capacity']},
  'azure-0369': {title:'App Service Autoscale',simple:'App Service kann die Zahl seiner Worker-Instanzen automatisch an Last oder Zeitplan anpassen. Dadurch reagiert die Anwendung auf Spitzen und reduziert ungenutzte Kapazität.',technical:'Autoscale-Regeln verwenden Plattformmetriken und verändern innerhalb gesetzter Grenzen die Instanzanzahl des App Service Plans. Alle Apps im Plan laufen auf den skalierten Workern und teilen deren Ressourcen. Aufwärmzeit, Mindestinstanzen und Cooldown beeinflussen das Verhalten.',architecture:'Autoscale funktioniert am besten mit zustandsarmen Anwendungen und externem Session State. Ein gemeinsam genutzter Plan koppelt die Skalierungs- und Kostenentwicklung aller enthaltenen Apps. Architekten testen Regeln mit realistischer Last und kombinieren Skalierung mit Health Checks, Alerts und Kapazitätsgrenzen.',why:'Automatische Skalierung ist nur sicher, wenn Anwendung und Plan als gemeinsame Kapazitätseinheit verstanden werden.',examples:['Ein Premium-Plan skaliert eine stateless API bei hoher Request-Last von zwei auf fünf Worker.'],merksatz:'App Service skaliert den Plan, nicht isoliert nur einen Prozess.',sources:['ms-app-service-plan'],tags:['app-service','autoscale','scale-out']},
  'azure-0370': {title:'App Service Monitoring und Logging',simple:'App Service stellt Plattformmetriken und Diagnoseprotokolle für Betrieb und Fehlersuche bereit. Die Daten können in Azure Monitor und Log Analytics zentral ausgewertet werden.',technical:'Metriken beschreiben beispielsweise Requests, Antwortzeiten, CPU und Speicher des Plans. Diagnoseeinstellungen leiten unterstützte Plattformlogs an Ziele wie einen Log Analytics Workspace weiter; Anwendungstelemetrie kann über Application Insights ergänzt werden. Alerts reagieren auf Metriken oder Logabfragen.',architecture:'Monitoring muss Plattform, Anwendung und Abhängigkeiten gemeinsam abdecken. Aufbewahrung, Kosten, personenbezogene Daten, Korrelation und Alarm-Owner sind Teil des Designs. Nur gesammelte Logs ohne Abfragen, Dashboards und Reaktionsprozess erzeugen keinen Betriebswert.',why:'PaaS versteckt Serverdetails; dadurch wird gute Telemetrie zur wichtigsten Sicht auf den realen Anwendungszustand.',examples:['HTTP-Fehler, Antwortzeiten und Anwendungs-Traces werden korreliert und lösen bei anhaltender Verschlechterung einen Alert aus.'],merksatz:'Was PaaS abstrahiert, muss Telemetrie verständlich machen.',sources:['ms-app-service','ms-log-analytics'],tags:['app-service','azure-monitor','logging']},
  'azure-0371': {title:'Deployment Slots, TLS und Custom Domains',simple:'App Service unterstützt eigene Domains, TLS-Zertifikate und getrennte Deployment Slots. Slots ermöglichen, eine neue Version vor dem Wechsel auf Produktion in einer laufenden Umgebung zu prüfen.',technical:'Ein Slot ist eine eigenständige App mit eigener URL, die auf Ressourcen des App Service Plans läuft. Inhalte und viele Konfigurationen lassen sich zwischen Staging und Produktion tauschen; slot-spezifische Settings bleiben auf Wunsch gebunden. Domains und Zertifikate ordnen öffentliche Namen und TLS-Vertrauen der App zu.',architecture:'Slots reduzieren Deploymentrisiko und ermöglichen schnelles Rollback, verbrauchen aber dieselbe Plan-Kapazität und benötigen saubere Konfigurationstrennung. Datenbankschemata und externe Seiteneffekte sind nicht automatisch reversibel. TLS- und Domain-Lifecycle müssen unabhängig vom Code automatisiert werden.',why:'Sichere Releases benötigen eine kontrollierte Umschaltung, nicht nur einen erfolgreichen Build.',examples:['Eine API-Version wird im Staging Slot mit Produktionsnähe getestet, aufgewärmt und anschließend ohne Requestverlust getauscht.'],merksatz:'Slot Swap schaltet Anwendung um, nicht automatisch alle externen Zustände.',sources:['ms-app-service-slots','ms-app-service-plan'],tags:['deployment-slots','tls','custom-domain']},
  'azure-0376': {title:'Web Apps und APIs auf App Service',simple:'App Service ist für Websites, Web APIs, REST-Dienste und mobile Backends optimiert. Diese Anwendungen können als Code oder Container bereitgestellt werden.',technical:'Die Plattform unterstützt verbreitete Weblaufzeiten auf Windows und Linux, eingehendes HTTP(S)-Routing, Deploymentintegration und horizontale Worker-Skalierung. Anwendungen laufen innerhalb eines App Service Plans und verwenden externe Daten- und Identitätsdienste über Netzwerkverbindungen. Persistenter lokaler Zustand sollte nicht als verteilte Anwendungsdatenbank behandelt werden.',architecture:'Für standardisierte HTTP-Anwendungen ist App Service meist einfacher als VM oder AKS. VMs sind sinnvoll bei voller OS-Kontrolle; AKS bei Kubernetes-API, komplexer Orchestrierung und Plattformteam; Container Apps wäre für serverlose Microservices relevant, ist aber in V1.3 nicht als Knoten vorhanden. Laufzeitunterstützung, Netzwerk, Isolation und Betriebsmodell entscheiden.',why:'Die richtige Compute-Plattform hängt stärker vom Betriebs- und Kontrollbedarf als von der Programmiersprache ab.',examples:['Eine öffentliche REST-API läuft in App Service und nutzt Azure SQL sowie Managed Identity statt lokaler Daten oder Secrets.'],merksatz:'Web-Workload plus Standardplattform spricht zuerst für PaaS.',sources:['ms-app-service','ms-container-options','ms-vm-overview'],tags:['web-app','api','paas']},
  'azure-0387': {title:'Azure Virtual Machine Scale Sets',simple:'VM Scale Sets erstellen und verwalten Gruppen virtueller Maschinen als gemeinsame Skalierungs- und Verfügbarkeitseinheit. Die Instanzzahl kann automatisch an Bedarf oder Zeitpläne angepasst werden.',technical:'Ein Scale Set beschreibt Instanzkonfiguration, Orchestrierungsmodus, VM-Größe, Image, Netzwerk und Datenträger. Instanzen können über Fault Domains oder Availability Zones verteilt, mit Load Balancer oder Application Gateway verbunden und durch Autoscale gesteuert werden. Flexible und Uniform Orchestration bieten unterschiedliche Kontrollmodelle.',architecture:'VMSS ist die Wahl, wenn eine Anwendung VM-Kontrolle benötigt, aber horizontal skalieren und redundant laufen soll. Gegenüber einzelnen VMs standardisiert es Instanzen und Lifecycle; gegenüber App Service oder AKS bleibt der Gastbetrieb aufwendiger. Orchestrierungsmodus, zustandsarmer Workload, Image-Pipeline, Health-Signal, Scale-in und Zonenstrategie sind entscheidend.',why:'VMSS verbindet IaaS-Kontrolle mit Flottenmanagement, ersetzt aber kein gutes Golden-Image- und Betriebsmodell.',examples:['Ein stateless Webtier läuft als zonenverteiltes VM Scale Set hinter einem Load Balancer und skaliert nach CPU.'],merksatz:'VMSS verwaltet eine VM-Flotte, eine einzelne VM nur eine Instanz.',sources:['ms-vmss-overview','ms-vmss-autoscale'],tags:['vmss','horizontal-scaling','high-availability','architecture-bridge']},
  'azure-0395': {title:'VMSS-Instanzmodell und Orchestrierung',simple:'Ein VM Scale Set verwendet ein gemeinsames Modell, um mehrere VM-Instanzen konsistent bereitzustellen und zu verwalten. Der Orchestrierungsmodus bestimmt, wie einheitlich oder flexibel die Instanzen behandelt werden.',technical:'Das Modell enthält Image, VM-Größe, Storage-, Netzwerk- und Extension-Konfiguration. Uniform Orchestration optimiert identische Instanzen als gemeinsame Skalierungseinheit; Flexible Orchestration integriert stärker mit normalen VM-Funktionen und unterstützt gemischtere Szenarien. Der Modus wird bei Erstellung festgelegt.',architecture:'Ein unveränderliches Image und automatisierte Konfiguration reduzieren Drift und machen Scale-out reproduzierbar. Flexible Orchestration eignet sich für mehr VM-Flexibilität und hohe Verfügbarkeit, Uniform für stark homogene Flotten; konkrete Featuregrenzen müssen geprüft werden. Manuelle Änderungen an Einzelinstanzen untergraben das Flottenmodell.',why:'Skalierung ist nur zuverlässig, wenn jede neue Instanz reproduzierbar und betrieblich gleichwertig entsteht.',examples:['Ein Image-Release erzeugt neue VMSS-Instanzen mit identischer Anwendung, Agenten- und Sicherheitskonfiguration.'],merksatz:'Das Instanzmodell ist der Bauplan der VM-Flotte.',sources:['ms-vmss-overview'],tags:['vmss','orchestration','immutable-infrastructure']},
  'azure-0399': {title:'Automatische VMSS-Instanzreparatur',simple:'Automatische Instanzreparatur ersetzt fehlerhafte VMSS-Instanzen anhand eines Health-Signals. Dadurch kann die Flotte ohne manuelles Eingreifen wieder auf die gewünschte gesunde Kapazität kommen.',technical:'VMSS bewertet den Zustand über unterstützte Health Extensions oder Load-Balancer-Application-Health. Nach einer Schonfrist wird eine dauerhaft ungesunde Instanz repariert, typischerweise durch Neuabbildung oder Ersatz entsprechend dem Scale-Set-Modell. Lokaler Zustand auf der Instanz kann dabei verloren gehen.',architecture:'Auto-Repair passt zu stateless und reproduzierbaren Workloads. Das Health-Signal muss die echte Anwendungsfähigkeit messen, ohne bei kurzzeitigen Störungen Reparaturstürme auszulösen. Daten gehören außerhalb der austauschbaren Instanz; Reparatur, Autoscale und Deployments benötigen abgestimmte Zeitfenster.',why:'Eine Flotte wird resilient, wenn fehlerhafte Instanzen sicher ersetzbar statt individuell repariert werden.',examples:['Eine nicht mehr antwortende Webinstanz wird nach Ablauf der Grace Period automatisch aus dem Modell neu erstellt.'],merksatz:'Auto-Repair ersetzt Vieh, nicht pflegt Haustiere.',sources:['ms-vmss-repair','ms-vmss-overview'],tags:['vmss','auto-repair','health']},
  'azure-0400': {title:'VMSS Autoscale',simple:'VMSS Autoscale erhöht oder reduziert automatisch die Zahl der VM-Instanzen. Es reagiert auf Metriken, Zeitpläne oder vorausschauend erkannte Nutzungsmuster.',technical:'Regeln überwachen Metrikschwellen über Zeitfenster und ändern die Scale-Set-Kapazität innerhalb von Minimum und Maximum. Scale-out stellt Instanzen aus dem VMSS-Modell bereit; Scale-in entfernt Instanzen nach einer gewählten Policy. Cooldown und Startzeit beeinflussen die Reaktion.',architecture:'Metrik, Schwelle und Aufwärmzeit müssen zur Workload passen; CPU allein bildet Warteschlangen oder Antwortzeiten nicht immer ab. Scale-in darf keine Zustände oder laufenden Jobs verlieren. Lasttests, Kapazitätsreserve, Quota und Alerting verhindern, dass Autoscale erst im Ausfall seine Grenzen zeigt.',why:'Autoscale verbindet Nachfrage mit Flottenkapazität, ist aber nur so gut wie Signal und Anwendungseigenschaften.',examples:['Eine Worker-Flotte skaliert anhand der Queue-Länge und beendet Instanzen erst nach Abschluss laufender Jobs.'],merksatz:'VMSS Autoscale zählt Instanzen; die Anwendung muss sie sicher hinzufügen und entfernen können.',sources:['ms-vmss-autoscale'],tags:['vmss','autoscale','metrics']},
  'azure-0412': {title:'Azure-Containerdienste',simple:'Azure bietet mehrere Dienste zum Ausführen containerisierter Anwendungen mit unterschiedlichem Abstraktionsgrad. ACI startet einzelne Containergruppen, App Service hostet Webcontainer, Container Apps abstrahiert Microservice-Orchestrierung und AKS stellt Kubernetes bereit.',technical:'Container teilen den Host-Kernel, bündeln aber Anwendung und Abhängigkeiten in Images. Azure-Dienste unterscheiden sich bei Orchestrierung, Skalierung, Netzwerk, Kubernetes-API und Kundenverantwortung. V1.3 besitzt eigene Knoten für ACI und AKS, aber keinen kanonischen Container-Apps-Knoten.',architecture:'Die Plattformwahl folgt dem benötigten Kontrollniveau: ACI für einfache kurzlebige Container, App Service für Webanwendungen, Container Apps für verwaltete Microservices und AKS für Kubernetes-Kontrolle. Mit wachsender Kontrolle steigen typischerweise Plattformkompetenz und Betriebsaufwand. Ein fehlender Container-Apps-Knoten wird in V1.4 bewusst nicht erfunden.',why:'„Container“ beschreibt das Paketformat, nicht das notwendige Betriebsmodell.',examples:['Ein einmaliger Batchjob läuft in ACI, während eine komplexe Kubernetes-Plattform mit eigenen Controllern AKS verwendet.'],merksatz:'Wähle den Containerdienst nach Orchestrierungsbedarf, nicht nur nach Imageformat.',sources:['ms-container-options','ms-aci-overview','ms-aks-overview'],tags:['containers','compute-options','architecture-decision']},
  'azure-0413': {title:'Container-Modell',simple:'Ein Container verpackt eine Anwendung mit ihren Laufzeitabhängigkeiten in ein portables Image. Er startet meist schneller und benötigt weniger Overhead als eine vollständige virtuelle Maschine.',technical:'Container isolieren Prozesse über Betriebssystemmechanismen und teilen den Kernel des Hosts. Images sind unveränderliche Schichten; laufende Container ergänzen einen beschreibbaren, kurzlebigen Zustand. Persistente Daten, Secrets, Netzwerk und Scheduling werden extern bereitgestellt.',architecture:'Container verbessern Reproduzierbarkeit und Deploymentdichte, lösen aber Betrieb, Sicherheit und Orchestrierung nicht automatisch. Anwendungen sollten zustandsarm sein, Images regelmäßig neu gebaut und gescannt werden und Daten außerhalb der Instanz liegen. Für einzelne Container reicht ACI; viele Services und komplexe Steuerung benötigen eine Plattform.',why:'Portabilität entsteht aus einem konsistenten Paket, nicht aus der Abwesenheit von Plattformabhängigkeiten.',examples:['Eine API wird als versioniertes Image gebaut und identisch in Test und Produktion ausgeführt.'],merksatz:'Container kapseln Anwendung und Abhängigkeiten, nicht den gesamten Server.',sources:['ms-aci-overview','ms-container-options'],tags:['container','image','portability']},
  'azure-0415': {title:'Azure Container Instances (ACI)',simple:'Azure Container Instances führt Container ohne selbst verwaltete VMs oder Kubernetes-Cluster aus. Der Dienst eignet sich für einfache, isolierte oder kurzlebige Aufgaben, die schnell starten sollen.',technical:'ACI plant eine Containergruppe auf Azure-Infrastruktur; Container der Gruppe teilen Lifecycle, Ressourcen, Netzwerk und Volumes. CPU und Arbeitsspeicher werden bei Bereitstellung angegeben, Abrechnung erfolgt nach Ressourcennutzung. Höhere Orchestrierungsfunktionen wie integriertes Scale-out, revisionsbasiertes Routing oder Kubernetes-API fehlen.',architecture:'ACI ist ein schlanker Baustein für Batchjobs, Tests, Bursting oder einfache Dienste. Gegenüber Container Apps fehlen anwendungsbezogene Skalierung und Microservicefunktionen; gegenüber AKS fehlen Clusterkontrolle und umfassende Orchestrierung. Für dauerhafte, komplexe Produktionssysteme muss der Kunde fehlende Routing-, Skalierungs- und Lifecyclefunktionen selbst ergänzen.',why:'ACI minimiert Plattformbetrieb, bietet dafür bewusst weniger Anwendungsplattform.',examples:['Ein nächtlicher Datenkonvertierungsjob startet eine Containergruppe, schreibt das Ergebnis in Storage und beendet sich.'],merksatz:'ACI startet Container; es orchestriert keine Anwendungsplattform.',sources:['ms-aci-overview','ms-aci-groups','ms-container-options'],tags:['aci','container-instance','serverless-container']},
  'azure-0425': {title:'Azure Kubernetes Service (AKS)',simple:'AKS ist ein verwalteter Kubernetes-Dienst für containerisierte Anwendungen. Azure betreibt die Kubernetes-Control-Plane; Teams verwenden Kubernetes-Funktionen für Deployment, Skalierung, Netzwerk und Betrieb ihrer Workloads.',technical:'Ein AKS-Cluster besteht aus einer von Azure verwalteten Control Plane und Node Pools, auf denen Pods laufen. AKS integriert Azure-Netzwerk, Microsoft Entra, Azure RBAC, Workload Identity, Container Registry und Azure Monitor. AKS Automatic übernimmt mehr Node-, Upgrade-, Security- und Monitoringaufgaben als AKS Standard.',architecture:'AKS ist sinnvoll, wenn Kubernetes-API, Portabilität, komplexe Orchestrierung oder ein Plattformteam benötigt werden. Gegenüber ACI und Container Apps bietet es mehr Kontrolle, aber deutlich mehr Betriebs- und Governanceaufwand; gegenüber App Service ist es flexibler, aber komplexer. Netzwerkmodell, Identität, Policies, Node-Lifecycle, Upgrades, Observability und Kosten sind gemeinsame Architekturentscheidungen.',why:'AKS verlagert nicht sämtliche Kubernetes-Verantwortung zu Azure; der gewählte Modus definiert die verbleibende Betriebsfläche.',examples:['Eine Microservice-Plattform nutzt private AKS-Nodes im VNet, Workload Identity, Azure RBAC und Container Insights.'],merksatz:'AKS verwaltet Kubernetes, nicht automatisch deine Plattformpraxis.',sources:['ms-aks-overview','ms-aks-support','ms-monitor-aks'],tags:['aks','kubernetes','containers','architecture-bridge']},
  'azure-0427': {title:'Verwaltete Kubernetes-Orchestrierung',simple:'AKS stellt Kubernetes bereit, ohne dass der Kunde die Control Plane selbst installieren und betreiben muss. Kubernetes plant Container, hält gewünschten Zustand und steuert Deployments und Services.',technical:'Die Azure-verwaltete Control Plane verarbeitet Kubernetes-API, Scheduler- und Controllerfunktionen. Worker Nodes führen Pods über Kubelet und Container Runtime aus; Node Pools gruppieren Kapazität und Eigenschaften. Betriebsaufgaben unterscheiden sich zwischen AKS Automatic und Standard.',architecture:'Managed Kubernetes reduziert Control-Plane-Aufwand, lässt aber Workload-, Policy-, Identitäts-, Netzwerk- und häufig Node-Verantwortung bestehen. Ein Plattformteam sollte Standards und Self-Service schaffen, statt jedem Anwendungsteam Roh-Kubernetes zu überlassen. Wenn Kubernetes-spezifische Funktionen nicht nötig sind, ist ein höher abstrahierter Dienst oft wirtschaftlicher.',why:'Eine verwaltete Control Plane ist nur ein Teil einer produktionsreifen Containerplattform.',examples:['Ein Plattformteam definiert Namespaces, Policies, Ingress, Workload Identity und Observability als wiederverwendbare AKS-Basis.'],merksatz:'AKS nimmt dir die Control Plane ab, nicht das Plattformdesign.',sources:['ms-aks-overview','ms-aks-support'],tags:['aks','orchestration','shared-responsibility']},
  'azure-0428': {title:'AKS Skalierung, Load Balancing und Upgrades',simple:'AKS kann Pods und Nodes skalieren, Netzwerkverkehr verteilen und Clusterkomponenten aktualisieren. Diese Funktionen müssen passend zum Workload und Betriebsmodell konfiguriert werden.',technical:'Horizontal Pod Autoscaler, KEDA oder VPA steuern Workloadkapazität; Cluster Autoscaler oder Node Auto Provisioning passen Nodes an. Kubernetes Services und Ingress verteilen Verkehr. Upgrade-Kanäle, Node Images, Pod Disruption Budgets und Surge-Kapazität beeinflussen Wartung und Verfügbarkeit.',architecture:'Anwendungs- und Infrastrukturskalierung sind getrennte Regelkreise und benötigen aufeinander abgestimmte Grenzen. Upgrades müssen Versionen, Add-ons, APIs und Workloadunterbrechung berücksichtigen. AKS Automatic setzt stärker verwaltete Defaults, während Standard mehr bewusste Plattformverantwortung verlangt.',why:'Die größte AKS-Komplexität liegt im Zusammenspiel mehrerer Steuerungs- und Lifecyclemechanismen.',examples:['KEDA erhöht Worker-Pods nach Queue-Länge, anschließend stellt Node Auto Provisioning zusätzliche Node-Kapazität bereit.'],merksatz:'AKS skaliert Pods und Nodes in getrennten, gekoppelten Ebenen.',sources:['ms-aks-overview','ms-aks-support'],tags:['aks','autoscaling','upgrades','load-balancing']},
  'azure-0429': {title:'AKS Worker Nodes auf virtuellen Maschinen',simple:'AKS-Pods laufen auf Worker Nodes, die in Azure typischerweise als virtuelle Maschinen oder VM Scale Sets bereitgestellt werden. Die Control Plane ist verwaltet, die Workload benötigt aber weiterhin reale Compute-Kapazität.',technical:'Node Pools bündeln Nodes mit VM-Größe, Betriebssystem, Zonen- und Skalierungseigenschaften. Kubelet und Container Runtime führen Pods aus und kommunizieren mit der Control Plane. System- und User-Node-Pools können getrennte Rollen, Taints und Kapazitätsprofile besitzen.',architecture:'Die VM-Größe bestimmt Poddichte, Kosten sowie Compute-, Disk- und Netzwerkgrenzen. Mehrere Node Pools isolieren Workloadklassen, erhöhen aber Betriebs- und Upgradeaufwand. Je nach AKS-Modus teilen Azure und Kunde die Node-Verantwortung unterschiedlich; Workloadressourcen und Kapazitätsplanung bleiben relevant.',why:'Kubernetes abstrahiert Nodes für Entwickler, aber Architekten müssen ihre Kapazitäts- und Fehlergrenzen weiterhin entwerfen.',examples:['Systemkomponenten laufen auf einem kleinen zonenverteilten Pool, speicherintensive Workloads auf einem getrennten memory-optimierten Pool.'],merksatz:'Unter jedem Pod liegt Node-Kapazität mit echten Grenzen und Kosten.',sources:['ms-aks-overview','ms-aks-support','ms-vm-sizes'],tags:['aks','node-pool','virtual-machines']},
  'azure-0430': {title:'AKS für produktive Microservice-Plattformen',simple:'AKS eignet sich für größere containerisierte Plattformen mit vielen Services, automatisierten Deployments und Kubernetes-basierten Betriebsabläufen. Es ist besonders sinnvoll, wenn das Team Kubernetes-Funktionen tatsächlich benötigt und beherrscht.',technical:'Kubernetes Deployments, Services, Ingress, ConfigMaps, Secrets, Operators und Autoscaler bilden eine erweiterbare Plattform-API. CI/CD oder GitOps liefern Manifeste und Images; Policies, Identity, Netzwerk und Telemetrie kontrollieren den Betrieb. Der Cluster wird zur gemeinsam genutzten Plattformgrenze.',architecture:'AKS schafft Flexibilität und Standardisierung für komplexe Produktlandschaften, bringt aber Plattformteam, Governance, Upgrade- und Sicherheitsverantwortung mit. Für wenige normale Web-APIs ist App Service oder Container Apps oft einfacher. Die Entscheidung sollte Teamfähigkeit, Kontrollbedarf, Portabilität und Total Cost of Ownership einbeziehen.',why:'Kubernetes ist ein Organisations- und Betriebsmodell, nicht nur ein Ort zum Starten von Containern.',examples:['Ein Plattformteam bietet Namespaces, Workload Identity, Ingress, Policies und Observability als Golden Path für mehrere Produktteams.'],merksatz:'AKS lohnt sich, wenn Kubernetes-Fähigkeiten einen konkreten Mehrwert tragen.',sources:['ms-aks-overview','ms-container-options','ms-monitor-aks'],tags:['aks','microservices','platform-engineering']},
  'azure-0567': {title:'Azure Managed Disks',simple:'Azure Managed Disks sind von Azure verwaltete Blockspeicher für virtuelle Maschinen. Sie speichern Betriebssystem- und Anwendungsdaten unabhängig vom Lebenszyklus des physischen Hosts.',technical:'Der Kunde wählt Disktyp, Größe und Leistungsoptionen; Azure verwaltet Storage-Konten, Replikation und Platzierung im Hintergrund. Verfügbare Typen umfassen HDD- und mehrere SSD-Klassen mit unterschiedlichen IOPS-, Durchsatz- und Latenzprofilen. OS-, Daten- und temporäre Datenträger haben unterschiedliche Aufgaben.',architecture:'Managed Disks sind der Standard für persistente VM-Daten, müssen aber nach Leistung, Verfügbarkeit, Verschlüsselung, Snapshot- und Backupstrategie dimensioniert werden. VM-Größe und Disktyp begrenzen gemeinsam den erreichbaren Durchsatz. Für gemeinsam genutzten oder dateibasierten Zugriff können andere Storage-Dienste geeigneter sein.',why:'Compute- und Storage-Auswahl sind gekoppelt; eine schnelle Disk kann an einer VM-Grenze ausgebremst werden.',examples:['Eine Datenbank-VM verwendet Premium SSD für Daten und getrennte Disks für Logs, während Azure Backup Wiederherstellungspunkte erstellt.'],merksatz:'Managed Disk ist persistenter Blockspeicher; die VM bestimmt mit, wie schnell er nutzbar ist.',sources:['ms-managed-disks','ms-vm-sizes'],tags:['managed-disks','block-storage','vm']},
  'azure-0568': {title:'Managed-Disk-Typen und VM-Anbindung',simple:'Managed Disks gibt es als HDD- und verschiedene SSD-Typen für unterschiedliche Leistungs- und Kostenanforderungen. Eine VM verwendet mindestens einen OS-Datenträger und kann zusätzliche Daten-Datenträger anbinden.',technical:'Standard HDD und Standard SSD bedienen kostensensitive Lasten; Premium SSD, Premium SSD v2 und Ultra Disk adressieren höhere IOPS, Durchsatz oder Latenzanforderungen. Größe und Typ definieren Leistungsgrenzen, zusätzlich begrenzt die VM-Größe aggregierte Storageleistung und die Zahl anschließbarer Disks. Temporärer lokaler Storage ist nicht persistent.',architecture:'Diskauswahl folgt dem I/O-Profil statt einer pauschalen Premium-Vorgabe. Architekten trennen OS, Daten, Logs und temporäre Daten nach Bedarf und prüfen Zonenunterstützung, Cache, Burst, Backup und Kosten. Persistente Daten dürfen nicht versehentlich auf temporären lokalen Disks liegen.',why:'Falscher Disktyp verursacht entweder unnötige Kosten oder einen kaum sichtbaren Leistungsengpass.',examples:['Eine transaktionsintensive VM nutzt Premium SSD für Daten, eine getrennte Log-Disk und lokalen temporären Storage nur für wiederherstellbaren Cache.'],merksatz:'Diskleistung endet am kleineren Limit von Datenträger und VM.',sources:['ms-managed-disks','ms-vm-sizes'],tags:['managed-disk','ssd','hdd','performance']},
  'azure-0831': {title:'Compute Security Responsibility',simple:'Compute-Sicherheit schützt virtuelle Maschinen und Container über Identität, Netzwerk, Härtung, Patchen und Überwachung. Welche Aufgaben Azure übernimmt, hängt vom gewählten Dienstmodell ab.',technical:'Bei VMs verantwortet der Kunde Gastbetriebssystem, lokale Konten, Patches, Endpoint-Schutz und Netzregeln. App Service verwaltet OS und Plattform, während Anwendung, Daten und Konfiguration beim Kunden bleiben. AKS teilt Verantwortung zwischen verwalteter Control Plane, Nodes und Workloads je nach Modus.',architecture:'Ein Architekt wählt nicht nur einen Compute-Dienst, sondern eine Sicherheitsverantwortungsfläche. Managed Identity und RBAC reduzieren Secrets und Zugriffsbreite, NSGs und private Netzpfade begrenzen Erreichbarkeit, Defender for Cloud bewertet Risiken und Azure Monitor liefert Betriebssignale. Kontrollen müssen über Policy und Plattformstandards skalieren.',why:'Mehr Kontrolle bedeutet mehr eigene Sicherheitsarbeit; unklare Ownership erzeugt Lücken zwischen Plattform und Anwendung.',examples:['Eine VM-Baseline kombiniert NSG, Managed Identity, minimales RBAC, Updateprozess, Defender for Servers und zentrale Logs.'],merksatz:'Sicherheit folgt der Verantwortungsschicht des Compute-Dienstes.',sources:['ms-vm-overview','ms-app-service-patching','ms-aks-support','ms-defender-servers'],tags:['compute-security','shared-responsibility','architecture-bridge']},
  'azure-0832': {title:'VM Security Operations',simple:'Sicherer VM-Betrieb umfasst regelmäßige Updates, Endpoint-Schutz, Schwachstellenmanagement und zeitlich begrenzten administrativen Zugriff. Defender for Cloud und Azure-Dienste unterstützen diese Aufgaben, ersetzen aber keine verantworteten Prozesse.',technical:'Update Manager oder definierte Wartungsverfahren bewerten und installieren Gast-Updates. Defender for Servers liefert Security-Posture-Empfehlungen, Schwachstellen- und Bedrohungserkennung; Just-in-Time Access schließt Verwaltungsports und öffnet sie nur kontrolliert. Azure Monitor ergänzt Betriebs- und Gasttelemetrie.',architecture:'Sicherheitskontrollen sollten subscriptionweit standardisiert, per Policy geprüft und mit Ausnahme-, Wartungs- und Incident-Prozessen verbunden werden. Offene RDP- oder SSH-Ports sind zu vermeiden; Managed Identity und RBAC begrenzen administrative Secrets und Rechte. Kosten, Agenten, Datenresidenz und Alarmverantwortung müssen eingeplant werden.',why:'VM-Freiheit schafft eine dauerhaft zu pflegende Angriffsfläche im Gastbetriebssystem.',examples:['Administratoren aktivieren RDP nur per JIT, Updates laufen in Wartungsfenstern und kritische Defender-Alarme gehen an das SOC.'],merksatz:'Eine sichere VM ist ein laufender Betriebsprozess, keine einmalige Härtung.',sources:['ms-vm-maintenance','ms-defender-servers','ms-jit-vm','ms-monitor-vm'],tags:['vm-security','defender-for-cloud','patch-management','jit']}
};

const relationDefinitions = [
  ['compute-rel-001','azure-0322','azure-0442','deployed_in','Eine Azure VM erhält eine Netzwerkschnittstelle in einem Subnetz des Virtual Network und nutzt dessen private Netzwerkgrenze.',['ms-vm-overview','ms-vnet-subnets'],0.99],
  ['compute-rel-002','azure-0505','azure-0322','routes_to','Azure Load Balancer verteilt Layer-4-Flows an erreichbare VM-Backends im Backend Pool.',['ms-load-balancing','ms-vm-overview'],0.99],
  ['compute-rel-003','azure-0322','azure-0947','uses','Eine VM oder eine auf ihr laufende Workload kann Managed Identity für tokenbasierten Zugriff ohne gespeichertes Anwendungsgeheimnis verwenden.',['ms-managed-identities','ms-vm-overview'],0.98],
  ['compute-rel-004','azure-0964','azure-0322','governs','Azure RBAC steuert Management-Plane-Aktionen auf der VM und ihrem Scope; es ersetzt keine Anmeldung im Gastbetriebssystem.',['ms-rbac','ms-role-assignments','ms-vm-overview'],0.99],
  ['compute-rel-005','azure-0322','azure-0864','secured_by','Eine der VM-NIC oder ihrem Subnetz zugeordnete NSG filtert eingehende und ausgehende Layer-3/4-Verbindungen.',['ms-nsg-asg','ms-vm-overview'],0.99],
  ['compute-rel-006','azure-0933','azure-0322','monitors','Defender for Cloud bewertet die Sicherheitslage der VM und Defender for Servers ergänzt Bedrohungs- und Schwachstellenschutz.',['ms-defender-servers'],0.99],
  ['compute-rel-007','azure-0983','azure-0322','monitors','Azure Monitor erfasst standardmäßig Hostmetriken und kann über den Azure Monitor Agent Gastmetriken und Logs der VM sammeln.',['ms-monitor-vm'],0.99],
  ['compute-rel-008','azure-0322','azure-0985','logs_to','VM-Aktivitäts- und konfigurierte Gastlogs können zur zentralen KQL-Analyse in einen Log Analytics Workspace geschrieben werden.',['ms-monitor-vm','ms-log-analytics'],0.99],
  ['compute-rel-009','azure-0322','azure-0567','uses','Azure VMs verwenden Managed Disks als persistente OS- und Daten-Blockvolumes.',['ms-managed-disks','ms-vm-overview'],0.99],
  ['compute-rel-010','azure-0322','azure-0116','uses','Azure Backup erzeugt richtliniengesteuerte Wiederherstellungspunkte für geschützte Azure VMs.',['ms-vm-backup'],0.99],
  ['compute-rel-011','azure-0322','azure-0118','uses','Azure Site Recovery kann VMs kontinuierlich replizieren und Failover in eine Zielumgebung orchestrieren.',['ms-site-recovery'],0.99],
  ['compute-rel-012','azure-0322','azure-0005','uses','Mehrere VMs in einem Availability Set werden auf Fault und Update Domains verteilt.',['ms-availability-sets'],0.99],
  ['compute-rel-013','azure-0322','azure-0007','uses','Redundante VM-Instanzen können über Availability Zones verteilt werden, um Rechenzentrumsausfälle zu tolerieren.',['ms-vm-overview','ms-zones-overview'],0.99],
  ['compute-rel-014','azure-0387','azure-0322','contains','Ein VM Scale Set verwaltet eine Gruppe von VM-Instanzen über ein gemeinsames Orchestrierungs- und Skalierungsmodell.',['ms-vmss-overview'],0.99],
  ['compute-rel-015','azure-0387','azure-0007','uses','Ein VM Scale Set kann Instanzen zonal oder über mehrere Availability Zones verteilen.',['ms-vmss-overview'],0.99],
  ['compute-rel-016','azure-0387','azure-0025','uses','VMSS verwendet Autoscale-Regeln oder Zeitpläne, um seine Instanzzahl an den Bedarf anzupassen.',['ms-vmss-autoscale'],0.99],
  ['compute-rel-017','azure-0025','azure-0020','uses','Autoscale setzt bei VMSS und App Service typischerweise horizontale Skalierung durch Erhöhen oder Reduzieren der Instanzzahl um.',['ms-vmss-autoscale','ms-app-service-plan'],0.98],
  ['compute-rel-018','azure-0015','azure-0020','alternative_to','Vertikale und horizontale Skalierung sind alternative oder kombinierbare Kapazitätsstrategien mit unterschiedlichen Verfügbarkeits- und Anwendungsanforderungen.',['ms-vm-overview','ms-vmss-overview'],0.97],
  ['compute-rel-019','azure-0351','azure-0363','uses','Jede App-Service-App läuft in einem App Service Plan, der ihre Compute-Kapazität und Plattformfunktionen festlegt.',['ms-app-service-plan'],0.99],
  ['compute-rel-020','azure-0376','azure-0351','part_of','Websites und Web APIs sind zentrale Anwendungstypen, die auf Azure App Service ausgeführt werden.',['ms-app-service'],0.99],
  ['compute-rel-021','azure-0371','azure-0351','part_of','Deployment Slots, Custom Domains und TLS sind App-Service-Funktionen für sichere Veröffentlichung und Releases.',['ms-app-service-slots','ms-app-service-plan'],0.99],
  ['compute-rel-022','azure-0351','azure-0947','uses','App Service kann eine system- oder benutzerzugewiesene Managed Identity für Azure-Ressourcenzugriffe verwenden.',['ms-managed-identities','ms-app-service'],0.99],
  ['compute-rel-023','azure-0964','azure-0351','governs','Azure RBAC steuert, welche Security Principals die App-Service-Ressource auf der Management Plane verwalten dürfen.',['ms-rbac','ms-role-assignments'],0.99],
  ['compute-rel-024','azure-0983','azure-0351','monitors','Azure Monitor verarbeitet Plattformmetriken, Diagnoseprotokolle und anwendungsbezogene Telemetrie von App Service.',['ms-app-service','ms-log-analytics'],0.98],
  ['compute-rel-025','azure-0351','azure-0985','logs_to','App-Service-Diagnoseeinstellungen können unterstützte Plattform- und Anwendungslogs an Log Analytics senden.',['ms-log-analytics','ms-app-service'],0.98],
  ['compute-rel-026','azure-0369','azure-0025','uses','App Service Autoscale verwendet Regeln und Plangrenzen, um die Zahl der Worker-Instanzen anzupassen.',['ms-app-service-plan'],0.98],
  ['compute-rel-027','azure-0415','azure-0425','alternative_to','ACI und AKS führen Container aus, unterscheiden sich aber grundlegend zwischen einfacher Containergruppe und vollständiger Kubernetes-Orchestrierung.',['ms-container-options','ms-aci-overview','ms-aks-overview'],0.99],
  ['compute-rel-028','azure-0415','azure-0412','part_of','Azure Container Instances ist eine der vorhandenen Compute-Optionen für Azure-Containerworkloads.',['ms-aci-overview','ms-container-options'],0.99],
  ['compute-rel-029','azure-0425','azure-0412','part_of','Azure Kubernetes Service ist die verwaltete Kubernetes-Option innerhalb der Azure-Containerdienste.',['ms-aks-overview','ms-container-options'],0.99],
  ['compute-rel-030','azure-0425','azure-0947','uses','AKS-Workloads können Workload Identity auf Basis von Microsoft Entra und Managed-Identity-Komponenten für Azure-Zugriffe verwenden.',['ms-aks-overview','ms-managed-identities'],0.98],
  ['compute-rel-031','azure-0964','azure-0425','governs','Azure RBAC kann Managementzugriff auf den AKS-Cluster und bei entsprechender Integration Kubernetes-Autorisierung steuern.',['ms-aks-overview','ms-rbac'],0.98],
  ['compute-rel-032','azure-0425','azure-0985','logs_to','Container Insights und Diagnoseeinstellungen können AKS-Logs zur zentralen Analyse an Log Analytics senden.',['ms-monitor-aks','ms-log-analytics'],0.99],
  ['compute-rel-033','azure-0429','azure-0425','part_of','Worker Nodes bilden als VM-basierte Node Pools die Compute-Ebene, auf der AKS-Pods ausgeführt werden.',['ms-aks-overview','ms-aks-support'],0.99],
  ['compute-rel-034','azure-0831','azure-0322','secures','Compute Security Responsibility umfasst für VMs Gast-Härtung, Patches, Netzwerk-, Identitäts- und Überwachungskontrollen.',['ms-vm-overview','ms-defender-servers'],0.98]
];

for (const source of officialSources) {
  const index = sourcesDocument.sources.findIndex(item => item.id === source.id);
  if (index >= 0) sourcesDocument.sources[index] = source;
  else sourcesDocument.sources.push(source);
}
for (const type of extraRelationTypes) {
  const index = typesDocument.relation_types.findIndex(item => item.id === type.id);
  if (index >= 0) typesDocument.relation_types[index] = type;
  else typesDocument.relation_types.push(type);
}
const typeById = new Map(typesDocument.relation_types.map(type => [type.id, type]));

for (const [id, enrichment] of Object.entries(E)) {
  const node = nodeById.get(id);
  if (!node) throw new Error(`Pilotknoten fehlt: ${id}`);
  const originalTitle = node.title;
  node.title = enrichment.title || node.title;
  node.description = {simple:enrichment.simple,technical:enrichment.technical,architecture:enrichment.architecture};
  node.why_important = enrichment.why;
  node.examples = enrichment.examples || [];
  node.merksatz = enrichment.merksatz || '';
  node.analogy = enrichment.analogy || '';
  node.sources = [...new Set([...(node.sources || []), ...enrichment.sources])];
  node.tags = [...new Set([...(node.tags || []).filter(tag => tag !== 'compute-architecture-pilot-v1.4'), ...(enrichment.tags || []), 'compute-pilot-v1.4'])];
  node.aliases = [...new Set([...(node.aliases || []), ...(originalTitle !== node.title ? [originalTitle] : [])])];
  node.metadata = {...node.metadata,status:'published',audit_flags:(node.metadata.audit_flags || []).filter(flag => flag !== 'description_generated_from_title'),enrichment:{version:'1.4',pilot:'compute-architecture-bridge',content_standard:'1.0',reviewed_at:today,source_policy:'official_microsoft_only'}};
  node.updated_at = today;
}

const pilotRelationIds = new Set(relationDefinitions.map(([id]) => id));
relationsDocument.relations = relationsDocument.relations.filter(relation => !pilotRelationIds.has(relation.id));
for (const node of nodesDocument.nodes) node.relations = (node.relations || []).filter(id => !pilotRelationIds.has(id));
for (const [id, source, target, type, explanation, sources, confidence] of relationDefinitions) {
  if (!nodeById.has(source) || !nodeById.has(target)) throw new Error(`${id}: Endpunkt fehlt`);
  const typeDefinition = typeById.get(type);
  if (!typeDefinition) throw new Error(`${id}: Typ ${type} fehlt`);
  const relation = {schema_version:'1.1',id,source,target,type,inverse_type:typeDefinition.inverse_type,explanation,sources,confidence,status:'accepted',created_by:'knowledge_enrichment_v1.4',created_at:today,reviewed_at:today};
  relationsDocument.relations.push(relation);
  for (const nodeId of [source,target]) {
    const node = nodeById.get(nodeId);
    node.relations = [...new Set([...(node.relations || []), id])];
  }
}

const legacyComputeRefinements = {
  'rel-007':{explanation:'Application Gateway kann HTTP(S)-Anfragen auf App Service routen; Backend-, TLS- und Zugriffskonfiguration müssen als gemeinsamer Layer-7-Pfad entworfen werden.',sources:['ms-app-gateway','ms-app-service'],confidence:0.99,reviewed_at:today},
  'rel-015':{explanation:'VM Scale Sets verwenden häufig Azure Load Balancer für Layer-4-Verteilung und Health Probes; Application Gateway ist eine Layer-7-Alternative für HTTP(S).',sources:['ms-vmss-overview','ms-load-balancing','ms-app-gateway'],confidence:0.99,reviewed_at:today},
  'rel-017':{explanation:'AKS integriert seine Node- und Pod-Netzwerkpfade in Azure Virtual Network; das konkrete Netzwerkmodell bestimmt IP-Planung und Konnektivität.',sources:['ms-aks-overview','ms-vnet-subnets'],confidence:0.98,reviewed_at:today},
  'rel-018':{explanation:'Azure Monitor und Container Insights erfassen AKS-Metriken, Logs und Zustandsinformationen über Control Plane, Nodes, Pods und Anwendungen.',sources:['ms-monitor-aks'],confidence:0.99,reviewed_at:today}
};
for (const relation of relationsDocument.relations) if (legacyComputeRefinements[relation.id]) Object.assign(relation, legacyComputeRefinements[relation.id]);

nodesDocument.meta = {...nodesDocument.meta,enrichment_version:'1.4',compute_pilot:{node_count:Object.keys(E).length,relation_count:relationDefinitions.length,content_standard:'1.0',reviewed_at:today,focus:'architecture_bridge'}};
relationsDocument.meta = {...relationsDocument.meta,relation_count:relationsDocument.relations.length,enrichment_version:'1.4',compute_relation_count:relationDefinitions.length};
sourcesDocument.meta = {...sourcesDocument.meta,count:sourcesDocument.sources.length,generated_at:today,enrichment_version:'1.4'};
typesDocument.meta = {...typesDocument.meta,type_count:typesDocument.relation_types.length,updated_at:today,enrichment_version:'1.4'};

write('nodes.json',nodesDocument);
write('relations.json',relationsDocument);
write('sources.json',sourcesDocument);
write('relation-types.json',typesDocument);

console.log(JSON.stringify({enriched_nodes:Object.keys(E).length,added_relations:relationDefinitions.length,total_relations:relationsDocument.relations.length,added_relation_types:extraRelationTypes.length,total_relation_types:typesDocument.relation_types.length,added_sources:officialSources.length,total_sources:sourcesDocument.sources.length},null,2));
