import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonical = path.join(project, 'data/canonical');
const today = '2026-08-11';
const read = name => JSON.parse(fs.readFileSync(path.join(canonical, name), 'utf8'));
const write = (name, value) => fs.writeFileSync(path.join(canonical, name), `${JSON.stringify(value, null, 2)}\n`);

const nodesDocument = read('nodes.json');
const relationsDocument = read('relations.json');
const sourcesDocument = read('sources.json');
const typesDocument = read('relation-types.json');
const nodeById = new Map(nodesDocument.nodes.map(node => [node.id, node]));

const officialSources = [
  {id:'ms-governance-overview',title:'What are the Azure Management areas?',url:'https://learn.microsoft.com/en-us/azure/governance/management-groups/azure-management',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-management-groups',title:'Manage Azure subscriptions at scale with management groups',url:'https://learn.microsoft.com/en-us/azure/governance/management-groups/manage',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-management-group-design',title:'Management groups – Cloud Adoption Framework',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-management-groups',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-subscription-design',title:'Subscriptions – Cloud Adoption Framework',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-subscriptions',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-arm-overview',title:'What is Azure Resource Manager?',url:'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-overview',title:'What is Azure Policy?',url:'https://learn.microsoft.com/en-us/azure/governance/policy/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-definitions',title:'Azure Policy definition structure basics',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure-basics',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-assignments',title:'Azure Policy assignment structure',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-initiatives',title:'Azure Policy initiative definition structure',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/initiative-definition-structure',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-effects',title:'Azure Policy definitions effect basics',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-compliance',title:'Azure Policy compliance states',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/compliance-states',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-policy-regulatory',title:'Regulatory Compliance in Azure Policy',url:'https://learn.microsoft.com/en-us/azure/governance/policy/concepts/regulatory-compliance',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-resource-naming',title:'Define your naming convention',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-resource-tags',title:'Use tags to organize your Azure resources and management hierarchy',url:'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-resource-tagging-strategy',title:'Define your tagging strategy',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-tagging',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-resource-locks',title:'Lock your Azure resources to protect your infrastructure',url:'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cost-management',title:'What is Microsoft Cost Management?',url:'https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/overview-cost-management',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cost-plan',title:'Plan to manage Azure costs',url:'https://learn.microsoft.com/en-us/azure/cost-management-billing/understand/plan-manage-costs',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cost-analysis',title:'Start using Cost Analysis',url:'https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/quick-acm-cost-analysis',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-posture',title:'Cloud overview dashboard in Microsoft Defender for Cloud',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/cloud-infrastructure-dashboard',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-regulatory',title:'Assign regulatory compliance standards in Microsoft Defender for Cloud',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/assign-regulatory-compliance-standards',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-security-benchmark',title:'Microsoft cloud security benchmark',url:'https://learn.microsoft.com/en-us/security/benchmark/azure/',publisher:'Microsoft Learn',accessed_at:today,type:'official'}
];

const extraRelationTypes = [
  {id:'organizes',label:'organisiert',inverse_type:'organized_by',inverse_label:'wird organisiert durch',description:'Das Quellobjekt strukturiert oder klassifiziert das Ziel nach einer vereinbarten Taxonomie.',color:'#b38cff',priority:72,symmetric:false},
  {id:'organized_by',label:'wird organisiert durch',inverse_type:'organizes',inverse_label:'organisiert',description:'Das Objekt wird durch die verbundene Taxonomie, Kennzeichnung oder Konvention strukturiert.',color:'#b38cff',priority:72,symmetric:false}
];

const E = {
  'azure-0033':{title:'Budgets und Kostenwarnungen',simple:'Azure-Budgets vergleichen aktuelle oder prognostizierte Kosten mit einem festgelegten Schwellenwert. Sie informieren Verantwortliche frühzeitig über auffällige Ausgaben, begrenzen die Ressourcennutzung aber nicht automatisch.',technical:'Budgets werden in Cost Management an einem unterstützten Abrechnungs- oder Ressourcenscope erstellt und besitzen Zeitraum, Betrag sowie Warnschwellen. Benachrichtigungen können Empfänger oder Action Groups adressieren. Die zugrunde liegenden Kostendaten treffen zeitversetzt ein, daher sind Budgets kein Echtzeit-Limit.',architecture:'Budgets gehören zu einem FinOps-Regelkreis aus Verantwortlichkeit, Analyse und Reaktion. Schwellen sollten nach Umgebung und Kritikalität gestaffelt, mit Forecast-Werten ergänzt und einem benannten Owner zugeordnet werden. Für harte technische Begrenzungen sind Quotas, Policies oder automatisierte Freigabeprozesse nötig.',why:'Ohne frühe Kostenwarnung werden Fehlkonfigurationen oder Laständerungen oft erst auf der Rechnung sichtbar.',examples:['Eine Produktions-Subscription warnt das FinOps-Team bei 80 Prozent Forecast und den Service Owner bei 100 Prozent Istkosten.'],merksatz:'Ein Budget warnt vor Kosten, es stoppt keine Ressourcen.',sources:['ms-cost-plan','ms-cost-management'],tags:['budget','cost-alert','finops']},
  'azure-0036':{title:'Azure Governance',simple:'Azure Governance umfasst Regeln, Strukturen und Verantwortlichkeiten für den kontrollierten Betrieb von Cloud-Ressourcen. Sie sorgt dafür, dass Teams Azure sicher, konform und kostenbewusst nutzen können, ohne jede Entscheidung einzeln abzustimmen.',technical:'Governance kombiniert Managementhierarchie, Azure Policy, Azure RBAC, Tags, Resource Locks, Cost Management und Security-Posture-Dienste. Einstellungen werden an Scopes wie Management Group, Subscription, Resource Group oder Ressource angewendet und teilweise nach unten vererbt. Compliance- und Kostendaten machen Abweichungen sichtbar.',architecture:'Enterprise Governance trennt verbindliche Guardrails von teamnahen Freiräumen. Die Hierarchie sollte stabil nach gemeinsamen Policy-, Zugriffs-, Netzwerk- und Complianceanforderungen aufgebaut werden, nicht als Kopie des Organigramms. Zu viele globale Regeln erhöhen Konflikte und Ausnahmen; zu wenig Steuerung erzeugt Drift und Wildwuchs.',why:'Governance übersetzt Unternehmensanforderungen in skalierbare technische und organisatorische Kontrollen.',examples:['Eine Plattformorganisation setzt an Management Groups regionale Vorgaben und Security-Baselines, während Produktteams ihre Ressourcen innerhalb freigegebener Subscriptions betreiben.'],merksatz:'Governance schafft Leitplanken, Scopes und Nachweisbarkeit für dezentrale Cloud-Teams.',sources:['ms-governance-overview','ms-management-group-design'],tags:['governance','enterprise-scale','guardrails']},
  'azure-0037':{title:'Governance-Regeln, Standards und Kontrollen',simple:'Governance-Regeln beschreiben, welche Cloud-Nutzung erlaubt, erforderlich oder zu überwachen ist. Standards machen wiederkehrende Entscheidungen einheitlich, während Kontrollen ihre Einhaltung prüfen oder durchsetzen.',technical:'Anforderungen werden über Policy Definitions und Initiatives, RBAC-Zuweisungen, Tags, Locks, Budgets und Security-Empfehlungen umgesetzt. Präventive Kontrollen blockieren unerwünschte Änderungen; detektive Kontrollen melden Abweichungen; korrektive Mechanismen unterstützen Remediation. Jede Kontrolle benötigt Scope, Owner, Ausnahmeprozess und Messsignal.',architecture:'Ein gutes Kontrollsystem folgt dem Risiko und setzt möglichst wenige Regeln am breitesten sinnvollen Scope. Globale Guardrails sollten stabil und testbar sein; workload-spezifische Regeln gehören näher an die Subscription oder Resource Group. Kontrollen ohne Ownership erzeugen Reports, aber keine Verbesserung.',why:'Erst das Zusammenspiel aus Standard, Durchsetzung und verantworteter Reaktion macht Governance wirksam.',examples:['Ein Konzern blockiert öffentliche Storage-Endpunkte zentral, erlaubt aber dokumentierte Ausnahmen mit Ablaufdatum für eine Migrationsphase.'],merksatz:'Eine Regel ohne Scope und Owner ist keine betreibbare Kontrolle.',sources:['ms-governance-overview','ms-policy-overview','ms-management-group-design'],tags:['governance-controls','standards','compliance']},
  'azure-0038':{title:'Governance-Scopes und Managementhierarchie',simple:'Azure ordnet Governance in mehrere Ebenen: Management Groups, Subscriptions, Resource Groups und einzelne Ressourcen. Eine Regel an einer höheren Ebene kann für darunterliegende Bereiche gelten.',technical:'Azure Resource Manager stellt diese vier Managementscopes bereit. Management Groups gruppieren Subscriptions; Subscriptions enthalten Resource Groups; Resource Groups enthalten die meisten Ressourcen. Policy- und RBAC-Zuweisungen können vererbt werden, während Tags nicht automatisch von Resource Groups auf Ressourcen vererbt werden.',architecture:'Die Scopewahl bestimmt Reichweite, Delegation und Fehlerauswirkung einer Kontrolle. Stabile, gemeinsame Vorgaben gehören höher; workload- oder teamspezifische Regeln tiefer. Überbreite Assignments erschweren Ausnahmen und Fehleranalyse, während zu tiefe Zuweisungen Konsistenz und Betriebsskalierung verschlechtern.',why:'Fast jede Governance-Fehlkonfiguration ist zugleich eine Scope-Entscheidung mit zu großer oder zu kleiner Wirkung.',examples:['Eine Management Group erzwingt erlaubte Regionen für alle Produktions-Subscriptions, während ein Team eigenes RBAC nur auf seiner Resource Group erhält.'],merksatz:'Je höher der Scope, desto größer Reichweite und Verantwortung.',sources:['ms-arm-overview','ms-management-groups'],tags:['scope','management-hierarchy','inheritance']},
  'azure-0040':{title:'Governance Guardrails',simple:'Guardrails sind verbindliche Leitplanken, innerhalb derer Teams Azure selbstständig nutzen können. Sie verhindern oder melden besonders riskante und unerwünschte Konfigurationen.',technical:'Azure Policy liefert präventive und detektive Effects wie deny, audit und modify; RBAC begrenzt Managementaktionen und Resource Locks schützen vor Löschung oder Änderung. Guardrails können auf Management-Group-, Subscription- oder Resource-Group-Ebene zugewiesen werden. Compliance-Daten und Ausnahmen gehören zum Lifecycle.',architecture:'Guardrails sollten wenige, risikobasierte Mindestanforderungen durchsetzen und über Sandboxen oder gestufte Rollouts getestet werden. Zu strikte Regeln blockieren Lieferung und erzeugen Schattenprozesse; reine Audit-Regeln ohne Remediation tolerieren dauerhafte Drift. Landing-Zone-Teams benötigen einen transparenten Ausnahme- und Änderungsprozess.',why:'Guardrails ermöglichen dezentrale Geschwindigkeit, ohne zentrale Sicherheits- und Complianceziele aufzugeben.',examples:['Eine Policy prüft neue Regeln zunächst im Audit-Modus und wechselt nach behobenen Abweichungen in den Deny-Modus.'],merksatz:'Guardrails definieren sicheren Freiraum, nicht jeden Umsetzungsschritt.',sources:['ms-policy-overview','ms-policy-effects','ms-management-group-design'],tags:['guardrails','policy','platform-governance']},
  'azure-0041':{title:'Azure Policy und Initiatives',simple:'Azure Policy prüft Ressourcen gegen organisatorische Regeln und kann bestimmte Konfigurationen blockieren oder korrigieren. Initiatives bündeln mehrere zusammengehörige Policy Definitions, damit sie gemeinsam zugewiesen und ausgewertet werden können.',technical:'Eine Policy Definition enthält Bedingung und Effect; ein Policy Assignment verbindet Definition oder Initiative mit einem Scope, Parametern, Ausschlüssen und Enforcement Mode. Azure Policy bewertet anwendbare Ressourcen und erzeugt Compliance States. Initiatives gruppieren Definitionen und Parameter zu einem kontrollierbaren Standard.',architecture:'Initiatives sind die geeignete Einheit für Baselines wie Logging, Tags oder Security Controls. Versionierung, Testscopes, Assignment-Ownership, Exemptions und Remediation müssen als Policy-as-Code-Prozess betrieben werden. Eine große Initiative vereinfacht Zuweisung, kann aber Fehlersuche und differenzierte Ausnahmen erschweren.',why:'Policy macht Architekturstandards über viele Teams und Subscriptions technisch prüf- und durchsetzbar.',examples:['Eine Produktionsinitiative verlangt Diagnostikeinstellungen, erlaubte Regionen und definierte Tags für alle enthaltenen Subscriptions.'],merksatz:'Definition beschreibt eine Regel; Assignment gibt ihr Scope; Initiative bündelt Regeln.',sources:['ms-policy-overview','ms-policy-definitions','ms-policy-assignments','ms-policy-initiatives'],tags:['azure-policy','initiative','policy-assignment']},
  'azure-0042':{title:'Azure-Policy-Effects',simple:'Ein Policy Effect bestimmt, was Azure tut, wenn eine Ressource eine Policy-Bedingung erfüllt. Je nach Effect wird die Konfiguration nur gemeldet, blockiert, verändert oder durch eine ergänzende Bereitstellung korrigiert.',technical:'Häufige Effects sind `audit`, `deny`, `modify`, `append`, `auditIfNotExists` und `deployIfNotExists`. Welcher Effect verfügbar ist, hängt vom Auswertungsmodus und Ressourcentyp ab. Bestehende Abweichungen benötigen bei korrektiven Effects häufig eine Remediation Task und passende Managed-Identity-Berechtigungen.',architecture:'Effects sollten gestuft von Sichtbarkeit zu Durchsetzung eingeführt werden. `deny` verhindert neue Drift, repariert aber keine bestehenden Ressourcen; `modify` und `deployIfNotExists` erhöhen Automatisierung, benötigen jedoch Berechtigungen und getestete Idempotenz. Falsche Effects können Deployments unterbrechen oder ungewollt Konfiguration verändern.',why:'Der Effect entscheidet, ob Governance nur beobachtet oder aktiv in den Ressourcenlebenszyklus eingreift.',examples:['Eine Policy prüft fehlende Diagnostic Settings zunächst mit auditIfNotExists und stellt sie später kontrolliert mit deployIfNotExists bereit.'],merksatz:'Die Regel erkennt den Zustand; der Effect bestimmt die Reaktion.',sources:['ms-policy-effects','ms-policy-compliance'],tags:['policy-effect','deny','audit','remediation']},
  'azure-0047':{title:'Standards, Naming und Wiederverwendbarkeit',simple:'Cloud-Standards legen wiederverwendbare Muster für Namen, Tags, Scopes und Bereitstellung fest. Sie verbessern Auffindbarkeit und Zusammenarbeit, wenn Teams sie konsistent anwenden.',technical:'Naming Conventions kombinieren stabile Bestandteile wie Ressourcentyp, Workload, Umgebung, Region und Instanznummer unter Beachtung ressourcenspezifischer Namensregeln. Tags speichern veränderliche Metadaten als Schlüssel-Wert-Paare. Policy und Infrastructure as Code können beide Standards prüfen oder anwenden.',architecture:'Namen sollten nur dauerhafte Informationen enthalten, weil viele Ressourcennamen später nicht geändert werden können; wechselnde Zuständigkeit oder Kostenstelle gehört in Tags. Ein zentraler Standard benötigt dokumentierte Abkürzungen, Ausnahmen und automatisierte Tests. Überladene Namen werden unlesbar und bleiben trotzdem unvollständig.',why:'Konsistente Standards machen große Umgebungen automatisierbar, abfragbar und über Teams hinweg verständlich.',examples:['Ein VNet heißt `vnet-shop-prod-westeu-001`, während Owner und CostCenter als veränderliche Tags gespeichert werden.'],merksatz:'Stabiles in den Namen, Veränderliches in Tags.',sources:['ms-resource-naming','ms-resource-tagging-strategy','ms-policy-overview'],tags:['naming-standard','reusability','resource-organization']},
  'azure-0057':{title:'Kostensteuerung und FinOps-Governance',simple:'Kostensteuerung verbindet Kostentransparenz, Verantwortlichkeit und regelmäßige Optimierung. Ziel ist nicht nur weniger Ausgaben, sondern der wirtschaftliche Einsatz von Cloud-Ressourcen für den gewünschten Nutzen.',technical:'Cost Management analysiert bewertete Nutzungsdaten nach Scopes, Services, Ressourcengruppen und Tags. Budgets, Forecasts, Anomalie- und geplante Alerts überwachen Entwicklungen; Exports und APIs integrieren Daten in FinOps-Prozesse. Tags und Hierarchie ordnen Kosten verantwortlichen Teams zu.',architecture:'Kosten brauchen einen Operating Rhythm mit Ownern, Budgets, Unit Economics und Maßnahmen. Subscription- und Resource-Group-Grenzen sollten technische Isolation mit finanzieller Verantwortlichkeit unterstützen. Reine Abschaltvorgaben können Verfügbarkeit gefährden; Optimierung muss Serviceziele und Reservierungsrisiken einbeziehen.',why:'Cloudkosten sind dynamisch und dezentral verursacht; ohne Governance fehlt die Verbindung zwischen Nutzung und Verantwortung.',examples:['Jedes Produktteam prüft monatlich Kosten pro Umgebung, erklärt Abweichungen und priorisiert Maßnahmen gemeinsam mit FinOps.'],merksatz:'FinOps macht Kosten sichtbar, zurechenbar und entscheidbar.',sources:['ms-cost-management','ms-cost-plan'],tags:['cost-governance','finops','accountability']},
  'azure-0059':{title:'Governance Compliance und Reporting',simple:'Compliance Reporting zeigt, welche Ressourcen festgelegte Regeln und Standards erfüllen. Es macht Abweichungen sichtbar, ersetzt aber weder die fachliche Bewertung noch ihre Behebung.',technical:'Azure Policy aggregiert Compliance States pro Assignment, Definition, Initiative und Ressource. Defender for Cloud ordnet Security-Empfehlungen unterstützten regulatorischen Standards zu. Reports müssen Scope, Zeitpunkt, Exemptions, nicht anwendbare Ressourcen und Verantwortungsanteile berücksichtigen.',architecture:'Compliance ist ein kontinuierlicher Regelkreis aus Anforderung, technischer Kontrolle, Evidenz, Ausnahme und Remediation. Ein grünes Dashboard beweist nicht automatisch vollständige regulatorische Konformität, weil organisatorische und Microsoft-verantwortete Controls außerhalb einzelner Ressourcen liegen können. Nachweise benötigen Owner und prüfbare Historie.',why:'Ohne verständliche Compliance-Daten lassen sich Abweichungen weder priorisieren noch gegenüber Audit und Management erklären.',examples:['Ein Compliance Owner prüft monatlich eine Initiative, weist Non-Compliance an Workload-Teams zu und dokumentiert genehmigte Exemptions.'],merksatz:'Compliance-Status ist Evidenz für Kontrollen, kein pauschales Zertifikat.',sources:['ms-policy-compliance','ms-policy-regulatory','ms-defender-regulatory'],tags:['compliance','reporting','evidence']},
  'azure-0060':{title:'Policy Compliance und regulatorische Security Governance',simple:'Azure Policy und Defender for Cloud zeigen, wie Ressourcen gegenüber technischen und regulatorischen Vorgaben bewertet werden. Abweichungen werden als nicht konform sichtbar und können mit Empfehlungen oder Remediation bearbeitet werden.',technical:'Regulatory-Compliance-Initiatives gruppieren Policy Definitions nach Controls und Verantwortungsbereichen. Defender for Cloud nutzt Azure-Policy-Initiatives für Standards, bewertet verbundene Scopes kontinuierlich und zeigt compliant sowie noncompliant Resources mit Empfehlungen. Das Microsoft Cloud Security Benchmark liefert einen technischen Baseline-Bezug.',architecture:'Security Baselines sollten als versionierte Initiatives mit klarer Scope- und Ausnahmegovernance betrieben werden. Framework-Mappings unterstützen Nachweise, decken aber nicht automatisch Prozesse, Datenklassifikation oder alle Kundenpflichten ab. Security-, Governance- und Workload-Owner müssen Findings gemeinsam priorisieren.',why:'Security Governance verbindet abstrakte Standards mit konkreten, bearbeitbaren Ressourcenkonfigurationen.',examples:['Eine Benchmark-Initiative erkennt öffentlich erreichbare Ressourcen und weist die Behebung dem verantwortlichen Plattform- oder Produktteam zu.'],merksatz:'Policy misst die Konfiguration; Governance sorgt für verantwortete Remediation.',sources:['ms-defender-regulatory','ms-policy-regulatory','ms-security-benchmark'],tags:['regulatory-compliance','security-baseline','policy-compliance']},
  'azure-0277':{title:'Azure Resource Groups',simple:'Eine Resource Group ist ein logischer Container für zusammengehörige Azure-Ressourcen. Sie bildet eine wichtige Grenze für Bereitstellung, Zugriff, Policy, Tags, Locks und gemeinsamen Lebenszyklus.',technical:'Die meisten Azure-Ressourcen gehören genau einer Resource Group innerhalb einer Subscription an. Ressourcen können miteinander kommunizieren, obwohl sie in unterschiedlichen Gruppen liegen, und viele Ressourcentypen lassen sich zwischen Gruppen verschieben. Beim Löschen einer Resource Group orchestriert Resource Manager auch die Löschung ihrer enthaltenen Ressourcen.',architecture:'Ressourcen sollten nach gemeinsamem Lifecycle, Ownership und Verwaltungsbedarf gruppiert werden, nicht allein nach Ressourcentyp. Eine zu große Gruppe erhöht Ausfallradius und unklare Verantwortung; zu viele kleine Gruppen erzeugen Verwaltungsaufwand. Shared Services mit anderem Lifecycle gehören häufig in getrennte Gruppen.',why:'Resource Groups sind zugleich Lebenszyklus- und Governancegrenzen; eine falsche Gruppierung erschwert Delegation, Deployment und sichere Löschung.',examples:['Web-App und zugehörige Komponenten liegen in einer Produkt-Resource-Group, ein zentraler Log-Analytics-Workspace in einer getrennten Plattformgruppe.'],merksatz:'Gemeinsamer Lifecycle gehört meist in eine gemeinsame Resource Group.',sources:['ms-arm-overview'],tags:['resource-group','scope','lifecycle']},
  'azure-0284':{title:'Azure Resource Manager (ARM)',simple:'Azure Resource Manager ist die zentrale Bereitstellungs- und Verwaltungsschicht für Azure-Ressourcen. Portal, Befehlszeile, SDKs und Templates verwenden diese einheitliche Control Plane.',technical:'Resource Manager authentifiziert und autorisiert Managementanfragen, leitet sie an Resource Provider weiter und verwaltet Scopes, Deployments sowie Abhängigkeiten. Managementfunktionen wie RBAC, Policy, Tags und Locks wirken über diese Ebene. ARM Templates und Bicep beschreiben deklarative Zielzustände für verschiedene Scopes.',architecture:'ARM ist die gemeinsame Governance-Enforcement- und Automatisierungsgrenze, nicht der Datenpfad der Anwendung. Architekturstandards sollten über Infrastructure as Code, Policy und kontrollierte Rollen reproduzierbar an ARM angebunden werden. Direkte Portaländerungen ohne Code und Review erzeugen Drift, obwohl sie dieselbe API verwenden.',why:'Wer ARM als Control Plane versteht, kann Deployment, Zugriff und Governance als zusammenhängendes System entwerfen.',examples:['Eine CI/CD-Pipeline authentifiziert sich mit Workload Identity und stellt eine geprüfte Bicep-Vorlage über ARM bereit.'],merksatz:'ARM ist die Azure-Control-Plane für Bereitstellung und Governance.',sources:['ms-arm-overview'],tags:['azure-resource-manager','control-plane','iac']},
  'azure-0933':{title:'Microsoft Defender for Cloud',simple:'Microsoft Defender for Cloud bewertet die Sicherheitslage von Cloud-Ressourcen und zeigt Risiken, Empfehlungen und Compliance-Ergebnisse. Je nach aktiviertem Plan ergänzt der Dienst außerdem Schutz für laufende Workloads.',technical:'Defender for Cloud verbindet Cloud Security Posture Management mit Workload Protection für Azure, Hybrid- und Multicloudressourcen. Es inventarisiert Assets, bewertet Konfigurationen, priorisiert Empfehlungen und ordnet Findings unterstützten Standards zu. Regulatory Compliance basiert auf zugewiesenen Azure-Policy-Initiatives und scopespezifischer Bewertung.',architecture:'Defender for Cloud ist eine zentrale Security-Governance-Sicht, aber keine automatische Risikobehebung. Scope-Onboarding, Pläne, Policy Assignments, Exemptions, Datenquellen, Kosten und Alert-Ownership müssen bewusst betrieben werden. Governance-Teams definieren Standards; Workload- und Security-Teams beheben Findings nach Risiko.',why:'Eine gemeinsame Posture-Sicht macht verteilte Fehlkonfigurationen und Sicherheitsverantwortung über viele Subscriptions sichtbar.',examples:['Das Cloud-Security-Team priorisiert subscriptionübergreifend exponierte Ressourcen und weist Empfehlungen den jeweiligen Workload-Ownern zu.'],merksatz:'Defender for Cloud findet und priorisiert Cloudrisiken; Owner müssen handeln.',sources:['ms-defender-posture','ms-defender-regulatory','ms-defender-overview'],tags:['defender-for-cloud','cspm','security-governance']},
  'azure-0936':{title:'Security Posture und Compliance Monitoring',simple:'Security-Posture-Monitoring prüft Cloud-Ressourcen fortlaufend auf Sicherheitsrisiken und Abweichungen. Compliance-Ansichten ordnen diese Ergebnisse Standards und Controls zu.',technical:'Defender for Cloud aggregiert Assessed Resources, Recommendations, Secure Score und Regulatory-Compliance-Ergebnisse über ausgewählte Scopes. Findings entstehen aus Ressourcenkonfiguration, aktivierten Plänen und Policy-basierten Standards. Filter und Reports unterstützen Priorisierung, Trendanalyse und Zuweisung.',architecture:'Posture-Werte sind Steuerungssignale, keine vollständige Risikomessung. Teams brauchen Risikokriterien, Service Owner, SLAs für Findings, Ausnahmeablauf und Nachweis der Behebung. Globale Dashboards ohne lokale Verantwortung bleiben reine Beobachtung.',why:'Kontinuierliche Sichtbarkeit verkürzt die Zeit zwischen sicherheitsrelevanter Drift und verantworteter Korrektur.',examples:['Ein monatliches Review verfolgt Secure-Score-Trends, überfällige High-Severity-Empfehlungen und auslaufende Exemptions pro Subscription.'],merksatz:'Posture Monitoring zeigt Drift; Governance macht daraus Entscheidungen und Maßnahmen.',sources:['ms-defender-posture','ms-defender-regulatory'],tags:['security-posture','compliance-monitoring','secure-score']},
  'azure-0961':{title:'Azure Governance-Methoden',simple:'Azure-Governance-Methoden kombinieren Organisation, Zugriff, Policy, Schutz und Kostensteuerung zu einem gemeinsamen Betriebsmodell. Sie helfen Unternehmen, viele Ressourcen und Teams konsistent zu führen.',technical:'Management Groups und Subscriptions strukturieren Scopes; Azure RBAC autorisiert Managementaktionen; Azure Policy bewertet Konfigurationen; Locks schützen vor Änderung; Tags klassifizieren Ressourcen; Cost Management und Defender for Cloud liefern Steuerungsdaten. Azure Resource Manager verbindet diese Mechanismen in der Control Plane.',architecture:'Die Methoden sollten als Plattformprodukt mit versionierten Guardrails, Delegationsmodell, Ausnahmeprozess und messbaren Ergebnissen betrieben werden. Ein Tool allein löst keine Governance: Hierarchie, Ownership und Betriebsrhythmus bestimmen den Nutzen. Standards müssen mit Cloudreife und Risikoprofil wachsen.',why:'Die einzelnen Dienste entfalten erst als abgestimmtes Governance-System ihren Enterprise-Mehrwert.',examples:['Ein Cloud Platform Team veröffentlicht ein Baseline-Paket aus Management-Group-Struktur, Policies, Rollen, Tags, Budgets und Security-Reporting.'],merksatz:'Governance ist ein System aus Scopes, Kontrollen, Daten und Verantwortung.',sources:['ms-governance-overview','ms-management-group-design','ms-arm-overview'],tags:['governance-methodology','operating-model','platform']},
  'azure-0962':{title:'Azure Policy',simple:'Azure Policy bewertet Azure-Ressourcen gegen organisatorische Regeln und kann unerwünschte Konfigurationen melden, blockieren oder korrigieren. Der Dienst wird verwendet, um Standards und Compliance über viele Scopes konsistent umzusetzen.',technical:'Policy Definitions beschreiben Bedingungen und Effects; Policy Assignments binden Definitionen oder Initiatives an Management Groups, Subscriptions, Resource Groups oder Ressourcen. Policy Insights erzeugt Compliance States für anwendbare Ressourcen. Exclusions, Exemptions, Parameter und Enforcement Mode steuern die konkrete Anwendung.',architecture:'Policy ergänzt RBAC: RBAC entscheidet, wer Managementaktionen ausführen darf, Policy bewertet, was als Ressourcenzustand zulässig ist. Breite Assignments benötigen gestufte Einführung, versionierten Policy-as-Code-Workflow und klare Exemption-Governance. Nicht jeder Security- oder Anwendungskontrollpunkt ist über Resource-Manager-Eigenschaften prüfbar.',why:'Policy verwandelt wiederkehrende Architekturanforderungen in skalierbare, nachweisbare Guardrails.',examples:['Eine Subscription-Policy blockiert nicht freigegebene Regionen und meldet bestehende Ressourcen außerhalb der Vorgabe.'],merksatz:'RBAC kontrolliert Akteure; Policy kontrolliert Ressourcenzustände.',sources:['ms-policy-overview','ms-policy-definitions','ms-policy-assignments','ms-policy-compliance'],tags:['azure-policy','resource-governance','compliance']},
  'azure-0963':{title:'Policy-Durchsetzung für Naming, Regionen und Compliance',simple:'Azure Policy kann Vorgaben wie erlaubte Regionen, erforderliche Tags und ausgewählte Sicherheitskonfigurationen prüfen. Je nach Regel meldet oder verhindert Azure eine Abweichung.',technical:'Eine Definition vergleicht Ressourceneigenschaften über Aliases mit einer Bedingung und führt einen Effect aus. Das Assignment bestimmt Scope, Parameter, Ausschlüsse und Enforcement Mode. Naming lässt sich nur soweit prüfen, wie Ressourcentyp, Namensregeln und Policy-Aliases dies unterstützen; Tags können häufig geprüft oder ergänzt werden.',architecture:'Nicht jede Konvention sollte mit `deny` erzwungen werden. Unveränderliche Ressourcennamen benötigen frühe Validierung in IaC und CI/CD, während Policy breite, ressourcenseitig sichtbare Mindestregeln absichert. Audit-first-Rollout und Ausnahmeprozess verhindern, dass neue Standards bestehende Umgebungen unkontrolliert blockieren.',why:'Durchsetzung verbindet dokumentierte Standards mit dem tatsächlichen Deploymentpfad.',examples:['Eine Policy verlangt den Tag `Environment`, während die Pipeline zusätzlich den detaillierten Namensstandard vor dem Deployment testet.'],merksatz:'Policy erzwingt prüfbare Ressourceneigenschaften; CI/CD prüft den restlichen Standard.',sources:['ms-policy-definitions','ms-policy-effects','ms-resource-naming','ms-resource-tags'],tags:['policy-enforcement','naming','allowed-locations']},
  'azure-0970':{title:'Azure Resource Locks',simple:'Resource Locks schützen Azure-Ressourcen vor versehentlicher Löschung oder Änderung. Sie können auf Subscription, Resource Group oder Ressource gesetzt und nach unten vererbt werden.',technical:'`CanNotDelete` erlaubt Lesen und Ändern, verhindert aber Löschen; `ReadOnly` blockiert auch Änderungen über die Resource-Manager-Control-Plane. Locks wirken unabhängig von regulären Benutzerberechtigungen, bis ein berechtigter Akteur den Lock entfernt. Datenebenenoperationen sind je nach Dienst nicht identisch betroffen.',architecture:'Locks eignen sich für kritische Shared Services und Ressourcen mit hohem Löschrisiko, ersetzen aber weder RBAC noch Backup. ReadOnly kann Betriebsaktionen unerwartet blockieren und muss mit Deployment- und Incident-Prozessen getestet werden. Die Berechtigung zum Entfernen von Locks ist eine eigene privilegierte Kontrolle.',why:'Auch korrekt berechtigte Administratoren können kritische Ressourcen versehentlich löschen oder verändern.',examples:['Ein CanNotDelete-Lock schützt den zentralen Log-Analytics-Workspace, während reguläre Konfigurationsänderungen weiter möglich bleiben.'],merksatz:'RBAC erlaubt Aktionen; ein Lock kann erlaubte Aktionen zusätzlich blockieren.',sources:['ms-resource-locks'],tags:['resource-lock','delete-protection','control-plane']},
  'azure-0980':{title:'Azure Resource Tags',simple:'Tags sind Schlüssel-Wert-Paare, die Azure-Ressourcen, Resource Groups und Subscriptions klassifizieren. Sie helfen bei Suche, Kostenanalyse, Automatisierung und Zuordnung zu Verantwortlichen.',technical:'Tags werden als Resource-Manager-Metadaten gespeichert und unterstützen beispielsweise `Environment=Production` oder `CostCenter=4711`. Sie werden nicht automatisch von Resource Groups an Ressourcen vererbt; Cost Management kann eigene Tag-Vererbung für Kostendaten aktivieren. Azure Policy kann erforderliche Tags prüfen oder ergänzen.',architecture:'Eine Tagging-Taxonomie braucht wenige verpflichtende Schlüssel, definierte Werte, Owner und einen Lifecycle. Tags sind kein Sicherheitsmechanismus und dürfen keine sensiblen Daten enthalten. Zu viele freie Werte verschlechtern Kostenberichte und Automatisierung; Namen und Hierarchie bleiben ergänzende Organisationsmittel.',why:'Ohne konsistente Metadaten lassen sich Ressourcen und Kosten in großen Umgebungen kaum zuverlässig zuordnen.',examples:['Alle Ressourcen tragen `Application`, `Environment`, `Owner` und `CostCenter`; Policy meldet fehlende Pflicht-Tags.'],merksatz:'Tags klassifizieren Ressourcen, sie autorisieren keinen Zugriff.',sources:['ms-resource-tags','ms-resource-tagging-strategy'],tags:['azure-tags','metadata','classification']},
  'azure-0981':{title:'Tags für Klassifikation, Kostenanalyse und Filterung',simple:'Ein konsistentes Tagging macht Ressourcen nach Anwendung, Umgebung, Owner oder Kostenstelle filterbar. Dieselben Metadaten können Cost Management und Automatisierung für Berichte und Aktionen verwenden.',technical:'Cost Analysis gruppiert unterstützte Kostendaten nach Tag-Schlüsseln und -Werten. Resource Graph und Management APIs können Ressourcen anhand von Tags abfragen; Automation kann diese Ergebnisse verarbeiten. Fehlende, verspätete oder inkonsistente Tags führen zu nicht zuordenbaren Kosten und unvollständigen Ansichten.',architecture:'Tags ergänzen Managementhierarchie, ersetzen sie aber nicht. Finanzielle Zuordnung sollte auf stabilen Scopes basieren und Tags für feinere Dimensionen nutzen. Tag-Vererbung in Cost Management betrifft Kostendatensätze und ist von der tatsächlichen Ressourcentag-Vererbung zu unterscheiden.',why:'Tagqualität bestimmt unmittelbar, wie präzise Kosten, Ownership und Inventar ausgewertet werden können.',examples:['Cost Analysis gruppiert die Monatskosten nach `CostCenter`, während Resource Graph alle produktiven Ressourcen ohne `Owner` findet.'],merksatz:'Schlechte Tagdaten ergeben schlechte Governance-Berichte.',sources:['ms-resource-tags','ms-cost-management','ms-cost-analysis'],tags:['tagging','cost-allocation','resource-graph']},
  'azure-1011':{title:'Azure Subscriptions',simple:'Eine Azure Subscription ist ein Verwaltungs- und häufig auch Abrechnungsscope für Azure-Ressourcen. Sie enthält Resource Groups und bildet eine zentrale Grenze für Zugriff, Policy, Kosten, Quotas und Verantwortlichkeit.',technical:'Eine Subscription ist einem Microsoft-Entra-Tenant zugeordnet und besitzt eine eindeutige Subscription-ID. Azure RBAC, Azure Policy, Budgets und viele Servicequotas können auf Subscription-Ebene gelten. Management Groups ordnen mehrere Subscriptions in eine übergeordnete Governancehierarchie ein.',architecture:'Subscriptions sind Skalierungs-, Delegations-, Kosten- und Risikogrenzen. Unternehmen trennen häufig Produktion, Nichtproduktion, Plattformen oder regulierte Workloads, wenn unterschiedliche Policies, Owner, Netzwerke oder Abrechnungsanforderungen bestehen. Zu wenige Subscriptions vergrößern Blast Radius; zu viele erhöhen Plattform- und Betriebsaufwand.',why:'Die Subscription-Struktur bestimmt, wie sauber Verantwortlichkeit, Isolation und Governance über viele Workloads skaliert.',examples:['Ein Produkt erhält getrennte Produktions- und Nichtproduktions-Subscriptions mit unterschiedlichen Policies, Budgets und Zugriffsgruppen.'],merksatz:'Subscription ist eine zentrale Governance-, Quota- und Kostengrenze.',sources:['ms-subscription-design','ms-arm-overview','ms-management-groups'],tags:['subscription','scope','resource-organization']},
  'azure-1022':{title:'Azure Management Groups',simple:'Management Groups ordnen mehrere Azure-Subscriptions in einer Hierarchie. Richtlinien und Zugriffszuweisungen an einer Management Group können auf die darunterliegenden Subscriptions vererbt werden.',technical:'Management Groups bilden einen Azure-Resource-Manager-Scope oberhalb von Subscriptions und sind an einen Microsoft-Entra-Tenant gebunden. Jede Subscription hat in der Hierarchie genau einen direkten Management-Group-Elternknoten. Azure Policy und Azure RBAC können auf diesem Scope zugewiesen werden.',architecture:'Die Hierarchie sollte gemeinsame Governanceanforderungen wie Security, Konnektivität, Compliance und Workloadtyp abbilden. Sie sollte stabil bleiben und nicht jede organisatorische Umstrukturierung nachziehen. Root-Zuweisungen sind besonders weitreichend und sollten auf wenige unverzichtbare Kontrollen begrenzt werden.',why:'Management Groups ermöglichen einheitliche Governance, ohne jede Subscription einzeln konfigurieren zu müssen.',examples:['Produktions-Subscriptions liegen unter einer Management Group mit strikten Security-Policies, Sandbox-Subscriptions unter einer flexibleren Gruppe.'],merksatz:'Management Groups skalieren Policy und RBAC über Subscriptions.',sources:['ms-management-groups','ms-management-group-design'],tags:['management-group','hierarchy','inheritance']},
  'azure-1023':{title:'Ressourcenorganisation mit Management Groups',simple:'Management Groups strukturieren Subscriptions nach gemeinsamen Governanceanforderungen. Dadurch können unterschiedliche Workloadtypen passende Regeln erhalten, ohne jedes Konto einzeln zu verwalten.',technical:'Subscriptions werden als Kinder in eine baumförmige Hierarchie eingeordnet und erben unterstützte Policy- und RBAC-Zuweisungen von übergeordneten Management Groups. Verschiebungen verändern den geerbten Governancekontext. Die Hierarchie liegt innerhalb eines Microsoft-Entra-Tenants.',architecture:'Geeignete Trennkriterien sind Plattformfunktion, Internetexposition, regulatorische Anforderungen, Datenresidenz oder Sandboxstatus. Eine direkte Abbildung von Abteilungen führt häufig zu instabiler Struktur und unnötigen Policy-Duplikaten. Änderungen benötigen Impactanalyse, weil geerbte Controls und Zugriffe wechseln können.',why:'Eine gute Hierarchie reduziert doppelte Assignments und macht Governancewirkungen vorhersehbar.',examples:['Connectivity-, Identity- und Management-Subscriptions liegen in einer Platform-Gruppe; Geschäftsanwendungen in Corp oder Online.'],merksatz:'Gruppiere Subscriptions nach Governancebedarf, nicht automatisch nach Organigramm.',sources:['ms-management-group-design','ms-management-groups'],tags:['resource-organization','management-group','landing-zone']},
  'azure-1025':{title:'Azure-Kosten planen und steuern',simple:'Kostenplanung schätzt erwartete Cloudausgaben und vergleicht sie später mit der tatsächlichen Nutzung. Kostensteuerung ergänzt diese Planung durch Budgets, Analyse, Zuordnung und Optimierungsmaßnahmen.',technical:'Pricing Calculator und TCO-Betrachtung unterstützen Vorabschätzungen; Cost Management verarbeitet bewertete Nutzungs- und Kaufdaten nach verfügbaren Scopes. Cost Analysis, Budgets, Alerts, Exports und Tags liefern Betriebsdaten. Abrechnungsdaten sind nicht in jedem Fall Echtzeit- oder identisch mit der finalen Rechnung.',architecture:'Planwerte müssen Annahmen zu Last, Skalierung, Verfügbarkeit, Datenverkehr und Betriebsmodell dokumentieren. Nach dem Deployment braucht jede Kostenstelle einen Owner und wiederkehrende Abweichungsanalyse. Optimierung darf Service-Level-, Resilienz- und Wachstumsanforderungen nicht isoliert ignorieren.',why:'Cloudkosten verändern sich mit Architektur und Nutzung; eine einmalige Kalkulation reicht nicht für den laufenden Betrieb.',examples:['Vor dem Launch wird ein Lastszenario kalkuliert; danach vergleicht das Team monatlich Forecast, Istkosten und Stückkosten pro Transaktion.'],merksatz:'Schätzen vor dem Deployment, messen und steuern im Betrieb.',sources:['ms-cost-plan','ms-cost-management','ms-cost-analysis'],tags:['cost-planning','cost-governance','finops']},
  'azure-1030':{title:'Nutzungsmessung und Kostenentstehung',simple:'Azure-Dienste messen ihre Nutzung in dienstspezifischen Einheiten wie Rechenzeit, Speicher oder übertragenen Daten. Diese Messwerte werden mit Preisen und Vertragsbedingungen zu Kostendatensätzen verarbeitet.',technical:'Ressourcennutzung und Käufe fließen mit unterschiedlicher Aktualität in die Commerce-Datenpipeline. Rating wendet Preise, Rabatte und Mengenmodelle an und erzeugt bewertete Nutzung für Cost Management. Messmenge, Preisberechnung und finale Rechnung können unterschiedliche Zeitpunkte und Einheiten besitzen.',architecture:'Kostenmodelle müssen die tatsächlich dominierenden Meter eines Designs berücksichtigen, etwa Compute-Laufzeit, Datentransfer, IOPS oder Log-Ingestion. Architekten sollten Unit Economics und Kostentreiber früh definieren und nach Lasttests validieren. Ein niedriger Ressourcenpreis kann durch hohen Verbrauch oder Nebenmeter überkompensiert werden.',why:'Nur wer den relevanten Meter versteht, kann Kostenwirkung einer Architekturänderung erklären.',examples:['Ein Loggingdesign wird nicht nur nach Workspace-Preis, sondern nach täglicher Ingestion, Aufbewahrung und Abfragevolumen bewertet.'],merksatz:'Preis mal gemessene Nutzung ergibt Kostenwirkung – nicht der Listenpreis allein.',sources:['ms-cost-management'],tags:['usage-meter','cost-driver','unit-economics']},
  'azure-1034':{title:'Microsoft Cost Management',simple:'Microsoft Cost Management hilft, Cloudkosten zu analysieren, zu überwachen und zu optimieren. Teams können Kosten nach Scopes und Metadaten untersuchen, Budgets setzen und Daten exportieren.',technical:'Cost Management verarbeitet bewertete Kosten- und Nutzungsdaten und stellt Cost Analysis, Budgets, Alerts, Exports, Cost Details API, Anomalieerkennung und Optimierungshinweise bereit. Berechtigungen und verfügbare Funktionen hängen vom Abrechnungs- und Ressourcenscope ab. Tags und Cost Allocation unterstützen feinere Zuordnung.',architecture:'Cost Management ist die Datengrundlage eines FinOps-Prozesses, aber kein autonomer Kostenoptimierer. Eine skalierbare Lösung verbindet Managementhierarchie, Tagging, Zugriff auf Kostendaten, Budgets, Reports und verantwortete Maßnahmen. Shared Costs und zentrale Plattformen benötigen transparente Allokationsregeln.',why:'Zentrale Kostendaten verbinden technische Nutzung mit finanzieller Verantwortung und Architekturentscheidungen.',examples:['Eine FinOps-Ansicht vergleicht Kosten pro Management Group, Subscription, Service und CostCenter und exportiert Details ins Unternehmensreporting.'],merksatz:'Cost Management liefert Sicht und Signale; Teams treffen und verantworten Maßnahmen.',sources:['ms-cost-management','ms-cost-analysis'],tags:['cost-management','finops','cost-analysis']}
};

const relationDefinitions = [
  ['gov-rel-001','azure-0036','azure-0038','contains','Azure Governance enthält die Managementhierarchie als Scope-Modell für vererbte Kontrollen und Delegation.',['ms-governance-overview','ms-arm-overview'],0.99],
  ['gov-rel-002','azure-0038','azure-1022','contains','Die Governance-Scope-Struktur beginnt oberhalb von Subscriptions mit Azure Management Groups.',['ms-arm-overview','ms-management-groups'],0.99],
  ['gov-rel-003','azure-1022','azure-1011','contains','Management Groups enthalten Subscriptions und übertragen unterstützte Policy- sowie RBAC-Zuweisungen auf untergeordnete Scopes.',['ms-management-groups'],0.99],
  ['gov-rel-004','azure-1011','azure-0277','contains','Eine Azure Subscription enthält Resource Groups als untergeordnete Verwaltungs- und Lebenszyklusscopes.',['ms-arm-overview'],0.99],
  ['gov-rel-005','azure-0277','azure-0322','contains','Eine Azure VM ist eine Resource-Manager-Ressource und gehört typischerweise genau einer Resource Group an.',['ms-arm-overview','ms-vm-overview'],0.99],
  ['gov-rel-006','azure-0277','azure-0442','contains','Ein Virtual Network ist eine Resource-Manager-Ressource innerhalb einer Resource Group.',['ms-arm-overview','ms-vnet-subnets'],0.99],
  ['gov-rel-007','azure-0284','azure-0277','governs','Azure Resource Manager stellt die Control Plane bereit, über die Resource Groups und ihre Ressourcen verwaltet werden.',['ms-arm-overview'],0.99],
  ['gov-rel-008','azure-0964','azure-1022','governs','Azure RBAC-Zuweisungen an einer Management Group autorisieren Managementaktionen auf diesem und geerbten untergeordneten Scopes.',['ms-rbac','ms-management-groups'],0.99],
  ['gov-rel-009','azure-0964','azure-1011','governs','Azure RBAC steuert Managementzugriff auf eine Subscription und ihre untergeordneten Scopes.',['ms-rbac','ms-role-assignments','ms-arm-overview'],0.99],
  ['gov-rel-010','azure-0965','azure-0322','governs','Ein Role Assignment verbindet Security Principal, Role Definition und Scope und kontrolliert dadurch Managementzugriff auf die VM.',['ms-role-assignments','ms-vm-overview'],0.99],
  ['gov-rel-011','azure-0962','azure-0036','part_of','Azure Policy ist ein zentraler technischer Baustein des Azure-Governance-Systems.',['ms-governance-overview','ms-policy-overview'],0.99],
  ['gov-rel-012','azure-0041','azure-0962','part_of','Policy Initiatives bündeln mehrere Policy Definitions innerhalb des Azure-Policy-Systems.',['ms-policy-initiatives','ms-policy-overview'],0.99],
  ['gov-rel-013','azure-0042','azure-0962','part_of','Effects bestimmen die Reaktion einer Azure-Policy-Definition auf erfüllte Bedingungen.',['ms-policy-effects'],0.99],
  ['gov-rel-014','azure-0059','azure-0962','depends_on','Governance-Compliance-Reporting verwendet die durch Policy Assignments erzeugten Compliance States als technische Evidenz.',['ms-policy-compliance'],0.98],
  ['gov-rel-015','azure-0962','azure-1022','governs','Policy Assignments auf Management-Group-Ebene bewerten und steuern Ressourcen in untergeordneten Subscriptions.',['ms-policy-overview','ms-management-groups'],0.99],
  ['gov-rel-016','azure-0962','azure-1011','governs','Ein Policy Assignment auf Subscription-Ebene gilt für anwendbare Ressourcen im Scope und darunter.',['ms-policy-assignments','ms-arm-overview'],0.99],
  ['gov-rel-017','azure-0962','azure-0322','governs','Azure Policy kann VM-Konfigurationen wie erlaubte SKUs, Regionen, Tags oder Diagnostikeinstellungen bewerten und je nach Effect steuern.',['ms-policy-overview','ms-policy-definitions'],0.98],
  ['gov-rel-018','azure-0962','azure-0351','governs','Azure Policy kann Resource-Manager-Eigenschaften von App Service gegen organisatorische Plattformstandards bewerten.',['ms-policy-overview','ms-app-service'],0.98],
  ['gov-rel-019','azure-0962','azure-0425','governs','Azure Policy kann ARM-Eigenschaften und unterstützte Kubernetes-Konfigurationen eines AKS-Umfelds gegen Standards bewerten.',['ms-policy-overview','ms-aks-overview'],0.97],
  ['gov-rel-020','azure-0962','azure-0442','governs','Azure Policy kann Netzwerkressourcen wie VNets anhand unterstützter Eigenschaften, Regionen, Tags und Sicherheitsanforderungen bewerten.',['ms-policy-overview','ms-vnet-subnets'],0.98],
  ['gov-rel-021','azure-0962','azure-0864','governs','Azure Policy kann unterstützte NSG-Konfigurationen und zugehörige Sicherheitsanforderungen im Resource-Manager-Scope bewerten.',['ms-policy-overview','ms-nsg-asg'],0.98],
  ['gov-rel-022','azure-0047','azure-0442','organizes','Eine Naming Convention strukturiert Netzwerkressourcen mit konsistenten Bestandteilen für Typ, Workload, Umgebung, Region und Instanz.',['ms-resource-naming'],0.98],
  ['gov-rel-023','azure-0980','azure-0322','organizes','Tags klassifizieren VMs nach Metadaten wie Anwendung, Umgebung, Owner und Kostenstelle.',['ms-resource-tags'],0.99],
  ['gov-rel-024','azure-0980','azure-0442','organizes','Tags klassifizieren Netzwerkressourcen für Inventar, Ownership, Automatisierung und Kostenanalyse.',['ms-resource-tags','ms-resource-tagging-strategy'],0.99],
  ['gov-rel-025','azure-1034','azure-0980','uses','Cost Management verwendet verfügbare Tags, um Kosten feiner zu gruppieren und zuzuordnen.',['ms-cost-management','ms-resource-tags'],0.99],
  ['gov-rel-026','azure-0033','azure-1011','monitors','Ein Budget überwacht tatsächliche oder prognostizierte Kosten einer Subscription und erzeugt Warnungen an definierten Schwellen.',['ms-cost-plan','ms-cost-management'],0.99],
  ['gov-rel-027','azure-1034','azure-1011','monitors','Cost Management analysiert und überwacht Kosten und Nutzung innerhalb des Subscription-Scopes.',['ms-cost-management'],0.99],
  ['gov-rel-028','azure-1034','azure-0277','monitors','Cost Management kann Kosten auf Resource-Group-Ebene anzeigen und verantwortlichen Teams zuordnen.',['ms-cost-management'],0.99],
  ['gov-rel-029','azure-1030','azure-1034','part_of','Bewertete Nutzungs- und Kaufdaten bilden die Datengrundlage für Cost Management.',['ms-cost-management'],0.99],
  ['gov-rel-030','azure-0933','azure-0060','monitors','Defender for Cloud bewertet verbundene Scopes gegen zugewiesene Regulatory-Compliance-Standards und zeigt Findings sowie Empfehlungen.',['ms-defender-regulatory','ms-defender-posture'],0.99],
  ['gov-rel-031','azure-0933','azure-0962','integrates_with','Defender for Cloud verwendet Azure-Policy-Initiatives zur Zuweisung und Bewertung unterstützter regulatorischer Standards.',['ms-defender-regulatory','ms-policy-regulatory'],0.99],
  ['gov-rel-032','azure-0962','azure-0831','governs','Azure Policy kann technische Security-Baseline-Anforderungen für Compute-Ressourcen prüfen und je nach Effect durchsetzen oder melden.',['ms-security-benchmark','ms-policy-overview'],0.98],
  ['gov-rel-033','azure-0970','azure-0277','secures','Ein Resource Lock auf einer Resource Group schützt ihren Managementscope vor versehentlicher Löschung oder Änderung und wird auf Ressourcen vererbt.',['ms-resource-locks'],0.99],
  ['gov-rel-034','azure-0057','azure-1034','uses','Kostensteuerung verwendet Cost Management als Daten- und Werkzeugbasis für Analyse, Budgets, Alerts und Optimierung.',['ms-cost-management','ms-cost-plan'],0.99]
];

for (const source of officialSources) {
  const index = sourcesDocument.sources.findIndex(item => item.id === source.id);
  if (index >= 0) sourcesDocument.sources[index] = source;
  else sourcesDocument.sources.push(source);
}
for (const type of extraRelationTypes) {
  const index = typesDocument.relation_types.findIndex(item => item.id === type.id);
  if (index >= 0) typesDocument.relation_types[index] = type;
  else typesDocument.relation_types.push(type);
}
const typeById = new Map(typesDocument.relation_types.map(type => [type.id, type]));

for (const [id, enrichment] of Object.entries(E)) {
  const node = nodeById.get(id);
  if (!node) throw new Error(`Pilotknoten fehlt: ${id}`);
  if (node.metadata?.enrichment) throw new Error(`${id}: Bereits in V${node.metadata.enrichment.version} angereichert und gegen Überschreiben geschützt.`);
  const originalTitle = node.title;
  node.title = enrichment.title || node.title;
  node.description = {simple:enrichment.simple,technical:enrichment.technical,architecture:enrichment.architecture};
  node.why_important = enrichment.why;
  node.examples = enrichment.examples || [];
  node.merksatz = enrichment.merksatz || '';
  node.analogy = enrichment.analogy || '';
  node.sources = [...new Set([...(node.sources || []), ...enrichment.sources])];
  node.tags = [...new Set([...(node.tags || []), ...(enrichment.tags || []), 'governance-pilot-v1.5'])];
  node.aliases = [...new Set([...(node.aliases || []), ...(originalTitle !== node.title ? [originalTitle] : [])])];
  node.metadata = {...node.metadata,status:'published',audit_flags:(node.metadata.audit_flags || []).filter(flag => flag !== 'description_generated_from_title'),enrichment:{version:'1.5',pilot:'governance-management',content_standard:'1.0',reviewed_at:today,source_policy:'official_microsoft_only'}};
  node.updated_at = today;
}

const pilotRelationIds = new Set(relationDefinitions.map(([id]) => id));
relationsDocument.relations = relationsDocument.relations.filter(relation => !pilotRelationIds.has(relation.id));
for (const node of nodesDocument.nodes) node.relations = (node.relations || []).filter(id => !pilotRelationIds.has(id));
for (const [id, source, target, type, explanation, sources, confidence] of relationDefinitions) {
  if (!nodeById.has(source) || !nodeById.has(target)) throw new Error(`${id}: Endpunkt fehlt`);
  const typeDefinition = typeById.get(type);
  if (!typeDefinition) throw new Error(`${id}: Typ ${type} fehlt`);
  const relation = {schema_version:'1.1',id,source,target,type,inverse_type:typeDefinition.inverse_type,explanation,sources,confidence,status:'accepted',created_by:'knowledge_enrichment_v1.5',created_at:today,reviewed_at:today};
  relationsDocument.relations.push(relation);
  for (const nodeId of [source,target]) {
    const node = nodeById.get(nodeId);
    node.relations = [...new Set([...(node.relations || []), id])];
  }
}

nodesDocument.meta = {...nodesDocument.meta,enrichment_version:'1.5',governance_pilot:{node_count:Object.keys(E).length,relation_count:relationDefinitions.length,content_standard:'1.0',reviewed_at:today,focus:'enterprise_control_and_standardization'}};
relationsDocument.meta = {...relationsDocument.meta,relation_count:relationsDocument.relations.length,enrichment_version:'1.5',governance_relation_count:relationDefinitions.length};
sourcesDocument.meta = {...sourcesDocument.meta,count:sourcesDocument.sources.length,generated_at:today,enrichment_version:'1.5'};
typesDocument.meta = {...typesDocument.meta,type_count:typesDocument.relation_types.length,updated_at:today,enrichment_version:'1.5'};

write('nodes.json',nodesDocument);
write('relations.json',relationsDocument);
write('sources.json',sourcesDocument);
write('relation-types.json',typesDocument);

console.log(JSON.stringify({enriched_nodes:Object.keys(E).length,added_relations:relationDefinitions.length,total_relations:relationsDocument.relations.length,added_relation_types:extraRelationTypes.length,total_relation_types:typesDocument.relation_types.length,added_sources:officialSources.length,total_sources:sourcesDocument.sources.length},null,2));
