import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonical = path.join(project, 'data/canonical');
const today = '2026-08-11';
const read = name => JSON.parse(fs.readFileSync(path.join(canonical, name), 'utf8'));
const write = (name, value) => fs.writeFileSync(path.join(canonical, name), `${JSON.stringify(value, null, 2)}\n`);

const nodesDocument = read('nodes.json');
const relationsDocument = read('relations.json');
const sourcesDocument = read('sources.json');
const typesDocument = read('relation-types.json');
const nodeById = new Map(nodesDocument.nodes.map(node => [node.id, node]));

const officialSources = [
  {id:'ms-shared-responsibility',title:'Shared responsibility in the cloud',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/shared-responsibility',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-security-overview',title:'Introduction to Azure security',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-security-pillar',title:'Azure Well-Architected Framework – Security pillar',url:'https://learn.microsoft.com/en-us/azure/well-architected/security/',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-security-design-patterns',title:'Architecture design patterns that support security',url:'https://learn.microsoft.com/en-us/azure/well-architected/security/design-patterns',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-zero-trust-infrastructure',title:'Secure infrastructure with Zero Trust',url:'https://learn.microsoft.com/en-us/security/zero-trust/deploy/infrastructure',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-azure-infrastructure-security',title:'Azure infrastructure security',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/infrastructure',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-azure-physical-security',title:'Physical security of Azure datacenters',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/physical-security',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-networking-overview',title:'Azure networking services overview',url:'https://learn.microsoft.com/en-us/azure/networking/networking-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-keyvault-concepts',title:'Azure Key Vault basic concepts',url:'https://learn.microsoft.com/en-us/azure/key-vault/general/basic-concepts',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-keyvault-objects',title:'Azure Key Vault keys, secrets, and certificates overview',url:'https://learn.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-keyvault-security',title:'Secure your Azure Key Vault',url:'https://learn.microsoft.com/en-us/azure/key-vault/general/secure-key-vault',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-key-management-choice',title:'Choose the right Azure key management solution',url:'https://learn.microsoft.com/en-us/azure/security/fundamentals/key-management-choose',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-secure-score',title:'Secure score in Microsoft Defender for Cloud',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/secure-score-security-controls',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-recommendations',title:'Security recommendations in Microsoft Defender for Cloud',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/security-recommendations',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-defender-vulnerability',title:'Enable vulnerability scanning with Microsoft Defender Vulnerability Management',url:'https://learn.microsoft.com/en-us/azure/defender-for-cloud/deploy-vulnerability-assessment-defender-vulnerability-management',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-backup-security',title:'Azure Backup security best practices for data protection',url:'https://learn.microsoft.com/en-us/azure/backup/azure-backup-data-protection-best-practices',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-backup-immutable',title:'Manage Azure Backup Immutable vault operations',url:'https://learn.microsoft.com/en-us/azure/backup/backup-azure-immutable-vault-how-to-manage',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-recovery-services-vault',title:'Create and configure a Recovery Services vault',url:'https://learn.microsoft.com/en-us/azure/backup/backup-create-recovery-services-vault',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-bcdr-concepts',title:'Business continuity, high availability, and disaster recovery',url:'https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery',publisher:'Microsoft Learn',accessed_at:today,type:'official'}
];

const E = {
  'azure-0070':{title:'Reliability und Security',simple:'Reliability hält einen Dienst trotz Fehlern verfügbar, Security schützt ihn vor unbefugtem Zugriff, Veränderung und Ausfall. Beide Disziplinen sichern den Geschäftsbetrieb, behandeln aber unterschiedliche Ursachen. Gute Cloud-Architektur plant sie gemeinsam.',technical:'Reliability verwendet Redundanz, Health Monitoring, Failover, Backup und Recovery. Security kombiniert Identitätskontrollen, Segmentierung, Verschlüsselung, Schwachstellenmanagement, Erkennung und Reaktion. Ein Security Incident kann zugleich ein Availability- oder Recovery-Ereignis werden, etwa bei Ransomware oder DDoS.',architecture:'Architekten übersetzen Geschäftsrisiken in messbare Anforderungen für Verfügbarkeit, RPO/RTO, Vertraulichkeit, Integrität und Wiederherstellbarkeit. Controls dürfen nicht isoliert optimiert werden: zusätzliche Inspection kann Latenz oder Fehlerrisiko erhöhen, während hohe Verfügbarkeit ohne geschützte Administration Angreifern robuste Infrastruktur bereitstellt. Entscheidungen benötigen Owner, Telemetrie und getestete Runbooks.',why:'Ein Dienst ist nicht erfolgreich, wenn er zwar läuft, aber kompromittiert ist, oder sicher konfiguriert ist, aber nicht wiederhergestellt werden kann.',examples:['Ein Zahlungsdienst kombiniert zonenredundante Komponenten, Conditional Access für Administratoren, private Datenpfade und unveränderbare Wiederherstellungspunkte.'],merksatz:'Reliability hält den Dienst am Leben; Security hält ihn vertrauenswürdig.',sources:['ms-security-pillar','ms-bcdr-concepts','ms-shared-responsibility'],tags:['reliability-security','risk-management','business-continuity']},
  'azure-0073':{title:'Security-Ziele: Vertraulichkeit, Integrität und Verfügbarkeit',simple:'Security schützt Informationen davor, von falschen Personen gelesen, unbemerkt verändert oder unbrauchbar gemacht zu werden. Diese Ziele heißen Vertraulichkeit, Integrität und Verfügbarkeit. Eine Architektur muss alle drei passend zum Geschäftsrisiko abdecken.',technical:'Vertraulichkeit entsteht durch Identität, Autorisierung, Segmentierung und Verschlüsselung. Integrität benötigt kontrollierte Änderungen, Signaturen, Versionierung, unveränderbare Logs oder Backups und Nachweisbarkeit. Verfügbarkeit wird durch DDoS-Schutz, resiliente Designs, Recovery und geschützte Betriebszugänge unterstützt.',architecture:'Die Priorität der drei Ziele hängt von Datenklassifikation und Workload ab. Maximale Vertraulichkeit kann Betriebszugriff und Recovery erschweren; maximale Verfügbarkeit kann mehr öffentliche Angriffsfläche erzeugen. Controls müssen daher nach Bedrohungsmodell, regulatorischer Pflicht und akzeptiertem Restrisiko ausgewählt werden.',why:'Ohne explizite Schutzziele wird Security zu einer Liste von Produkten statt zu einer risikobasierten Architektur.',examples:['Für medizinische Daten gelten starke Zugriffskontrollen und Verschlüsselung, manipulationssichere Nachweise sowie ein getesteter Wiederherstellungsweg.'],merksatz:'Security schützt, wer lesen darf, was unverändert bleibt und ob der Dienst nutzbar ist.',sources:['ms-security-pillar','ms-security-overview'],tags:['confidentiality','integrity','availability','security-objectives']},
  'azure-0074':{title:'Azure Security Controls im Zusammenspiel',simple:'Azure schützt Identitäten, Netzwerke, Anwendungen und Daten mit mehreren zusammenwirkenden Kontrollen. Dazu gehören Entra ID, RBAC, PIM, NSGs, Firewall, Private Endpoints, Verschlüsselung, Key Vault, Defender for Cloud, Policy und Backup. Kein einzelner Dienst deckt alle Risiken ab.',technical:'Identity Controls authentifizieren Akteure und autorisieren Aktionen; Network Controls filtern und segmentieren Datenpfade; Workload Controls härten Konfiguration und erkennen Bedrohungen; Data Controls verschlüsseln, versionieren und sichern Informationen. Azure Policy und Defender bewerten den Zustand kontinuierlich. Logs, Alerts und Incident-Prozesse schließen den Regelkreis.',architecture:'Controls werden nach Angriffspfad und Schutzobjekt geschichtet, nicht nach Portalmenü. Zentrale Guardrails schaffen Mindeststandards, workloadnahe Regeln berücksichtigen lokale Anforderungen. Zu viele überlappende Kontrollen erhöhen Komplexität; fehlende Unabhängigkeit erzeugt gemeinsame Ausfall- oder Kompromittierungswege.',why:'Security wird erst wirksam, wenn präventive, detektive und wiederherstellende Kontrollen als System betrieben werden.',examples:['Eine VM besitzt Managed Identity, minimales RBAC, NSG-Regeln, zentralen Firewall-Egress, Defender-Überwachung, verschlüsselte Disks und geschützte Backups.'],merksatz:'Identity entscheidet wer, Netzwerk woher, Workload was läuft und Data was erhalten bleibt.',sources:['ms-security-overview','ms-zero-trust-infrastructure','ms-security-benchmark'],tags:['security-controls','defense-in-depth','security-lifecycle']},
  'azure-0076':{title:'Customer-Managed Keys (CMK)',simple:'Customer-Managed Keys sind Verschlüsselungsschlüssel, deren Lebenszyklus der Kunde kontrolliert. Sie werden typischerweise in Azure Key Vault oder Managed HSM gespeichert. Azure-Dienste können diese Schlüssel zusätzlich zu ihrer standardmäßigen Verschlüsselung verwenden.',technical:'Bei CMK referenziert ein unterstützter Dienst einen Key-Encryption-Key in Key Vault oder Managed HSM und benötigt dafür eine verwaltete Identität sowie Berechtigungen. Rotation, Versionen, Aktivierung, Sperre, Löschschutz und Verfügbarkeit des Schlüssels beeinflussen den Datenzugriff. Microsoft-Managed Keys werden dagegen durch den Dienst ohne kundenseitigen Schlüsselbetrieb verwaltet.',architecture:'CMK ist sinnvoll bei regulatorischer Schlüsselkontrolle, Trennung von Aufgaben oder gefordertem Widerruf. Es erhöht Betriebsverantwortung, Kosten und Abhängigkeiten: falsche Rotation, fehlende Berechtigungen oder gelöschte Schlüssel können Daten unzugänglich machen. Ohne konkrete Anforderung sind Microsoft-Managed Keys oft die robustere Standardwahl.',why:'CMK gibt dem Kunden zusätzliche Kontrolle über Verschlüsselung, überträgt aber zugleich kritische Schlüsselverantwortung.',examples:['Ein regulierter Storage Account verwendet einen CMK aus einem produktionsgetrennten Key Vault mit Purge Protection und überwachten Rotationsprozessen.'],merksatz:'CMK bedeutet mehr Kontrolle und mehr Verantwortung für die Verfügbarkeit des Schlüssels.',sources:['ms-key-management-choice','ms-keyvault-security','ms-storage-encryption'],tags:['cmk','customer-managed-key','key-lifecycle']},
  'azure-0114':{title:'Disaster Recovery (DR)',simple:'Disaster Recovery beschreibt, wie ein Dienst nach einem schweren Ausfall oder Sicherheitsvorfall wieder arbeitsfähig wird. Dazu gehören Wiederherstellung, Failover, Kommunikation und Rückkehr zum Normalbetrieb. Backup allein ist noch kein vollständiger DR-Plan.',technical:'DR kombiniert Recovery Points, Replikation, Failover/Failback, alternative Betriebsumgebungen und dokumentierte Runbooks. RPO begrenzt tolerierbaren Datenverlust, RTO die Wiederanlaufzeit. Recovery muss Identitäten, Schlüssel, Netzwerk, Abhängigkeiten, Datenkonsistenz und Cyber-Recovery nach einer Kompromittierung berücksichtigen.',architecture:'Die Strategie folgt Business Impact und Ausfallszenarien: Restore, Active/Passive oder Active/Active haben unterschiedliche Kosten und Komplexität. Backups sollten getrennt, zugriffsgeschützt, überwacht und möglichst unveränderbar sein. Ein regionaler Failover hilft nicht, wenn kompromittierte Daten oder Identitäten ungeprüft repliziert werden.',why:'Schwere Störungen lassen sich nicht vollständig verhindern; ohne getesteten Wiederanlauf bleibt die tatsächliche Erholbarkeit unbekannt.',examples:['Nach einem Ransomware-Vorfall stellt das Team eine saubere Umgebung aus einem geschützten Recovery Point wieder her und rotiert zuvor privilegierte Zugangsdaten.'],merksatz:'DR ist ein getesteter Geschäftsprozess, nicht nur eine Datenkopie.',sources:['ms-bcdr-concepts','ms-backup-security','ms-site-recovery'],tags:['disaster-recovery','cyber-recovery','rpo-rto']},
  'azure-0115':{title:'Recovery-Planung und Wiederherstellbarkeit',simple:'Recovery-Planung legt fest, welche Systeme in welcher Reihenfolge wiederhergestellt werden. Sie berücksichtigt Daten, Identitäten, Netzwerk und abhängige Dienste. Regelmäßige Tests zeigen, ob der Plan wirklich funktioniert.',technical:'Ein Recovery-Plan definiert Schutzobjekte, Recovery Points, RPO/RTO, Abhängigkeitsreihenfolge, Runbooks, Rollen, Eskalation, Kommunikation und Validierung. Azure Backup verwaltet Wiederherstellungspunkte in Vaults; Site Recovery orchestriert unterstützte Replikations- und Failoverpfade. Restore-Tests sollten isoliert und ohne Beeinträchtigung der Produktion erfolgen.',architecture:'Recovery wird vom kritischen Geschäftsprozess rückwärts entworfen, nicht von verfügbaren Backupjobs vorwärts. Vault-, Identitäts- und Schlüsselgrenzen müssen einen kompromittierten Produktionsadministrator überstehen. Retention, Immutability und Cross-Region-Optionen erhöhen Schutz, aber auch Kosten und Änderungsrestriktionen.',why:'Ein vorhandenes Backup beweist weder, dass alle Abhängigkeiten erfasst sind, noch dass die Wiederherstellung rechtzeitig gelingt.',examples:['Ein Quartalstest stellt Datenbank, Anwendung und DNS in einer isolierten Umgebung wieder her und misst das tatsächliche RPO und RTO.'],merksatz:'Nicht der erfolgreiche Backupjob, sondern der erfolgreiche Restore beweist Wiederherstellbarkeit.',sources:['ms-recovery-services-vault','ms-backup-security','ms-bcdr-concepts'],tags:['recovery-planning','restore-testing','rpo-rto']},
  'azure-0117':{title:'Replikation, Failover und Failback',simple:'Replikation hält eine zusätzliche Kopie eines Systems oder seiner Daten an einem anderen Ort. Failover schaltet bei einem Ausfall auf diese Kopie um. Failback führt den Betrieb kontrolliert zur ursprünglichen oder einer neuen Primärumgebung zurück.',technical:'Replikation kann synchron oder asynchron erfolgen und bestimmt damit Latenz und mögliches Datenverlustfenster. Ein Failover benötigt konsistente Abhängigkeiten, aktualisierte Netzwerkpfade, DNS, Identität, Schlüssel und Validierung; Failback muss neue Änderungen zurückführen. Azure Site Recovery unterstützt ausgewählte VM-Szenarien, Storage- und Datenbankdienste besitzen eigene Mechanismen.',architecture:'Replikation verbessert Recovery-Zeit, schützt aber nicht automatisch vor logischer Beschädigung oder Ransomware, weil Fehler mitkopiert werden können. Für Cyber-Recovery sind unabhängige Recovery Points und saubere Zielumgebungen nötig. Geplante Tests, Runbook-Automatisierung und klare Entscheidungshoheit reduzieren Ausfallzeit.',why:'Ohne geplanten Umschalt- und Rückkehrprozess ist eine zweite Kopie kein verlässlicher DR-Betrieb.',examples:['Eine Anwendung wird testweise in die Sekundärregion umgeschaltet, dort validiert und nach synchronisiertem Failback wieder in der Primärregion betrieben.'],merksatz:'Replikation kopiert Zustand; Failover und Failback machen daraus einen Betriebsprozess.',sources:['ms-bcdr-concepts','ms-site-recovery','ms-storage-disaster-recovery'],tags:['replication','failover','failback']},
  'azure-0815':{title:'Azure Security & Protection Architecture',simple:'Azure Security & Protection verbindet Identitäts-, Netzwerk-, Workload-, Daten- und Recovery-Schutz zu einer durchgängigen Architektur. Ziel ist, Angriffe zu verhindern, früh zu erkennen, ihre Auswirkung zu begrenzen und den Betrieb wiederherzustellen. Security bleibt dabei eine gemeinsame Verantwortung von Microsoft und Kunde.',technical:'Die Architektur kombiniert Entra ID, Conditional Access, MFA, PIM, RBAC, Netzwerksegmentierung, Firewall, DDoS/WAF, Private Link, Key Vault, Verschlüsselung, Defender for Cloud, Policy, Monitoring und Backup. Controls liefern Prävention, Erkennung, Reaktion und Recovery über Management- und Datenebene. Telemetrie und Ownership verbinden Findings mit Remediation.',architecture:'Das Schutzmodell folgt Zero Trust: explizit prüfen, Least Privilege verwenden und Kompromittierung annehmen. Sicherheitsgrenzen werden nach Workload, Umgebung, Datenklassifikation und Blast Radius gestaltet. Zentral verantwortete Baselines und dezentrale Workload-Controls benötigen einen gemeinsamen Ausnahme-, Test- und Incident-Prozess.',why:'Einzelne Sicherheitsprodukte erzeugen erst durch abgestimmte Grenzen, Zuständigkeiten und Reaktionsprozesse belastbaren Schutz.',examples:['Eine Landing Zone erzwingt zentrale Identity- und Policy-Baselines, während Workloadteams eigene App-, Daten- und Recovery-Controls innerhalb dieser Leitplanken betreiben.'],merksatz:'Security ist ein Lebenszyklus aus verhindern, erkennen, reagieren und wiederherstellen.',sources:['ms-security-overview','ms-zero-trust-infrastructure','ms-shared-responsibility'],tags:['security-architecture','zero-trust','protection-lifecycle']},
  'azure-0816':{title:'Network Security Architecture',simple:'Network Security kontrolliert, welche Systeme über welche Pfade miteinander kommunizieren dürfen. Sie reduziert öffentliche Angriffsflächen und begrenzt seitliche Bewegung nach einer Kompromittierung. Schutz entsteht aus Segmentierung, Filterung, privaten Endpunkten und Überwachung.',technical:'NSGs filtern zustandsbehaftet auf Layer 3/4 an Subnetzen oder NICs; Azure Firewall bietet zentrale Layer-3/4- und anwendungsbezogene Filterung, NAT und Logging. WAF schützt HTTP/S auf Layer 7, DDoS Protection mitigiert volumetrische Angriffe und Private Endpoints bringen PaaS-Zugriff in private IP-Pfade. Routing und DNS bestimmen, ob diese Kontrollen tatsächlich durchlaufen werden.',architecture:'Zentrale Firewallmodelle vereinheitlichen Egress, Inspection und Logging, erzeugen aber Kosten, Routingkomplexität und potenziell große Fehlerdomänen. Dezentrale NSG- und workloadnahe Kontrollen skalieren lokal, können jedoch Regelwildwuchs erzeugen. Ein gutes Design kombiniert zentrale Transitkontrollen mit lokaler Segmentierung und klarer Ownership.',why:'Identität allein verhindert nicht jeden Angriffspfad; Netzwerkschutz begrenzt Erreichbarkeit und Blast Radius.',examples:['Spokes verwenden lokale NSGs, leiten kontrollierten Internet-Egress über eine zentrale Azure Firewall und erreichen Storage über Private Endpoints.'],merksatz:'Routing bestimmt den Pfad, Segmentierung begrenzt Reichweite und Firewalls kontrollieren den erlaubten Verkehr.',sources:['ms-networking-overview','ms-firewall','ms-nsg-asg','ms-storage-private-endpoints'],tags:['network-security','segmentation','layer-3-4','layer-7']},
  'azure-0817':{title:'Defense in Depth',simple:'Defense in Depth schützt ein System mit mehreren unabhängigen Sicherheitsschichten. Wenn eine Kontrolle versagt oder umgangen wird, begrenzen weitere Schichten den Angriff. Die Schichten reichen von physischer Infrastruktur bis zu Identität, Netzwerk, Anwendung, Daten und Recovery.',technical:'Typische Ebenen sind Physical, Identity and Access, Perimeter, Internal Network, Compute, Application, Data und Recovery. Jede Ebene kombiniert präventive, detektive und korrektive Controls und liefert Telemetrie. Unabhängige Identitäten, Schlüssel und Backups verhindern, dass eine einzige Kompromittierung alle Schutzschichten zugleich aufhebt.',architecture:'Mehr Schichten sind nicht automatisch besser; sie müssen unterschiedliche Fehler- und Angriffswege adressieren. Doppelte Kontrollen ohne klare Verantwortung erhöhen Betriebslast, während gemeinsame Administratoren oder Secrets scheinbar unabhängige Schichten koppeln. Threat Modeling und Attack Paths bestimmen die sinnvolle Staffelung.',why:'Angriffe nutzen oft mehrere kleine Schwächen; gestaffelte Kontrollen verhindern, dass eine einzelne Lücke zum Totalausfall wird.',examples:['Ein kompromittiertes App-Konto wird durch minimale RBAC-Rechte, private Datenpfade, getrennte Key-Vault-Berechtigungen und unveränderbare Backups begrenzt.'],merksatz:'Eine Schicht kann fallen, ohne dass der gesamte Schutz fällt.',sources:['ms-security-overview','ms-security-design-patterns','ms-zero-trust-infrastructure'],tags:['defense-in-depth','layered-security','blast-radius']},
  'azure-0818':{title:'Physical Security',simple:'Physical Security schützt Azure-Rechenzentren, Hardware und Betriebsbereiche vor unbefugtem Zugang und physischen Gefahren. Microsoft betreibt dafür mehrere Zugangskontrollen, Überwachung und geprüfte Betriebsprozesse. In der Public Cloud gehört diese Ebene zur Verantwortung von Microsoft.',technical:'Azure-Datacenter verwenden gestaffelte Perimeter-, Gebäude- und Betriebsbereichskontrollen, Genehmigungsprozesse, Überwachung und sichere Hardwareentsorgung. Physische Infrastruktur, Hosts und das Basisnetz werden durch Microsoft betrieben. Kunden erhalten keine direkte Kontrolle über einzelne physische Server, wählen aber Region, Verfügbarkeitsmodell und Dienstkonfiguration.',architecture:'Cloud verschiebt physische Sicherheit zum Provider, beseitigt aber nicht die Kundenverantwortung für Daten, Identitäten, Endgeräte und Konfiguration. Regulatorische Anforderungen werden über Regionen, Compliance-Nachweise und Vertragsbedingungen adressiert statt durch eigenen Zutritt. Dedicated- oder Sovereignty-Anforderungen müssen gesondert bewertet werden.',why:'Physical Security bildet die unterste Vertrauensschicht, auf der alle logischen Azure-Controls aufbauen.',examples:['Ein Audit nutzt Microsoft-Nachweise zur Datacenterkontrolle, während das Unternehmen selbst Identitäten, Datenzugriffe und Endgeräte prüft.'],merksatz:'Microsoft schützt das Rechenzentrum; der Kunde schützt seine Nutzung der Cloud.',sources:['ms-azure-infrastructure-security','ms-azure-physical-security','ms-shared-responsibility'],tags:['physical-security','datacenter','shared-responsibility']},
  'azure-0821':{title:'Identity & Access Security',simple:'Identity & Access Security prüft, wer oder was auf Ressourcen zugreifen möchte und was erlaubt ist. Authentication bestätigt die Identität, Authorization entscheidet über Berechtigungen. MFA, Conditional Access, PIM, Managed Identity und RBAC reduzieren missbräuchlichen Zugriff.',technical:'Entra ID authentifiziert Benutzer, Anwendungen und Workloadidentitäten und stellt Tokens aus. Conditional Access bewertet Signale und erzwingt Controls, MFA erhöht die Sicherheit der Anmeldung, PIM begrenzt privilegierte Rollen zeitlich und RBAC autorisiert Azure-Aktionen an Scopes. Managed Identities vermeiden gespeicherte Anwendungscredentials.',architecture:'Zero Trust verlangt explizite Prüfung, Least Privilege und Annahme einer Kompromittierung. Menschliche und Workloadidentitäten werden getrennt, privilegierte Zugriffe sind zeitlich begrenzt und Notfallkonten gesondert geschützt. Zu breite Rollen und dauerhafte Secrets schaffen Angriffswege über alle anderen Schichten.',why:'Identitäten sind die Steuerungsebene der Cloud; kompromittierte Berechtigungen können Netzwerk-, Daten- und Recovery-Controls verändern.',examples:['Ein Administrator aktiviert eine privilegierte Rolle per PIM mit MFA, während eine App per Managed Identity nur Leserechte auf einen Blob-Container erhält.'],merksatz:'Authentication beweist wer; Authorization begrenzt was.',sources:['ms-zero-trust-infrastructure','ms-conditional-access','ms-mfa','ms-pim','ms-rbac'],tags:['identity-security','authentication','authorization','least-privilege']},
  'azure-0824':{title:'Perimeter Security',simple:'Perimeter Security schützt die Übergänge zwischen vertrauensärmeren und internen Bereichen. Sie reduziert schädlichen oder unerwünschten Datenverkehr, bevor er Workloads erreicht. In Azure gehören DDoS Protection, Azure Firewall, WAF und kontrollierte öffentliche Endpunkte dazu.',technical:'DDoS Protection mitigiert volumetrische Layer-3/4-Angriffe, Azure Firewall filtert zentral Netzwerk- und Anwendungsverkehr und WAF untersucht HTTP/S-Anfragen auf Layer 7. NAT, Routing, Public IPs, TLS und Logging bestimmen die tatsächliche Schutzwirkung. Perimeterkontrollen ersetzen keine interne Segmentierung oder Identitätsprüfung.',architecture:'Moderne Architekturen besitzen mehrere Perimeter statt einer einzigen Netzgrenze: Internet, Hybridzugang, PaaS-Endpunkte, APIs und Administration. Controls werden dem Protokoll und Angriffstyp zugeordnet. Eine zentrale Firewall vereinfacht Governance, während regionale oder workloadnahe Instanzen Fehlerdomänen und Latenz reduzieren können.',why:'Öffentliche und domänenübergreifende Übergänge bündeln Angriffsfläche und benötigen passende Schutz- und Beobachtungspunkte.',examples:['Ein öffentlicher Webdienst nutzt DDoS Protection am Netzwerk, WAF für HTTP/S und Azure Firewall für kontrollierten ausgehenden Verkehr.'],merksatz:'Layer 3/4 schützt den Verkehrsfluss; Layer 7 versteht die Webanfrage.',sources:['ms-ddos','ms-firewall','ms-waf','ms-networking-overview'],tags:['perimeter-security','ddos','firewall','waf']},
  'azure-0827':{title:'Internal Network Security und Segmentierung',simple:'Interne Segmentierung teilt Netzwerke in kleinere Sicherheitsbereiche mit klar erlaubten Verbindungen. Dadurch kann ein kompromittiertes System nicht automatisch alle anderen Ressourcen erreichen. NSGs, ASGs, Subnetze, Routing und Private Endpoints setzen diese Grenzen um.',technical:'NSGs filtern Quell-/Ziel-IP, Port und Protokoll an Subnetzen oder NICs; ASGs gruppieren Workloadrollen für Regeln. UDRs erzwingen Datenpfade über Inspektionspunkte, während Private Endpoints PaaS-Dienste über private IPs erreichbar machen. DNS und Routing müssen konsistent sein, sonst werden Kontrollen umgangen oder Dienste unerreichbar.',architecture:'Segmentierung folgt Vertrauensniveau, Datenklassifikation und Workloadbeziehung, nicht nur organisatorischen Teams. Mikrosegmentierung reduziert Blast Radius, erhöht aber Regel- und Troubleshootingaufwand. Zentrale Policy, wiederverwendbare Muster und Flow-Logs verhindern unkontrollierte lokale Sonderregeln.',why:'Viele Angriffe werden erst kritisch, wenn der Angreifer sich seitlich zu privilegierten Systemen oder Daten bewegen kann.',examples:['Web-, App- und Datenbanksubnetze erlauben nur notwendige Ost-West-Verbindungen; PaaS-Datenbanken werden über Private Endpoints erreicht.'],merksatz:'Segmentierung macht aus einem großen Vertrauensraum mehrere kleine, kontrollierte Wege.',sources:['ms-nsg-asg','ms-security-design-patterns','ms-storage-private-endpoints'],tags:['network-segmentation','east-west-security','microsegmentation']},
  'azure-0833':{title:'Application Security',simple:'Application Security schützt Code, APIs, Abhängigkeiten und Laufzeitkonfiguration während Entwicklung und Betrieb. Sie verhindert, dass unsichere Eingaben, verwundbare Pakete oder offengelegte Secrets zu einem Angriff führen. Plattformschutz ersetzt keine sichere Anwendung.',technical:'Controls umfassen Threat Modeling, sichere Entwicklungspraktiken, Dependency- und Code-Scanning, WAF/API-Schutz, starke Authentifizierung und Autorisierung, Secretless Access sowie Laufzeittelemetrie. Secrets gehören in Key Vault und Workloads nutzen Managed Identity. Patching und Vulnerability Management schließen bekannte Schwachstellen.',architecture:'Security wird in den Software-Lifecycle integriert und nach Datenflüssen und Trust Boundaries entworfen. WAF filtert Webmuster, behebt aber keinen unsicheren Code; Scanner finden mögliche Schwächen, benötigen jedoch Priorisierung und Remediation. PaaS reduziert Plattformbetrieb, lässt Code, Daten und Konfiguration beim Kunden.',why:'Anwendungen verarbeiten Geschäftslogik und Daten; Fehler auf dieser Ebene umgehen oft reine Netzwerkkontrollen.',examples:['Eine App Service-Anwendung nutzt Managed Identity für Key Vault, validiert API-Tokens und blockiert bekannte Webangriffe über WAF.'],merksatz:'Die Plattform schützt die Laufzeit; das Team schützt Code, Abhängigkeiten und Konfiguration.',sources:['ms-security-design-patterns','ms-shared-responsibility','ms-keyvault-security'],tags:['application-security','secure-development','secretless']},
  'azure-0834':{title:'Application Security Controls',simple:'Application Security Controls sind konkrete Maßnahmen zum Schutz einer Anwendung. Dazu zählen sichere Anmeldung, minimale Berechtigungen, Eingabeprüfung, Secret Management, WAF und Schwachstellenbehebung. Sie müssen über Entwicklung und Betrieb hinweg gepflegt werden.',technical:'Präventive Controls validieren Eingaben, erzwingen Token und reduzieren Rechte; detektive Controls sammeln App-, Identity- und Security-Telemetrie. Code- und Dependency-Scanner sowie Defender-Findings identifizieren Schwächen, während Pipelines Policy Gates anwenden können. Key Vault und Managed Identity vermeiden fest codierte Credentials.',architecture:'Controls werden an Trust Boundaries und Missbrauchsszenarien ausgerichtet. Zentrale Plattformstandards liefern Baselines, Produktteams verantworten fachliche Autorisierung und sichere Codepfade. Automatisierte Gates müssen Ausnahmen, False Positives und dringende Patches betrieblich handhaben können.',why:'Nur anwendungsspezifische Controls verstehen fachliche Regeln und können missbräuchliche, aber technisch gültige Anfragen erkennen.',examples:['Eine Deployment-Pipeline blockiert kritische Dependency-Findings und erlaubt der laufenden App nur über Managed Identity den Zugriff auf benötigte Secrets.'],merksatz:'Sichere Anwendungen kombinieren Codekontrollen, Plattformkontrollen und laufende Remediation.',sources:['ms-security-design-patterns','ms-defender-recommendations','ms-keyvault-security'],tags:['application-controls','vulnerability-remediation','devsecops']},
  'azure-0836':{title:'Data Security',simple:'Data Security schützt Informationen beim Speichern, Übertragen und Verarbeiten. Sie kombiniert Klassifikation, Verschlüsselung, Zugriffskontrolle, Schlüsselverwaltung, Backup und Wiederherstellung. Der Schutz richtet sich nach Sensibilität und Geschäftsanforderung der Daten.',technical:'Verschlüsselung at rest und in transit schützt Inhalte, während Entra ID und RBAC Datenoperationen autorisieren. Key Vault verwaltet Keys, Secrets und Certificates; Private Endpoints begrenzen Netzwerkpfade. Versioning, Soft Delete, Backup und Immutability unterstützen Integrität und Recovery, sind aber getrennte Schutzmechanismen.',architecture:'Daten werden über ihren Lebenszyklus inventarisiert, klassifiziert und mit Owner, Aufbewahrung und Löschanforderung versehen. Microsoft-Managed Keys bieten robuste Standardverschlüsselung; CMK ergänzt kundenseitige Schlüsselkontrolle mit höherem Betriebsrisiko. Backups benötigen getrennte Berechtigungen und Restore-Tests gegen Ransomware.',why:'Daten bleiben oft länger bestehen als Anwendungen und sind häufig das eigentliche Ziel eines Angriffs.',examples:['Vertrauliche Dokumente liegen verschlüsselt in privatem Storage, werden per RBAC begrenzt und besitzen getrennte unveränderbare Recovery Points.'],merksatz:'Daten brauchen Schutz beim Zugriff, auf dem Transport, im Ruhezustand und bei der Wiederherstellung.',sources:['ms-storage-encryption','ms-key-management-choice','ms-backup-security','ms-storage-authorization'],tags:['data-security','encryption','data-lifecycle']},
  'azure-0837':{title:'Protection of Data at Rest',simple:'Data-at-Rest-Schutz sichert gespeicherte Daten gegen unbefugtes Lesen, Verändern und Löschen. Azure-Dienste verschlüsseln viele Daten standardmäßig mit Microsoft-Managed Keys. Zusätzliche Zugriffskontrollen, CMK, Versionierung und Backups adressieren weitere Risiken.',technical:'Service-side Encryption verschlüsselt Daten transparent vor dem Speichern und entschlüsselt sie beim autorisierten Abruf. Unterstützte Dienste können einen CMK aus Key Vault oder Managed HSM verwenden; Identität, Key Permissions und Key Availability werden dann Teil des Datenpfads. Soft Delete, Versions und immutable Backups schützen nicht die Vertraulichkeit, sondern Wiederherstellbarkeit und Integrität.',architecture:'Verschlüsselung ist kein Ersatz für Autorisierung, weil berechtigte oder kompromittierte Identitäten entschlüsselte Daten lesen können. CMK wird nur mit klarer Kontrollanforderung gewählt und benötigt Rotation, Löschschutz und Notfallzugriff. Recovery-Kopien müssen mindestens denselben Klassifikations- und Zugriffsschutz erhalten wie Produktionsdaten.',why:'Gespeicherte Daten benötigen mehrere unabhängige Kontrollen, weil Verschlüsselung allein weder Fehlberechtigung noch Löschung verhindert.',examples:['Ein Storage Account verwendet Standardverschlüsselung, private Zugriffe, Datenrollen und unveränderbare Backups; CMK wird nur für regulierte Daten aktiviert.'],merksatz:'Encryption schützt Inhalt, Access Control schützt Nutzung und Backup schützt Wiederherstellung.',sources:['ms-storage-encryption','ms-key-management-choice','ms-backup-security'],tags:['data-at-rest','encryption-at-rest','recovery-protection']},
  'azure-0838':{title:'Data Protection Controls',simple:'Data Protection Controls verbinden Verschlüsselung, Zugriffskontrolle, Key Vault, Versionierung, Backup und Recovery. Jede Kontrolle schützt gegen andere Verlust- oder Angriffsszenarien. Gemeinsam erhalten sie Vertraulichkeit, Integrität und Wiederherstellbarkeit.',technical:'Encryption at rest verwendet serviceverwaltete oder kundenseitig verwaltete Keys; Key Vault schützt kryptografisches Material und Secrets. RBAC und private Netzwerkpfade begrenzen Zugriff, während Soft Delete, Versioning, Snapshots und Azure Backup Recovery Points bereitstellen. Immutable Vault kann destruktive Änderungen bis zum Ablauf der Retention blockieren.',architecture:'Ein Schutzmodell beginnt mit Datenklassifikation und Threat Model. Produktions- und Backupadministration sollten getrennt, Recovery Points außerhalb des primären Blast Radius und Schlüssel gegen Löschung geschützt sein. Mehr Retention und Immutability erhöhen Schutz, reduzieren aber Änderungsfreiheit und können Kosten steigern.',why:'Ransomware, Fehlkonfiguration und Insider-Risiken erfordern andere Kontrollen als ein reiner Hardwareausfall.',examples:['Ein Unternehmen trennt Storage-Administratoren von Backup-Administratoren und sperrt produktionskritische Recovery Points durch unveränderbare Aufbewahrung.'],merksatz:'Kein einzelner Schalter schützt Daten vor Lesen, Ändern und Löschen zugleich.',sources:['ms-backup-security','ms-backup-immutable','ms-keyvault-security','ms-storage-encryption'],tags:['data-protection','immutable-backup','ransomware-protection']},
  'azure-0840':{title:'Shared Responsibility for Security',simple:'Cloud Security ist eine gemeinsame Verantwortung von Microsoft und dem Kunden. Microsoft schützt Rechenzentren, Hardware und große Teile der Plattform. Der Kunde bleibt für Daten, Identitäten, Zugriff, Konfiguration und je nach Servicemodell weitere Schichten verantwortlich.',technical:'Bei IaaS betreibt der Kunde Betriebssystem, Anwendungen, Daten und viele Netzwerkcontrols; bei PaaS übernimmt Microsoft zusätzlich Betriebssystem und Laufzeit. Unabhängig vom Modell bleiben Accounts, Access Management, Datenklassifikation und kontrollierte Konfiguration Kundenaufgaben. Verantwortung kann an Teams delegiert, aber nicht durch den Dienstkauf beseitigt werden.',architecture:'Die Verantwortungsmatrix wird pro Workload und Service explizit dokumentiert. PaaS reduziert und standardisiert Betriebsaufgaben, verlangt aber weiterhin sichere Code-, Identity-, Data- und Recovery-Entscheidungen. Unklare Übergaben zwischen Plattform-, Produkt- und Securityteams erzeugen Kontrolllücken.',why:'Viele Cloudvorfälle entstehen nicht durch fehlende Plattformfunktionen, sondern durch falsch verstandene Kundenverantwortung.',examples:['Bei App Service patcht Microsoft das Betriebssystem; das Produktteam verantwortet Code, Authentifizierung, Secrets, Datenzugriff und Recoverytests.'],merksatz:'Microsoft sichert die Cloud; gemeinsam sichern wir, was in der Cloud betrieben wird.',sources:['ms-shared-responsibility','ms-security-pillar'],tags:['shared-responsibility','iaas-paas-saas','security-ownership']},
  'azure-0932':{title:'Azure Security Tools and Features',simple:'Azure stellt Werkzeuge für Schutz, Bewertung, Erkennung, Untersuchung und Governance bereit. Dazu gehören Defender for Cloud, Sentinel, Key Vault, Policy, Monitor und spezialisierte Identity- und Network-Dienste. Die Werkzeuge benötigen ein gemeinsames Betriebsmodell.',technical:'Defender for Cloud bewertet Posture und schützt unterstützte Workloads, Sentinel korreliert Security Events, Key Vault verwaltet sensitive Objekte und Policy erzwingt Ressourcenkonfiguration. Entra ID liefert Identity Controls, Network Services begrenzen Datenpfade und Azure Monitor/Log Analytics speichern operative Signale. Integrationen verbinden Findings mit Alerts und Remediation.',architecture:'Tools werden nach benötigter Capability und Datenfluss ausgewählt, nicht nach maximaler Produktzahl. Detection ohne Incident Ownership oder Recommendation ohne Remediation-SLA erzeugt keine Risikoreduktion. Zentrale Securityteams liefern Plattform und Standards; Workloadteams beheben kontextspezifische Risiken.',why:'Ein abgestimmtes Toolset schafft kontinuierliche Sichtbarkeit und handlungsfähige Schutzprozesse über viele Azure-Domänen.',examples:['Defender priorisiert ein internetexponiertes VM-Finding, Policy verhindert die Fehlkonfiguration künftig und Sentinel alarmiert bei verdächtigem Verhalten.'],merksatz:'Tools liefern Signale und Kontrollen; Prozesse und Owner reduzieren das Risiko.',sources:['ms-defender-overview','ms-defender-recommendations','ms-zero-trust-infrastructure'],tags:['security-tooling','detection-response','security-operations']},
  'azure-0934':{title:'Defender for Cloud Recommendations and Workload Protection',simple:'Defender for Cloud bewertet Cloudressourcen kontinuierlich und zeigt Sicherheitsprobleme als priorisierte Empfehlungen. Secure Score fasst einen Teil der bewerteten Schutzlage zusammen. Workload-Protection-Pläne erkennen zusätzlich Bedrohungen und Schwachstellen für unterstützte Ressourcen.',technical:'CSPM vergleicht Konfigurationen mit Security Standards und erzeugt Findings, Recommendations, Attack Paths und Secure-Score-Beiträge. Defender-Pläne ergänzen workloadbezogene Signale für Server, Container, Storage, Datenbanken und weitere Dienste; Vulnerability Management bewertet unterstützte Maschinen und Images. Ergebnisse benötigen Scope, Planaktivierung, Telemetrie und Berechtigungen.',architecture:'Secure Score ist ein Orientierungs- und Verbesserungsmaß, kein Beweis vollständiger Sicherheit. Empfehlungen werden nach Exposition, Kritikalität, Exploitability und Geschäftskontext priorisiert und mit Owner sowie Frist versehen. Defender ergänzt Policy: Defender findet und priorisiert Risiken, Policy verhindert oder meldet wiederkehrende Konfigurationsabweichungen.',why:'Kontinuierliche Bewertung macht neue Ressourcen, Drift und Schwachstellen sichtbar, bevor sie dauerhaft unbemerkt bleiben.',examples:['Defender priorisiert eine kritische Schwachstelle auf einer öffentlich erreichbaren VM höher als dieselbe Schwäche in einem isolierten Testsystem.'],merksatz:'Secure Score zeigt Richtung; risikobasierte Remediation verbessert den tatsächlichen Schutz.',sources:['ms-defender-secure-score','ms-defender-recommendations','ms-defender-vulnerability','ms-defender-posture'],tags:['defender-for-cloud','secure-score','vulnerability-assessment','cspm']},
  'azure-0944':{title:'Azure Key Vault',simple:'Azure Key Vault speichert und schützt Keys, Secrets und Certificates zentral. Anwendungen greifen darauf über Entra ID und Berechtigungen zu, statt sensitive Werte im Code abzulegen. Der Dienst unterstützt sicheren Schlüssel- und Secret-Lifecycle.',technical:'Key Vault bietet versionierte Objekte über REST und SDKs; Authentifizierung erfolgt mit Entra ID, Autorisierung vorzugsweise über Azure RBAC. Keys führen kryptografische Operationen aus, Secrets speichern sensitive Werte und Certificates ergänzen X.509-Lifecycle. Netzwerkzugriff, Logging, Soft Delete, Purge Protection und Rotation härten den Vault.',architecture:'Ein Vault ist eine Security- und Blast-Radius-Grenze und sollte nach Anwendung, Umgebung, Region und Mandant geschnitten werden. Managed Identity ermöglicht credentialfreien Zugriff, aber Least Privilege und getrennte Administration bleiben nötig. Key Vault ist kein allgemeiner Konfigurations- oder Datenspeicher und seine Verfügbarkeit kann zum kritischen Anwendungsdependency werden.',why:'Zentraler, auditierbarer Zugriff reduziert Secret-Leaks und schafft kontrollierbare Schlüssel- und Zertifikatsprozesse.',examples:['Eine App Service-Anwendung liest ein Datenbanksecret per Managed Identity aus einem produktionsgetrennten Key Vault.'],merksatz:'Key Vault schützt sensitive Objekte; Managed Identity schützt den Weg dorthin.',sources:['ms-keyvault-concepts','ms-keyvault-objects','ms-keyvault-security','ms-keyvault-auth'],tags:['azure-key-vault','secrets','keys','certificates']},
  'azure-0945':{title:'Secrets Management',simple:'Secrets Management schützt Passwörter, API-Schlüssel, Connection Strings und andere sensitive Werte über ihren Lebenszyklus. Secrets werden zentral gespeichert, nur berechtigten Workloads bereitgestellt und regelmäßig rotiert. Sie gehören nicht in Quellcode, Images oder ungeschützte Konfiguration.',technical:'Key Vault Secrets sind versionierte Werte mit Aktivierungs-, Ablauf- und Verwaltungsmetadaten. Workloads authentifizieren sich idealerweise per Managed Identity und erhalten per RBAC nur benötigte Get- oder List-Berechtigungen. Rotation, Caching, Audit Logs, Netzwerkzugriff, Soft Delete und Purge Protection gehören zum Betrieb.',architecture:'Der beste Secret ist ein Secret, das durch föderierte oder verwaltete Identität entfallen kann. Verbleibende Secrets werden nach Anwendung und Umgebung segmentiert und mit Owner, Rotation und Notfallverfahren versehen. Zu aggressives Laufzeitabrufen erhöht Abhängigkeit und Latenz; unkontrolliertes Caching verlängert Exposition.',why:'Offengelegte langfristige Credentials ermöglichen Angreifern oft direkten Zugriff ohne weitere Schwachstelle.',examples:['Eine Anwendung ersetzt ein fest codiertes Storage Account Key durch Managed Identity; das verbleibende Drittanbieter-Secret liegt versioniert im Key Vault.'],merksatz:'Vermeiden, zentral schützen, minimal freigeben und regelmäßig rotieren.',sources:['ms-keyvault-concepts','ms-keyvault-security','ms-managed-identities'],tags:['secrets-management','rotation','credentialless']},
  'azure-0946':{title:'Keys, Secrets and Certificates',simple:'Key Vault unterscheidet Keys, Secrets und Certificates, weil sie unterschiedliche Aufgaben haben. Keys führen kryptografische Operationen aus, Secrets speichern sensitive Werte und Certificates verbinden Schlüssel mit einer digitalen Identität. Das richtige Objekt vereinfacht Lifecycle und Berechtigungen.',technical:'Keys unterstützen Verschlüsselungs-, Signatur- und Wrap/Unwrap-Operationen und können software- oder HSM-geschützt sein. Secrets sind opaque Werte, während Certificates X.509-Policies, Issuer, Renewal und zugehörige Key-/Secret-Repräsentationen besitzen. Alle Objekte sind versioniert und besitzen eigene Datenaktionen und Identifiers.',architecture:'Kryptografische Schlüssel sollten nicht als exportierbare Secrets behandelt werden; Zertifikate benötigen Ablauf- und Erneuerungsprozesse. HSM-Schutz, Exportierbarkeit, Rotation und Vaultgrenzen folgen Risiko und Compliance. CMK für Azure-Dienste verwendet einen Key, nicht beliebig ein Secret oder Certificate.',why:'Die korrekte Objektwahl verhindert unsichere Schlüsselhandhabung und macht Rotation, Audit und Least Privilege präziser.',examples:['Ein TLS-Zertifikat wird als Certificate mit Renewal Policy verwaltet, ein API-Token als Secret und ein Storage-CMK als nicht exportierbarer Key.'],merksatz:'Secret ist ein Wert, Key führt Kryptografie aus, Certificate bindet einen Schlüssel an Identität.',sources:['ms-keyvault-objects','ms-keyvault-security','ms-key-management-choice'],tags:['key-vault-objects','cryptographic-keys','x509-certificates']}
};

const relationDefinitions = [
  ['security-rel-001','azure-0815','azure-0816','contains','Die Security-&-Protection-Architektur umfasst Network Security als eigene Schutzdomäne.',['ms-security-overview','ms-networking-overview'],0.99],
  ['security-rel-002','azure-0815','azure-0932','contains','Security Tools and Features liefern Schutz-, Bewertungs-, Erkennungs- und Governance-Funktionen für die Security-Architektur.',['ms-security-overview','ms-defender-overview'],0.98],
  ['security-rel-003','azure-0815','azure-0944','contains','Azure Key Vault ist ein zentraler Baustein der Security-Architektur für Keys, Secrets und Certificates.',['ms-keyvault-concepts','ms-keyvault-objects'],0.98],
  ['security-rel-004','azure-0821','azure-0817','part_of','Identity & Access Security ist eine Defense-in-Depth-Schicht, die Authentication und Authorization kontrolliert.',['ms-security-overview','ms-zero-trust-infrastructure'],0.99],
  ['security-rel-005','azure-0824','azure-0817','part_of','Perimeter Security schützt Übergänge zu externen oder weniger vertrauenswürdigen Bereichen.',['ms-security-overview','ms-networking-overview'],0.99],
  ['security-rel-006','azure-0827','azure-0817','part_of','Interne Segmentierung begrenzt laterale Bewegung als eigene Defense-in-Depth-Schicht.',['ms-security-design-patterns','ms-nsg-asg'],0.99],
  ['security-rel-007','azure-0833','azure-0817','part_of','Application Security schützt Code, APIs, Abhängigkeiten und Laufzeitkonfiguration innerhalb von Defense in Depth.',['ms-security-design-patterns','ms-shared-responsibility'],0.99],
  ['security-rel-008','azure-0836','azure-0817','part_of','Data Security schützt gespeicherte, übertragene und verarbeitete Informationen innerhalb von Defense in Depth.',['ms-security-pillar','ms-storage-encryption'],0.99],
  ['security-rel-009','azure-0840','azure-0815','part_of','Shared Responsibility ordnet Security-Aufgaben zwischen Microsoft, Plattformteams und Workloadteams zu.',['ms-shared-responsibility'],0.99],
  ['security-rel-010','azure-0966','azure-0817','part_of','Least Privilege reduziert den Blast Radius kompromittierter Identitäten und ist ein Kernprinzip gestaffelter Security.',['ms-zero-trust-infrastructure','ms-rbac'],0.99],
  ['security-rel-011','azure-0824','azure-0852','uses','Perimeter Security verwendet DDoS Protection zur Mitigation volumetrischer Layer-3/4-Angriffe auf öffentliche Endpunkte.',['ms-ddos','ms-networking-overview'],0.99],
  ['security-rel-012','azure-0824','azure-0841','uses','Perimeter Security verwendet Azure Firewall für zentrale Netzwerk- und Anwendungsregeln, NAT und Logging.',['ms-firewall','ms-networking-overview'],0.99],
  ['security-rel-013','azure-0824','azure-0863','uses','Perimeter Security verwendet WAF zur Layer-7-Prüfung von HTTP/S-Anfragen.',['ms-waf','ms-networking-overview'],0.99],
  ['security-rel-014','azure-0827','azure-0864','uses','Interne Segmentierung verwendet NSGs für zustandsbehaftete Layer-3/4-Regeln an Subnetzen oder NICs.',['ms-nsg-asg'],0.99],
  ['security-rel-015','azure-0827','azure-0875','uses','Interne Segmentierung verwendet Application Security Groups zur rollenbasierten Gruppierung von NICs in NSG-Regeln.',['ms-nsg-asg'],0.99],
  ['security-rel-016','azure-0827','azure-0881','uses','Interne Segmentierung verwendet Private Endpoints, um unterstützte PaaS-Dienste über private IP-Pfade zu erreichen.',['ms-storage-private-endpoints','ms-private-link'],0.99],
  ['security-rel-017','azure-0833','azure-0863','uses','Application Security verwendet WAF als ergänzende Schutzschicht für Webanfragen; sichere Anwendungscodepfade bleiben erforderlich.',['ms-waf','ms-security-design-patterns'],0.98],
  ['security-rel-018','azure-0833','azure-0944','uses','Anwendungen verwenden Key Vault, um sensitive Werte und kryptografische Objekte außerhalb von Code und Images zu verwalten.',['ms-keyvault-security','ms-keyvault-concepts'],0.99],
  ['security-rel-019','azure-0836','azure-0944','uses','Data Security verwendet Key Vault für kontrollierte Schlüssel-, Secret- und Zertifikatsverwaltung.',['ms-keyvault-objects','ms-key-management-choice'],0.99],
  ['security-rel-020','azure-0944','azure-0945','contains','Key Vault enthält versionierte Secrets und stellt dafür eigene Datenaktionen bereit.',['ms-keyvault-objects','ms-keyvault-concepts'],0.99],
  ['security-rel-021','azure-0944','azure-0946','contains','Key Vault verwaltet die unterschiedlichen Objekttypen Keys, Secrets und Certificates.',['ms-keyvault-objects'],0.99],
  ['security-rel-022','azure-0944','azure-0076','contains','Customer-Managed Keys werden für unterstützte Dienste in Key Vault oder Managed HSM gehalten und betrieben.',['ms-key-management-choice','ms-keyvault-security'],0.98],
  ['security-rel-023','azure-0579','azure-0076','uses','Ein unterstützter Storage Account kann einen Customer-Managed Key aus Key Vault oder Managed HSM für die Verschlüsselung referenzieren.',['ms-storage-encryption','ms-key-management-choice'],0.99],
  ['security-rel-024','azure-0838','azure-0579','secures','Data Protection Controls schützen Storage-Daten durch Verschlüsselung, Zugriffskontrolle, Versionierung, Backup und Recovery-Mechanismen.',['ms-storage-encryption','ms-blob-data-protection','ms-backup-security'],0.98],
  ['security-rel-025','azure-0933','azure-0322','secures','Defender for Cloud ergänzt die VM-Sicherheitsarchitektur durch kontinuierliche Bewertung und aktivierte Workload-Protection-Funktionen.',['ms-defender-overview','ms-defender-servers'],0.99],
  ['security-rel-026','azure-0934','azure-0933','part_of','Secure Score, Recommendations und Vulnerability Findings sind Teil der Defender-for-Cloud-Posture- und Workload-Protection-Erfahrung.',['ms-defender-secure-score','ms-defender-recommendations','ms-defender-vulnerability'],0.99],
  ['security-rel-027','azure-0934','azure-0936','part_of','Recommendations und Secure Score liefern bewertete Signale für Security Posture und Compliance Monitoring.',['ms-defender-secure-score','ms-defender-recommendations','ms-defender-posture'],0.99],
  ['security-rel-028','azure-0962','azure-0817','governs','Azure Policy kann Security-Baselines über Ressourcen hinweg prüfen, melden oder mit geeigneten Effects durchsetzen.',['ms-policy-overview','ms-security-benchmark'],0.99],
  ['security-rel-029','azure-0114','azure-0116','uses','Disaster Recovery verwendet Azure Backup für unabhängige VM-Recovery-Points und Restore-Szenarien.',['ms-vm-backup','ms-backup-security','ms-bcdr-concepts'],0.99],
  ['security-rel-030','azure-0114','azure-0118','uses','Disaster Recovery verwendet Azure Site Recovery für unterstützte Replikations-, Failover- und Failback-Szenarien.',['ms-site-recovery','ms-bcdr-concepts'],0.99],
  ['security-rel-031','azure-0115','azure-0114','part_of','Recovery-Planung ist der operative Teil einer Disaster-Recovery-Strategie und definiert Reihenfolge, Rollen, Tests und Validierung.',['ms-bcdr-concepts','ms-backup-security'],0.99],
  ['security-rel-032','azure-0117','azure-0114','part_of','Replikation, Failover und Failback sind mögliche technische Mechanismen innerhalb eines Disaster-Recovery-Plans.',['ms-bcdr-concepts','ms-site-recovery'],0.99],
  ['security-rel-033','azure-0116','azure-0322','secures','Azure Backup schützt VM-Wiederherstellbarkeit mit getrennten Recovery Points und Restore-Funktionen.',['ms-vm-backup','ms-backup-security'],0.99],
  ['security-rel-034','azure-0838','azure-0116','uses','Data Protection Controls verwenden Azure Backup als wiederherstellende Schutzschicht gegen Löschung, Beschädigung und Ransomware-Szenarien.',['ms-backup-security','ms-backup-immutable'],0.99]
];

for (const source of officialSources) {
  const index = sourcesDocument.sources.findIndex(item => item.id === source.id);
  if (index >= 0) sourcesDocument.sources[index] = source;
  else sourcesDocument.sources.push(source);
}
const typeById = new Map(typesDocument.relation_types.map(type => [type.id, type]));

for (const [id, enrichment] of Object.entries(E)) {
  const node = nodeById.get(id);
  if (!node) throw new Error(`Pilotknoten fehlt: ${id}`);
  if (node.metadata?.enrichment) throw new Error(`${id}: Bereits in V${node.metadata.enrichment.version} angereichert und gegen Überschreiben geschützt.`);
  const originalTitle = node.title;
  node.title = enrichment.title || node.title;
  node.description = {simple:enrichment.simple,technical:enrichment.technical,architecture:enrichment.architecture};
  node.why_important = enrichment.why;
  node.examples = enrichment.examples || [];
  node.merksatz = enrichment.merksatz || '';
  node.analogy = enrichment.analogy || '';
  node.sources = [...new Set([...(node.sources || []), ...enrichment.sources])];
  node.tags = [...new Set([...(node.tags || []), ...(enrichment.tags || []), 'security-pilot-v1.7'])];
  node.aliases = [...new Set([...(node.aliases || []), ...(originalTitle !== node.title ? [originalTitle] : [])])];
  node.metadata = {...node.metadata,status:'published',audit_flags:(node.metadata.audit_flags || []).filter(flag => flag !== 'description_generated_from_title'),enrichment:{version:'1.7',pilot:'security-protection-architecture',content_standard:'1.0',reviewed_at:today,source_policy:'official_microsoft_only'}};
  node.updated_at = today;
}

const pilotRelationIds = new Set(relationDefinitions.map(([id]) => id));
relationsDocument.relations = relationsDocument.relations.filter(relation => !pilotRelationIds.has(relation.id));
for (const node of nodesDocument.nodes) node.relations = (node.relations || []).filter(id => !pilotRelationIds.has(id));
for (const [id, source, target, type, explanation, sources, confidence] of relationDefinitions) {
  if (!nodeById.has(source) || !nodeById.has(target)) throw new Error(`${id}: Endpunkt fehlt`);
  const typeDefinition = typeById.get(type);
  if (!typeDefinition) throw new Error(`${id}: Typ ${type} fehlt`);
  for (const sourceId of sources) if (!sourcesDocument.sources.some(item => item.id === sourceId)) throw new Error(`${id}: Quelle ${sourceId} fehlt`);
  const relation = {schema_version:'1.1',id,source,target,type,inverse_type:typeDefinition.inverse_type,explanation,sources,confidence,status:'accepted',created_by:'knowledge_enrichment_v1.7',created_at:today,reviewed_at:today};
  relationsDocument.relations.push(relation);
  for (const nodeId of [source,target]) {
    const node = nodeById.get(nodeId);
    node.relations = [...new Set([...(node.relations || []), id])];
  }
}

nodesDocument.meta = {...nodesDocument.meta,enrichment_version:'1.7',security_pilot:{node_count:Object.keys(E).length,relation_count:relationDefinitions.length,content_standard:'1.0',reviewed_at:today,focus:'security_and_protection_architecture'}};
relationsDocument.meta = {...relationsDocument.meta,relation_count:relationsDocument.relations.length,enrichment_version:'1.7',security_relation_count:relationDefinitions.length};
sourcesDocument.meta = {...sourcesDocument.meta,count:sourcesDocument.sources.length,generated_at:today,enrichment_version:'1.7'};
typesDocument.meta = {...typesDocument.meta,type_count:typesDocument.relation_types.length,updated_at:today,enrichment_version:'1.7'};

write('nodes.json',nodesDocument);
write('relations.json',relationsDocument);
write('sources.json',sourcesDocument);
write('relation-types.json',typesDocument);

console.log(JSON.stringify({enriched_nodes:Object.keys(E).length,added_relations:relationDefinitions.length,total_relations:relationsDocument.relations.length,added_relation_types:0,total_relation_types:typesDocument.relation_types.length,added_sources:officialSources.length,total_sources:sourcesDocument.sources.length},null,2));
