import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonical = path.join(project, 'data/canonical');
const today = '2026-08-11';
const read = name => JSON.parse(fs.readFileSync(path.join(canonical, name), 'utf8'));
const write = (name, value) => fs.writeFileSync(path.join(canonical, name), `${JSON.stringify(value, null, 2)}\n`);

const nodesDocument = read('nodes.json');
const relationsDocument = read('relations.json');
const sourcesDocument = read('sources.json');
const typesDocument = read('relation-types.json');
const nodeById = new Map(nodesDocument.nodes.map(node => [node.id, node]));

const officialSources = [
  {id:'ms-azure-monitor-overview',title:'Azure Monitor overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/fundamentals/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-azure-monitor-data-platform',title:'Azure Monitor data platform',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/fundamentals/data-platform',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-metrics',title:'Azure Monitor Metrics overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/metrics/data-platform-metrics',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-logs',title:'Azure Monitor Logs overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-diagnostic-settings',title:'Diagnostic settings in Azure Monitor',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-alerts',title:'Azure Monitor alerts overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-application-insights',title:'Application Insights overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-application-map',title:'Application map in Application Insights',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-map',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-monitor-workbooks',title:'Azure Workbooks overview',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-service-health-overview',title:'What is Azure Service Health?',url:'https://learn.microsoft.com/en-us/azure/service-health/overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-resource-health-overview',title:'Azure Resource Health overview',url:'https://learn.microsoft.com/en-us/azure/service-health/resource-health-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-advisor-overview',title:'Azure Advisor documentation',url:'https://learn.microsoft.com/en-us/azure/advisor/',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-advisor-score',title:'Advisor score',url:'https://learn.microsoft.com/en-us/azure/advisor/advisor-score',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-operations-observability',title:'Architecture strategies for designing a monitoring system',url:'https://learn.microsoft.com/en-us/azure/well-architected/operational-excellence/observability',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cloud-estate-monitor',title:'Monitor your Azure cloud estate',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/manage/monitor',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cloud-operations-functions',title:'Understand cloud operations functions',url:'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-operations',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-reliability-targets',title:'Architecture strategies for defining reliability targets',url:'https://learn.microsoft.com/en-us/azure/well-architected/reliability/metrics',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-failover-failback',title:'What are failover and failback?',url:'https://learn.microsoft.com/en-us/azure/reliability/concept-failover-failback',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-sla-concepts',title:'How to read a service-level agreement',url:'https://learn.microsoft.com/en-us/azure/reliability/concept-service-level-agreements',publisher:'Microsoft Learn',accessed_at:today,type:'official'}
];

const E = {
  'azure-0094':{title:'Manageability und Cloud Operations',simple:'Manageability beschreibt, wie Azure-Ressourcen zentral bereitgestellt, gesteuert und überwacht werden. Gute Verwaltbarkeit macht Betrieb wiederholbar und nachvollziehbar. Sie verbindet Werkzeuge, Automatisierung, Governance und Monitoring.',technical:'Azure Portal, CLI, PowerShell, REST APIs und Infrastructure as Code greifen auf die Azure-Steuerungsebene zu. Azure Monitor sammelt Betriebsdaten, während Policy und RBAC Grenzen für Änderungen setzen. Die Plattform stellt Werkzeuge bereit, aber der Kunde definiert Standards, Zuständigkeiten und Reaktionsprozesse.',architecture:'Architekten standardisieren Bereitstellung, Telemetrie, Zugriff und Betriebsabläufe über Plattformteams und Workloadteams hinweg. Zentralisierung verbessert Konsistenz, kann jedoch Teamautonomie und Datengrenzen einschränken. Ein föderiertes Betriebsmodell kombiniert zentrale Leitplanken mit workloadnaher Verantwortung.',why:'Ohne Manageability wird eine wachsende Cloud-Landschaft langsam, inkonsistent und schwer wiederherstellbar.',examples:['Eine Plattform stellt Bicep-Module, Policy-Baselines, zentrale Monitor-Regeln und klar zugewiesene Runbooks für alle Produktteams bereit.'],merksatz:'Verwaltbarkeit macht Cloud-Betrieb wiederholbar, messbar und verantwortbar.',sources:['ms-cloud-operations-functions','ms-cloud-estate-monitor'],tags:['manageability','cloud-operations','operating-model']},
  'azure-0095':{title:'Zentrale Steuerung und Überwachung von Cloud-Ressourcen',simple:'Azure-Ressourcen lassen sich über gemeinsame Verwaltungs- und Überwachungswerkzeuge betreiben. Teams sehen Zustände, Änderungen und Störungen über viele Ressourcen hinweg. Zentral bedeutet dabei nicht, dass ein einziges Team alles selbst erledigen muss.',technical:'Die Azure Resource Manager-Steuerungsebene liefert Inventar und Änderungsereignisse; Azure Monitor verarbeitet Metriken, Logs, Traces und Events. RBAC begrenzt Zugriff und Azure Policy bewertet Konformität. Unterschiedliche Dienste besitzen weiterhin eigene Datenebenen, Telemetriearten und Betriebsgrenzen.',architecture:'Eine zentrale Sicht erleichtert Korrelation und Standardisierung, während getrennte Workspaces oder Zuständigkeiten Isolation und Datenhoheit verbessern können. Architekturentscheidungen betreffen Scope, Aufbewahrung, Zugriffsmodell, Kosten und Eskalationswege. Die Betriebsverantwortung muss pro Signal und Ressource festgelegt sein.',why:'Eine gemeinsame Betriebssicht reduziert blinde Flecken und beschleunigt koordinierte Reaktionen.',examples:['Ein zentrales Operations-Team sieht Plattformzustand und Baselines, während App-Teams nur die Logs und Dashboards ihrer Workloads verwalten.'],merksatz:'Zentrale Sicht, verteilte Verantwortung.',sources:['ms-cloud-estate-monitor','ms-azure-monitor-overview'],tags:['central-management','operations','federated-monitoring']},
  'azure-0098':{title:'Monitoring und Operations mit Azure Monitor',simple:'Monitoring beobachtet definierte Signale und meldet Abweichungen. Operations nutzt diese Signale, um Systeme stabil zu betreiben, Störungen zu bearbeiten und Verbesserungen abzuleiten. Azure Monitor, Log Analytics, Alerts und Application Insights bilden dafür zentrale Bausteine.',technical:'Azure Monitor erfasst Plattformmetriken, Aktivitäts- und Ressourcenlogs sowie Anwendungstelemetrie. Diagnostic Settings und Data Collection Rules steuern Datenpfade; Log Analytics analysiert Logs mit KQL und Alerts verbinden Bedingungen mit Action Groups. Nicht jede Telemetrie wird automatisch gesammelt oder unbegrenzt gespeichert.',architecture:'Monitoring beantwortet bekannte Fragen und Schwellenwerte; Observability ermöglicht aus Metriken, Logs und Traces auch unbekannte Fehlerbilder abzuleiten. Architekten wählen Signale nach Geschäftsflüssen, SLOs und Reaktionsfähigkeit statt nach maximalem Datenvolumen. Betriebsteams verantworten Qualität, Kosten, Zugriffe, Alarmhygiene und Runbooks.',why:'Telemetrie wird erst durch Analyse, Zuständigkeit und Handlung zu zuverlässigem Betrieb.',examples:['Ein Checkout-Fluss besitzt Erfolgsrate, Latenz, Abhängigkeits-Traces, Logabfragen und einen Alert mit Runbook und Bereitschaftsdienst.'],merksatz:'Sammeln zeigt Daten; betreiben bedeutet daraus verlässlich zu handeln.',sources:['ms-azure-monitor-overview','ms-operations-observability','ms-cloud-estate-monitor'],tags:['monitoring','observability','operations']},
  'azure-0100':{title:'Operational Manageability',simple:'Operational Manageability bedeutet, dass ein System im Alltag sicher und effizient bedient werden kann. Dazu gehören klare Zustände, Automatisierung, Diagnose und kontrollierte Änderungen. Ein technisch funktionierender Dienst kann trotzdem schlecht betreibbar sein.',technical:'Betreibbarkeit benötigt standardisierte Deployment- und Konfigurationspfade, strukturierte Telemetrie, Dashboards, Alerts, Runbooks und auditierbare Zugriffe. APIs und IaC reduzieren manuelle Abweichungen. Grenzen entstehen durch fehlende Instrumentierung, unklare Ownership und voneinander getrennte Datenquellen.',architecture:'Architekten behandeln Betrieb als eigene Qualitätsanforderung und planen ihn parallel zur Funktion. Automatisierung senkt Toil, erhöht aber die Auswirkung fehlerhafter Regeln; zentrale Werkzeuge vereinfachen Betrieb, können jedoch gemeinsame Abhängigkeiten schaffen. Jede Automation braucht Schutz, Tests und einen manuellen Rückweg.',why:'Betreibbarkeit entscheidet, wie schnell Teams Änderungen und Störungen sicher beherrschen.',examples:['Ein Dienst kann über IaC reproduziert, über ein Health-Dashboard verstanden und über ein getestetes Runbook zurückgesetzt werden.'],merksatz:'Gut gebaut ist erst gut betrieben.',sources:['ms-cloud-operations-functions','ms-operations-observability'],tags:['operational-excellence','manageability','automation']},
  'azure-0107':{title:'Fault Tolerance und Fehlerbetrieb',simple:'Fault Tolerance lässt einen Dienst trotz Ausfall einzelner Komponenten weiterarbeiten. Sie nutzt Redundanz, Erkennung und Umschaltung. Monitoring zeigt, wann die vorgesehenen Fehlermodi tatsächlich eintreten.',technical:'Mehrere Instanzen, Health Probes, Load Balancing, Replikation und Failover begrenzen einzelne Fehler. Telemetrie erkennt Ausfälle und Degradation, während Automatisierung Traffic umleiten oder Instanzen ersetzen kann. Gemeinsame Abhängigkeiten und falsche Health-Signale können die Toleranz aufheben.',architecture:'Architekten definieren erwartete Fehlerdomänen und gewünschte Degradation statt pauschal maximale Redundanz zu kaufen. Schnellere automatische Reaktion reduziert Ausfallzeit, kann aber bei fehlerhaften Signalen Folgeschäden auslösen. Failoverlogik, Zustandskonsistenz und Rückkehrbetrieb müssen getestet werden.',why:'Fehler sind unvermeidbar; Fault Tolerance verhindert, dass jeder Einzelfehler zum Geschäftsausfall wird.',examples:['Ein Webdienst verteilt Traffic auf mehrere Zonen und nimmt eine Instanz erst nach bestätigtem Health-Probe-Fehler aus dem Verkehr.'],merksatz:'Fehler tolerieren heißt erkennen, begrenzen und kontrolliert weiterarbeiten.',sources:['ms-bcdr-concepts','ms-failover-failback','ms-reliability-targets'],tags:['fault-tolerance','health-signals','failover']},
  'azure-0108':{title:'Verfügbarkeit trotz Komponentenfehlern',simple:'Ein fehlertoleranter Service bleibt für Benutzer nutzbar, obwohl eine Instanz, ein Host oder eine Zone ausfällt. Das erfordert mehr als nur mehrere Kopien. Der Dienst muss Fehler erkennen und seine Arbeit auf gesunde Komponenten verlagern.',technical:'Health Checks und synthetische Tests liefern Zustände; Load Balancer entfernen ungesunde Ziele und Orchestratoren ersetzen Instanzen. Zustandsbehaftete Komponenten benötigen Replikation und Konsistenzregeln. Ein grünes Infrastruktur-Signal beweist nicht automatisch, dass ein Geschäftsfluss funktioniert.',architecture:'Die Health-Definition sollte kritische Benutzerflüsse und Abhängigkeiten abbilden. Zu aggressive Schwellen erzeugen Flapping, zu träge Schwellen verlängern Ausfälle. Teams müssen entscheiden, wann Graceful Degradation sinnvoller ist als vollständiger Failover.',why:'Verfügbarkeit entsteht durch funktionsfähige Reaktion auf Fehler, nicht allein durch vorhandene Redundanz.',examples:['Eine API meldet nur dann gesund, wenn sie auch ihre kritische Datenbankabhängigkeit innerhalb des vereinbarten Zeitbudgets erreicht.'],merksatz:'Redundanz schafft Optionen; Health und Failover nutzen sie.',sources:['ms-reliability-targets','ms-failover-failback'],tags:['availability','health-model','graceful-degradation']},
  'azure-0109':{title:'Redundante Instanzen und Kapazitätsreserve',simple:'Mehrere Instanzen vermeiden, dass eine einzelne Komponente den gesamten Dienst stoppt. Sie können außerdem Last verteilen. Reservekapazität muss auch während Wartung oder Ausfall ausreichen.',technical:'Instanzen werden über Fehlerdomänen, Zonen oder Regionen verteilt und über einen gemeinsamen Daten- und Routingpfad koordiniert. Autoscale reagiert auf Metriken, ersetzt aber keine Mindestreserve für plötzliche Fehler. Zustand, Quoten und nachgelagerte Abhängigkeiten begrenzen die nutzbare Kapazität.',architecture:'Zusätzliche Instanzen erhöhen Kosten und können gemeinsame Engpässe verdecken. Architekten dimensionieren für Normalbetrieb, Ausfallszenario und Skalierungsverzögerung. Capacity Monitoring betrachtet Sättigung und Throttling, nicht nur durchschnittliche CPU.',why:'Redundanz ohne ausreichende Restkapazität kann beim ersten Ausfall kollabieren.',examples:['Drei Instanzen über drei Zonen halten auch nach dem Verlust einer Zone die vereinbarte Spitzenlast aus.'],merksatz:'Plane Kapazität für den Fehlerfall, nicht nur für den Normalfall.',sources:['ms-reliability-targets','ms-bcdr-concepts','ms-monitor-metrics'],tags:['redundancy','capacity-monitoring','headroom']},
  'azure-0110':{title:'Automatisches Failover',simple:'Failover schaltet Arbeit von einer fehlerhaften auf eine gesunde Instanz oder Umgebung um. Automatisierung kann die Reaktion beschleunigen. Sie braucht jedoch verlässliche Signale und einen getesteten Rückweg.',technical:'Ein Failover wird durch Health-Zustände, Schwellen oder eine bewusste Betriebsentscheidung ausgelöst und ändert Routing, Rollen oder Replikatpriorität. Asynchrone Replikation kann Datenverlust innerhalb des RPO verursachen. Failback synchronisiert Änderungen und stellt den gewünschten Primärzustand wieder her.',architecture:'Automatisches Failover eignet sich bei eindeutig messbaren Fehlern und sicherem Zielzustand. Bei mehrdeutigen oder datenrelevanten Ereignissen kann menschliche Freigabe risikoärmer sein. Architekten bewerten Split-Brain, DNS-Verzögerung, Abhängigkeiten und Wiederanlaufkosten.',why:'Schnelles Umschalten begrenzt Ausfallzeit, aber unkontrolliertes Umschalten kann einen größeren Incident erzeugen.',examples:['Traffic wird nach mehreren fehlgeschlagenen Health-Prüfungen in eine gesunde Region umgeleitet und später kontrolliert zurückgeführt.'],merksatz:'Failover braucht ein verlässliches Signal, ein gesundes Ziel und einen Rückweg.',sources:['ms-failover-failback','ms-reliability-targets'],tags:['failover','automation','recovery-signal']},
  'azure-0111':{title:'Load Balancing und Health Probes',simple:'Ein Load Balancer verteilt Anfragen auf mehrere Ziele. Health Probes prüfen, welche Ziele Traffic erhalten sollen. Sie schützen Nutzer aber nur, wenn die Prüfung den echten Dienstzustand sinnvoll abbildet.',technical:'Probes prüfen in Intervallen einen TCP- oder HTTP-Endpunkt; fehlerhafte Ziele werden aus der Verteilung genommen und nach Erholung wieder aufgenommen. Plattform- und Anwendungsmetriken ergänzen diese lokale Entscheidung. Eine oberflächliche Probe kann gesund melden, obwohl eine kritische Abhängigkeit ausfällt.',architecture:'Readiness, Liveness und End-to-End-Health erfüllen unterschiedliche Zwecke und sollten nicht vermischt werden. Tiefe Prüfungen liefern bessere Aussage, erhöhen aber Last und Kopplung. Fail-open oder Fail-closed wird nach Risiko des jeweiligen Datenpfads entschieden.',why:'Traffic darf nicht nur verteilt, sondern muss auf tatsächlich nutzbare Instanzen gelenkt werden.',examples:['Der Readiness-Endpunkt prüft Konfiguration und kritische Abhängigkeiten, während Liveness nur einen festgefahrenen Prozess erkennt.'],merksatz:'Eine Health Probe ist eine Routingentscheidung, keine vollständige Root-Cause-Analyse.',sources:['ms-reliability-targets','ms-operations-observability','ms-load-balancing'],tags:['load-balancing','health-probes','readiness']},
  'azure-0112':{title:'Multi-Zone und Multi-Region nach Kritikalität',simple:'Mehrere Zonen schützen vor lokalen Rechenzentrumsausfällen, mehrere Regionen vor größeren regionalen Ereignissen. Nicht jede Anwendung benötigt beide Ebenen. Die Wahl folgt Geschäftsrisiko und Wiederherstellungsziel.',technical:'Zonenredundanz verteilt Komponenten innerhalb einer Region mit geringer Latenz; Multi-Region benötigt zusätzlich Replikation, globales Routing und abgestimmte Abhängigkeiten. Monitoring muss den Zustand je Standort und den gesamten Benutzerfluss zeigen. Failover und Datenkonsistenz unterscheiden sich je Dienst.',architecture:'Multi-Region kann RTO verbessern, erhöht aber Kosten, Betriebsaufwand und Testbedarf erheblich. Architekten wählen Active/Active, Active/Passive oder Restore nach SLO, RPO/RTO und Datenanforderungen. Telemetrie und Runbooks müssen dieselben Fehlergrenzen abdecken wie das Design.',why:'Verfügbarkeitsarchitektur muss zur tatsächlichen Ausfallwirkung und nicht zum maximal möglichen Design passen.',examples:['Ein kritisches Portal läuft zonenredundant und hält eine zweite Region als getestetes Warm-Standby bereit.'],merksatz:'Zonen mindern lokale Fehler, Regionen mindern regionale Fehler.',sources:['ms-zones-overview','ms-regions-overview','ms-failover-failback'],tags:['availability-zones','multi-region','criticality']},
  'azure-0113':{title:'Fault Tolerance versus High Availability',simple:'Fault Tolerance ist die Fähigkeit, bestimmte Fehler zu verkraften. High Availability ist das messbare Ziel, den Dienst möglichst lange nutzbar zu halten. Ein Design kann einzelne Fehler tolerieren und trotzdem sein Gesamtziel verfehlen.',technical:'Fault-Tolerance-Mechanismen umfassen Redundanz, Failover, Partitionierung und Graceful Degradation. Availability wird über definierte SLIs und SLOs in einem Beobachtungsfenster gemessen. Plattform-SLAs ersetzen weder Workload-SLOs noch End-to-End-Messung.',architecture:'Architekten ordnen jedem Availability-Ziel konkrete Fehlerannahmen, Controls und Messwerte zu. Mehr Mechanismen können Verfügbarkeit erhöhen, erzeugen aber Kosten und neue Komplexität. Das Ergebnis muss aus Benutzersicht überwacht und regelmäßig durch Tests validiert werden.',why:'Die Trennung verhindert, dass technische Redundanz fälschlich als garantierte Verfügbarkeit gilt.',examples:['Zwei Webinstanzen tolerieren einen Hostausfall, erfüllen aber kein End-to-End-SLO, wenn die gemeinsame Datenbank ausfällt.'],merksatz:'Fault Tolerance ist ein Mittel; High Availability ist das gemessene Ergebnis.',sources:['ms-bcdr-concepts','ms-reliability-targets','ms-sla-concepts'],tags:['fault-tolerance','high-availability','slo']},
  'azure-0979':{title:'Monitoring, Observability und Operations in Azure',simple:'Dieser Wissensbereich zeigt, wie Azure-Systeme erkannt, gemessen, analysiert und betrieben werden. Monitoring prüft bekannte Zustände, Observability hilft auch unbekannte Ursachen aus Telemetrie abzuleiten. Operations verbindet Erkenntnisse mit Verantwortung, Reaktion und Verbesserung.',technical:'Azure Monitor vereint Metriken, Logs, Traces und Events; Log Analytics, Application Insights, Alerts und Workbooks analysieren oder visualisieren sie. Advisor, Service Health und Resource Health ergänzen Optimierungs- und Plattformsignale. Die Signale besitzen unterschiedliche Aktualität, Granularität und Zuständigkeit.',architecture:'Eine Observability-Architektur beginnt bei kritischen Flows und Health-Modellen und definiert dann Instrumentierung, Sammlung, Korrelation, Aufbewahrung und Reaktion. Mehr Daten verbessern nicht automatisch Diagnose und erhöhen Kosten sowie Datenschutzrisiken. Zentraler Plattformbetrieb und workloadnahe Interpretation müssen zusammenarbeiten.',why:'Nur eine durchgängige Signalkette von Geschäftsfluss bis Runbook macht den Azure-Lifecycle lernfähig.',examples:['Ein Team korreliert Nutzerfehler aus Application Insights mit Plattformmetriken, Deployment-Logs und Service-Health-Ereignissen und aktualisiert danach sein Runbook.'],merksatz:'Monitoren erkennt; Observability erklärt; Operations handelt und verbessert.',sources:['ms-azure-monitor-overview','ms-operations-observability','ms-cloud-operations-functions'],tags:['monitoring','observability','operations-lifecycle']},
  'azure-0983':{title:'Azure Monitor',simple:'Azure Monitor ist der zentrale Azure-Dienst für Telemetrie und Observability. Er sammelt und verarbeitet Metriken, Logs, Traces und Events aus Anwendungen, Azure-Ressourcen und hybriden Umgebungen. Analysen, Visualisierungen und Alerts machen daraus Betriebsinformationen.',technical:'Metrics speichert numerische Zeitreihen für schnelle Auswertung; Azure Monitor Logs speichert strukturierte Datensätze in Log Analytics Workspaces und wird mit KQL abgefragt. Application Insights instrumentiert Anwendungen. Diagnostic Settings und Data Collection Rules steuern ausgewählte Datenpfade, wobei Retention, Limits und Kosten je Datentyp variieren.',architecture:'Architekten entscheiden Scope, Workspace-Topologie, Datengrenzen, Aufbewahrung, Zugriffsmodell und Ausfallsicht. Metrics eignen sich für schnelle Erkennung, Logs und Traces für Kontext und Root-Cause-Analyse. Der Kunde verantwortet Instrumentierung, relevante Diagnostic Settings, Alertregeln, Zugriff und Reaktion.',why:'Azure Monitor bildet die gemeinsame Signaleebene zwischen Workload, Plattform, Security, Governance und Reliability.',examples:['Eine Plattform sammelt VM- und PaaS-Metriken zentral, sendet ausgewählte Ressourcenlogs an Log Analytics und korreliert Anwendungstraces mit Infrastrukturereignissen.'],merksatz:'Azure Monitor liefert Signale; ein Health-Modell gibt ihnen Bedeutung.',sources:['ms-azure-monitor-overview','ms-azure-monitor-data-platform','ms-operations-observability'],tags:['azure-monitor','metrics','logs','traces']},
  'azure-0984':{title:'Azure Monitor Alerts',simple:'Azure Monitor Alerts benachrichtigen oder automatisieren, wenn eine definierte Bedingung erfüllt ist. Ein Alert ist ein technisches Signal, noch kein vollständig bearbeiteter Incident. Gute Alerts sind relevant, eindeutig zugeordnet und handlungsfähig.',technical:'Alert Rules werten Metriken, Logabfragen, Activity Logs oder andere unterstützte Signale aus. Action Groups versenden Benachrichtigungen oder starten Automatisierung. Stateful-Verhalten, Auswertungsfenster, Häufigkeit und Schwellen beeinflussen Verzögerung, Fehlalarme und Kosten.',architecture:'Alerts werden aus SLOs, Health-Zuständen und konkreten Runbooks abgeleitet. Zu empfindliche Regeln erzeugen Alarmmüdigkeit, zu grobe Regeln erkennen Störungen zu spät. Ein Incident beginnt, wenn Menschen oder Automatisierung die Auswirkung koordinieren, priorisieren und beheben.',why:'Ohne handlungsfähige Alerts bleiben kritische Abweichungen in Dashboards und Logs unbemerkt.',examples:['Eine hohe Fehlerrate löst einen Alert mit betroffener Anwendung, Severity, Dashboard-Link, Runbook und zuständigem On-Call-Team aus.'],merksatz:'Ein Alert sagt handeln; ein Incident organisiert die Wiederherstellung.',sources:['ms-monitor-alerts','ms-operations-observability'],tags:['alerts','incident-response','action-groups']},
  'azure-0985':{title:'Log Analytics Workspace',simple:'Ein Log Analytics Workspace ist der zentrale Datenspeicher für Azure Monitor Logs. Er organisiert Telemetrie in Tabellen und macht sie mit Kusto Query Language analysierbar. Zugriff, Aufbewahrung und Kosten werden am Workspace und an Tabellen gesteuert.',technical:'Daten werden über Diagnostic Settings, Agents, Data Collection Rules, APIs und integrierte Dienste aufgenommen. Tabellen besitzen Schema, Plan und Retention; Abfragen nutzen KQL. Workspace- und Ressourcenkontext sowie Azure RBAC bestimmen, welche Datensätze ein Benutzer lesen darf.',architecture:'Die Workspace-Topologie balanciert zentrale Korrelation gegen Isolation, Datenresidenz, Security-Grenzen und Kostenverantwortung. Ein Workspace pro Ressource verhindert oft sinnvolle Korrelation; ein einziger globaler Workspace kann Zugriff und Governance erschweren. Aufbewahrung folgt Diagnose-, Compliance- und Kostenbedarf.',why:'Der Workspace ist die gemeinsame Analysebasis für Betriebs-, Anwendungs-, Governance- und Security-Signale.',examples:['Produktionslogs mehrerer Komponenten liegen in einem kontrollierten Workspace, während besonders regulierte Workloads wegen Datenresidenz getrennt bleiben.'],merksatz:'Der Workspace sammelt Logs; KQL macht Zusammenhänge sichtbar.',sources:['ms-monitor-logs','ms-log-analytics','ms-cloud-estate-monitor'],tags:['log-analytics-workspace','kql','log-architecture']},
  'azure-0986':{title:'Logspeicherung und Analyse mit KQL',simple:'Logs halten detaillierte Ereignisse und Kontext fest. In Log Analytics werden sie in Tabellen gespeichert und mit KQL durchsucht. Sie helfen besonders bei Fehleranalyse, Audit und langfristigen Trends.',technical:'Jeder Logdatensatz besitzt Zeitstempel und strukturierte Felder; KQL filtert, aggregiert, verbindet und korreliert Tabellen. Metrics sind kompakte Zeitreihen und meist schneller für Schwellen, Logs sind detailreicher und flexibler. Hohe Datenmenge, lange Retention und komplexe Abfragen erhöhen Kosten und Latenz.',architecture:'Logdesign priorisiert entscheidungsrelevante, strukturierte Ereignisse mit Korrelations-IDs. Vollständige Detailerfassung verbessert Debugging, kann aber sensible Daten, Kosten und Rauschen erhöhen. Teams definieren Tabellenpläne, Retention und Zugriffsgrenzen nach Betriebs- und Compliance-Zweck.',why:'Logs liefern den Kontext, den reine Metrikabweichungen für Root-Cause-Analyse nicht enthalten.',examples:['Eine KQL-Abfrage verbindet fehlgeschlagene Requests mit Dependency-Fehlern und einem kurz zuvor ausgeführten Deployment.'],merksatz:'Metriken zeigen dass etwas kippt; Logs helfen zu verstehen warum.',sources:['ms-monitor-logs','ms-log-analytics','ms-operations-observability'],tags:['logs','kql','root-cause-analysis']},
  'azure-0987':{title:'Application Insights',simple:'Application Insights überwacht Laufzeit, Leistung und Nutzung von Anwendungen. Es sammelt Requests, Abhängigkeiten, Ausnahmen, Traces und weitere Telemetrie. Dadurch sehen Entwickler Probleme aus Sicht der Anwendung und ihrer Benutzerflüsse.',technical:'Instrumentierung erfolgt über OpenTelemetry, SDKs oder unterstützte automatische Instrumentierung. Telemetrie wird in Azure Monitor verarbeitet und workspacebasiert in Log Analytics gespeichert; Application Map korreliert Komponenten und Abhängigkeiten. Sampling, Instrumentierungsabdeckung und Kardinalität begrenzen Genauigkeit und Kosten.',architecture:'Application Insights eignet sich für Code- und Transaktionsebene, ersetzt aber weder Infrastruktur- noch Service-Health-Monitoring. Architekten definieren kritische Flows, Korrelationskontext und Datenfilterung. Mehr Telemetrie verbessert Diagnose, muss aber gegen Performance, Datenschutz und Ingestionskosten abgewogen werden.',why:'Anwendungsfehler sind in Plattformmetriken oft unsichtbar; Application Insights verbindet Nutzerwirkung mit Code und Abhängigkeiten.',examples:['Ein langsamer Checkout wird über verteilte Traces bis zu einer fehlerhaften Datenbankabhängigkeit verfolgt.'],merksatz:'Application Insights beobachtet den Geschäftsfluss, nicht nur den Server.',sources:['ms-application-insights','ms-application-map','ms-operations-observability'],tags:['application-insights','apm','distributed-tracing']},
  'azure-0988':{title:'Application Insights als Teil von Azure Monitor',simple:'Application Insights ist die anwendungsorientierte Observability-Funktion innerhalb von Azure Monitor. Seine Telemetrie kann gemeinsam mit Infrastruktur- und Plattformdaten analysiert werden. So entsteht ein End-to-End-Bild.',technical:'Application Insights sendet Requests, Dependencies, Exceptions, Traces und Custom Events an einen workspacebasierten Azure-Monitor-Datenpfad. KQL-Abfragen, Alerts und Workbooks können diese Daten mit anderen Tabellen und Metriken kombinieren. Unterschiedliche Sampling- und Retentionseinstellungen können Korrelation beeinflussen.',architecture:'Die Integration reduziert Werkzeugbrüche, verlangt aber gemeinsame Namens-, Zeit- und Korrelationsstandards. App-Teams verantworten Instrumentierung und Interpretation, Plattformteams Workspace, Zugriff und zentrale Standards. Eine gemeinsame Plattform darf nicht zu unkontrolliertem Datenzugriff führen.',why:'Erst die Verbindung von Code-, Abhängigkeits- und Ressourcensignalen verkürzt die Ursachenanalyse verteilter Fehler.',examples:['Ein Workbook zeigt App-Fehler, VM-Sättigung und Deployment-Ereignisse im selben Zeitfenster.'],merksatz:'Application Insights liefert Anwendungskontext zur Azure-Monitor-Signaleebene.',sources:['ms-application-insights','ms-azure-monitor-overview','ms-monitor-workbooks'],tags:['application-insights','azure-monitor','telemetry-correlation']},
  'azure-0989':{title:'Application Performance Monitoring (APM)',simple:'APM misst, wie schnell und zuverlässig eine Anwendung aus Benutzersicht arbeitet. Es beobachtet Requests, Fehler, Abhängigkeiten und Nutzung. Ziel ist nicht nur Erkennung, sondern die Lokalisierung von Leistungsproblemen.',technical:'APM korreliert Server-Requests, Dependency Calls, Exceptions, Traces und benutzerdefinierte Metriken über Telemetrie-Kontext. Verteilte Traces zeigen den Pfad einer Transaktion durch Komponenten. Sampling und fehlende Instrumentierung können seltene oder asynchrone Abläufe unvollständig darstellen.',architecture:'Architekten instrumentieren zuerst kritische Benutzerflüsse und externe Abhängigkeiten. Hohe Kardinalität und vollständige Traces erhöhen Diagnosewert und Kosten. APM-Daten müssen mit SLOs, Release-Ereignissen und Infrastrukturzustand verbunden werden, damit Optimierung nicht lokal am falschen Baustein erfolgt.',why:'APM übersetzt technische Laufzeitdaten in die erlebte Qualität von Anwendungen.',examples:['Die Analyse zeigt, dass nicht der Webserver, sondern ein langsamer externer API-Aufruf die Antwortzeit des Bestellflusses bestimmt.'],merksatz:'APM folgt dem Request durch die Anwendung und ihre Abhängigkeiten.',sources:['ms-application-insights','ms-application-map','ms-operations-observability'],tags:['apm','performance','dependencies']},
  'azure-0990':{title:'Fehler- und Anomalieerkennung in Anwendungen',simple:'Application Insights hilft, ungewöhnliche Fehler- oder Leistungsänderungen zu erkennen. Solche Signale weisen auf ein mögliches Problem hin. Sie liefern aber nicht automatisch die vollständige Ursache oder die richtige Reaktion.',technical:'Ausnahmen, fehlgeschlagene Requests, Dependency-Fehler, Metriktrends und unterstützte Erkennungsfunktionen werden aus instrumentierter Telemetrie abgeleitet. Baselines und statistische Verfahren ergänzen feste Schwellen. Sampling, neue Releases und saisonale Last können das Signal beeinflussen.',architecture:'Detection erkennt eingetretene oder entstehende Abweichungen; Prevention reduziert die Eintrittswahrscheinlichkeit durch Design und Controls. Beide Ebenen sind nötig. Anomalien werden nach Nutzerwirkung, Kontext und Runbook priorisiert, bevor sie zu automatischen Aktionen führen.',why:'Frühe Erkennung begrenzt Auswirkung und verkürzt die Zeit bis zur Diagnose.',examples:['Nach einem Deployment steigt die Fehlerrate nur für eine bestimmte Dependency; ein Alert verknüpft Anomalie, Release und Trace-Beispiele.'],merksatz:'Detection findet Abweichungen; Prevention verhindert Ursachen, soweit möglich.',sources:['ms-application-insights','ms-operations-observability'],tags:['anomaly-detection','error-analysis','detection-vs-prevention']},
  'azure-0992':{title:'Anwendungs- und Nutzungsanalyse',simple:'Application Insights zeigt, wie Nutzer und technische Komponenten eine Anwendung tatsächlich verwenden. Teams erkennen erfolgreiche und fehlerhafte Abläufe sowie Leistungsunterschiede. Nutzungsdaten sollten immer zweckgebunden und datenschutzgerecht erhoben werden.',technical:'Custom Events, Page Views, Requests, User Flows und Performance-Telemetrie lassen sich nach Version, Region oder anderen kontrollierten Dimensionen analysieren. Korrelation verbindet Nutzung mit Fehlern und Dependencies. Personenbezug, hohe Kardinalität und unklare Semantik erschweren sichere Auswertung.',architecture:'Architekten unterscheiden technische Observability von Produktanalyse und definieren Datenminimierung, Aufbewahrung und Zugriffe. Ein KPI muss einen Geschäftsfluss abbilden und darf nicht nur leicht messbare Infrastrukturwerte verwenden. Telemetrieänderungen werden wie Schnittstellen versioniert und getestet.',why:'Nutzungs- und Verhaltenssignale verbinden Systemzustand mit tatsächlicher Geschäftswirkung.',examples:['Ein Team misst Abbruchrate und Antwortzeit eines Anmeldeflusses, ohne unnötige personenbezogene Inhalte in Logs zu speichern.'],merksatz:'Beobachte den Nutzerfluss, aber sammle nur was du begründet brauchst.',sources:['ms-application-insights','ms-operations-observability'],tags:['usage-analysis','business-kpi','privacy']},
  'azure-0993':{title:'Azure Advisor',simple:'Azure Advisor analysiert Azure-Konfigurationen und gibt personalisierte Empfehlungen. Die Hinweise betreffen unter anderem Zuverlässigkeit, Sicherheit, Leistung, Kosten und Operational Excellence. Eine Empfehlung ist eine Entscheidungshilfe, keine automatische Architekturfreigabe.',technical:'Advisor bewertet unterstützte Ressourcen und Konfigurationen gegen Microsoft-Heuristiken und Best Practices. Empfehlungen besitzen Kategorie, Auswirkung und mögliche Maßnahme; Advisor Score zeigt Optimierungsfortschritt. Abdeckung, Aktualität und Kontext unterscheiden sich je Dienst und ersetzen keine workloadbezogene Telemetrie.',architecture:'Advisor eignet sich für proaktive Hygiene und regelmäßige Optimierungszyklen. Empfehlungen werden nach Geschäftsrisiko, Abhängigkeiten, Testbarkeit und Aufwand priorisiert; Ausnahmen benötigen Begründung und Ablaufdatum. Blinde Umsetzung kann Kosten oder Risiko an anderer Stelle erhöhen.',why:'Advisor macht wiederkehrende Optimierungspotenziale über eine große Azure-Landschaft sichtbar.',examples:['Ein Plattformteam triagiert wöchentlich Reliability- und Cost-Empfehlungen und überführt akzeptierte Maßnahmen in den normalen Change-Prozess.'],merksatz:'Advisor empfiehlt; Architekturkontext entscheidet.',sources:['ms-advisor-overview','ms-advisor-score','ms-cloud-estate-monitor'],tags:['azure-advisor','proactive-operations','optimization']},
  'azure-0994':{title:'Advisor-Empfehlungen für Zuverlässigkeit, Sicherheit, Leistung und Kosten',simple:'Advisor-Empfehlungen zeigen konkrete Verbesserungsmöglichkeiten an Azure-Ressourcen. Sie helfen, Risiken und Verschwendung früh zu erkennen. Nicht jede Empfehlung passt unverändert zu jedem Geschäftsfall.',technical:'Die Kategorien umfassen Reliability, Security, Performance, Cost und Operational Excellence. Advisor Score und potenzieller Score-Anstieg unterstützen Priorisierung; Empfehlungen können umgesetzt, verschoben oder mit Begründung verworfen werden. Die Bewertung kennt nicht jede Anwendungsabhängigkeit oder interne Vorgabe.',architecture:'Ein Governance-Prozess ordnet Empfehlungen Ownern, Risikoklassen und Änderungsfenstern zu. Kostenoptimierung darf SLOs nicht unterlaufen, Security-Härtung nicht ungeprüft Betriebszugänge blockieren. Wirksamkeit wird nach Umsetzung durch Telemetrie und Review bestätigt.',why:'Kategorisierte Empfehlungen verbinden Plattformwissen mit einem kontinuierlichen Verbesserungsprozess.',examples:['Eine Resize-Empfehlung wird erst nach Kapazitätsanalyse und Lasttest umgesetzt, damit Kosten sinken ohne den SLO zu gefährden.'],merksatz:'Empfehlung plus Kontext plus Validierung ergibt Verbesserung.',sources:['ms-advisor-score','ms-advisor-overview','ms-cloud-estate-monitor'],tags:['advisor-recommendations','continuous-improvement','tradeoffs']},
  'azure-0995':{title:'Azure Advisor als Cloud Coach',simple:'Azure Advisor kann wie ein Cloud Coach auf Verbesserungsmöglichkeiten hinweisen. Er beobachtet jedoch nicht jeden Geschäftsfluss und kennt nicht alle Organisationsziele. Menschen bleiben für Priorität, Risiko und Umsetzung verantwortlich.',technical:'Der Dienst erzeugt ressourcenbezogene Empfehlungen und Scores aus unterstützten Konfigurationssignalen. Benachrichtigungen und regelmäßige Reviews bringen Findings in den Betriebsprozess. Workload-Monitoring, Incident Detection und Root-Cause-Analyse sind separate Fähigkeiten.',architecture:'Advisor wird in ein Backlog mit Ownership, Fristen, Ausnahmeprozess und Erfolgsmessung integriert. Proaktive Operations bearbeiten Empfehlungen vor dem Incident; reaktive Operations stabilisieren einen bereits beeinträchtigten Dienst. Beide Zyklen teilen Telemetrie und Lessons Learned.',why:'Der Coach-Charakter fördert kontinuierliche Verbesserung, ohne menschliche Architekturverantwortung zu verschleiern.',examples:['Ein monatliches Review bewertet offene Advisor-Findings zusammen mit SLO-Trends, Incidents und Kostenentwicklung.'],merksatz:'Advisor coacht proaktiv; Operations entscheidet und liefert nach.',sources:['ms-advisor-overview','ms-advisor-score','ms-cloud-operations-functions'],tags:['advisor','proactive-operations','operational-review']},
  'azure-0998':{title:'Advisor-Benachrichtigungen und operative Nachverfolgung',simple:'Advisor-Empfehlungen können über geeignete Benachrichtigungs- und Betriebswege sichtbar gemacht werden. Eine Meldung allein behebt noch nichts. Sie braucht Owner, Priorität und einen kontrollierten Änderungsprozess.',technical:'Advisor Alerts und integrationsfähige Ausgaben können neue oder geänderte Empfehlungen in Workflows bringen. Deduplizierung, Scope und Kategorie reduzieren Rauschen. Umsetzung und Wirksamkeit werden außerhalb der reinen Benachrichtigung verfolgt.',architecture:'Nicht jede Empfehlung gehört in den Bereitschaftskanal; kritische Risiken, planbare Optimierung und reine Information benötigen unterschiedliche Wege. Architekten trennen Alert, Work Item und Incident nach Dringlichkeit und Nutzerwirkung. So bleibt On-Call handlungsfähig.',why:'Passende Nachverfolgung verhindert, dass wertvolle Empfehlungen ungelesen bleiben oder unnötig Incidents auslösen.',examples:['Ein kritisches Reliability-Finding erzeugt ein priorisiertes Ticket, während eine langfristige Kostenempfehlung in das Optimierungsbacklog fließt.'],merksatz:'Der richtige Kanal richtet sich nach Dringlichkeit und Wirkung.',sources:['ms-advisor-overview','ms-advisor-score','ms-cloud-operations-functions'],tags:['advisor-alerts','triage','operational-workflow']},
  'azure-0999':{title:'Azure Service Health',simple:'Azure Service Health informiert personalisiert über Azure-Ereignisse, geplante Wartung und Hinweise, die verwendete Dienste und Regionen betreffen. Resource Health betrachtet dagegen den Zustand einzelner Ressourcen. Beide ergänzen das eigene Workload-Monitoring.',technical:'Service Health liefert abonnements- und regionsbezogene Service Issues, Planned Maintenance und Advisories. Resource Health meldet Zustände wie Available, Degraded, Unavailable oder Unknown für unterstützte Ressourcen. Die Signale stammen aus der Plattform und kennen nicht automatisch die End-to-End-Auswirkung auf den Geschäftsfluss.',architecture:'Plattform-Health ist ein externer Health Signal, keine Root-Cause-Analyse der gesamten Anwendung. Teams korrelieren es mit Application Insights, Ressourcenlogs und synthetischen Tests. Eskalation, Kommunikationsweg und regionale Recovery-Entscheidung werden in Incident-Runbooks festgelegt.',why:'Service Health hilft schnell zu unterscheiden, ob ein Problem durch ein bekanntes Azure-Ereignis beeinflusst wird.',examples:['Bei erhöhter Fehlerrate prüft der On-Call-Dienst Service Health, Resource Health und eigene Telemetrie, bevor ein regionaler Failover entschieden wird.'],merksatz:'Service Health erklärt Azure-Ereignisse; Workload-Telemetrie zeigt die Nutzerwirkung.',sources:['ms-service-health-overview','ms-resource-health-overview','ms-cloud-estate-monitor'],tags:['service-health','resource-health','platform-signals']},
  'azure-1000':{title:'Service-Health-Alerts',simple:'Service-Health-Alerts benachrichtigen über relevante Azure-Serviceereignisse. Sie können Incident Response und Kommunikation früh starten. Nicht jedes Plattformereignis beeinträchtigt jedoch den eigenen Dienst.',technical:'Alert Rules filtern Service-Health-Ereignisse nach Subscription, Service, Region und Ereignistyp und verwenden Action Groups für Benachrichtigung oder Automation. Ereignisse umfassen Ausfälle, Wartung und Advisories. Eigene Health Checks bleiben nötig, weil Plattformscope und Workloadscope nicht identisch sind.',architecture:'Alerts werden auf tatsächlich genutzte Regionen und Dienste zugeschnitten und mit Runbooks verbunden. Automatischer Failover sollte nicht allein auf eine allgemeine Service-Meldung reagieren, sondern zusätzliche Workload-Signale prüfen. Kommunikation unterscheidet bestätigte Auswirkung von möglicher Betroffenheit.',why:'Frühe, gezielte Plattformwarnungen verkürzen Triage und Vorbereitung auf Störungen.',examples:['Ein regionales Service-Health-Ereignis alarmiert das Plattformteam, das gleichzeitig synthetische Tests und Ressourcenstatus prüft.'],merksatz:'Plattformwarnung ist ein Signal zur Prüfung, nicht automatisch der Beweis eines Workload-Ausfalls.',sources:['ms-service-health-overview','ms-resource-health-overview','ms-monitor-alerts'],tags:['service-health-alerts','incident-triage','platform-events']},
  'azure-1042':{title:'Service Level Agreements, Objectives und Indicators',simple:'Ein SLA ist eine vertragliche Zusage zwischen Anbieter und Kunde. Ein SLO ist ein internes messbares Ziel, ein SLI der dazu verwendete Messwert. Azure-SLAs ersetzen nicht das End-to-End-Ziel einer eigenen Anwendung.',technical:'SLIs messen beispielsweise Erfolgsrate, Latenz, Verfügbarkeit oder Kapazität in einem definierten Beobachtungsfenster. SLOs setzen Schwellen auf diese Indikatoren; Alerts warnen vor Zielverletzungen. Microsoft-SLAs besitzen konkrete Bedingungen, Messmethoden und Ausschlüsse je Dienst.',architecture:'Architekten leiten Workload-SLOs aus kritischen Geschäftsflüssen ab und berücksichtigen Plattform, Code, Konfiguration, Betrieb und Abhängigkeiten. Ein höheres Ziel erhöht typischerweise Kosten und Komplexität. SLA, SLO und Error Budget benötigen getrennte Ownership zwischen Business, Engineering und Provider.',why:'Messbare Ziele verbinden Geschäftsanforderung, Architekturentscheidung und Betriebspriorität.',examples:['Ein API-SLO bewertet Erfolgsrate und Latenz des vollständigen Bestellflusses, nicht nur die Verfügbarkeit des App-Service-Plans.'],merksatz:'SLA verspricht, SLO zielt, SLI misst.',sources:['ms-reliability-targets','ms-sla-concepts','ms-operations-observability'],tags:['sla','slo','sli','reliability-targets']},
  'azure-1043':{title:'SLA-Downtime und Error Budgets',simple:'Höhere Verfügbarkeitsprozente erlauben weniger rechnerische Ausfallzeit. Die Prozentzahl sagt aber nur im Rahmen ihrer Messdefinition etwas aus. Ein Error Budget übersetzt ein SLO in den tolerierbaren Anteil nicht erfolgreicher Nutzung.',technical:'Verfügbarkeit wird über ein definiertes Zeitfenster und eine konkrete Erfolgsbedingung berechnet. 99,9 Prozent und 99,99 Prozent unterscheiden sich deutlich in tolerierter Nichtverfügbarkeit. Wartungsfenster, Ausschlüsse, Messpunkt und einzelne kritische Flows beeinflussen die Aussage.',architecture:'Teams verwenden Downtime-Tabellen als Orientierung, nicht als Ersatz für ein Health-Modell. Error Budgets helfen, Release-Geschwindigkeit gegen Reliability-Arbeit abzuwägen. Wenn das Budget aufgebraucht ist, werden riskante Änderungen reduziert und Ursachen priorisiert.',why:'Prozentwerte werden erst durch Messdefinition, Benutzerfluss und Betriebsentscheidung handlungsfähig.',examples:['Ein Team stoppt nichtkritische Releases, nachdem der Checkout-SLO sein monatliches Error Budget fast verbraucht hat.'],merksatz:'Eine Verfügbarkeitszahl ohne Messdefinition ist kein Betriebsziel.',sources:['ms-reliability-targets','ms-sla-concepts'],tags:['downtime','error-budget','availability']},
  'azure-1045':{title:'Zusammengesetzte Zuverlässigkeitsziele',simple:'Eine Anwendung besteht meist aus mehreren abhängigen Komponenten. Ihre Zuverlässigkeit ergibt sich nicht automatisch aus einer einzelnen Azure-SLA-Zahl. Entscheidend ist, welche Komponenten für einen konkreten Benutzerfluss wirklich benötigt werden.',technical:'Serielle Abhängigkeiten, parallele Alternativen, Graceful Degradation und Retry-Verhalten beeinflussen das End-to-End-Ergebnis unterschiedlich. Plattform-SLAs haben eigene Deckungsbedingungen und sind nicht pauschal multiplizierbar. Messbare SLIs am Flow validieren die tatsächliche Verfügbarkeit.',architecture:'Architekten modellieren kritische Flows, Single Points of Failure und alternative Pfade. Redundanz kann ein Ziel verbessern, aber auch neue Abhängigkeiten und Betriebsrisiken erzeugen. Die berechnete Erwartung wird durch reale Telemetrie, Tests und Incident-Daten laufend korrigiert.',why:'Nur die Flow-Sicht verhindert, dass gute Einzelkomponenten ein schwaches Gesamtsystem verdecken.',examples:['Ein Checkout bleibt trotz Ausfall der Empfehlungsfunktion verfügbar, weil diese Abhängigkeit kontrolliert degradiert und nicht zum kritischen Pfad gehört.'],merksatz:'Miss den Benutzerfluss, nicht die Summe der Produktversprechen.',sources:['ms-reliability-targets','ms-sla-concepts'],tags:['composite-reliability','critical-flows','dependencies']},
  'azure-1046':{title:'Verfügbarkeit als messbarer Anteil erfolgreicher Nutzung',simple:'Verfügbarkeit beschreibt, wie oft ein Dienst im betrachteten Zeitraum die erwartete Funktion erfüllt. Sie wird häufig als Prozentwert angegeben. Uptime allein kann Fehler oder unbrauchbar langsame Antworten übersehen.',technical:'Ein SLI definiert Ereignisse oder Zeitfenster als erfolgreich beziehungsweise nicht erfolgreich und aggregiert sie über das Beobachtungsfenster. Latenz, Erfolgsrate und Kapazität können zusätzlich zur reinen Erreichbarkeit gehören. Synthetische Tests und Anwendungstelemetrie messen näher an der Nutzerperspektive als reine Hostzustände.',architecture:'Die Messung wird an kritischen Flows, Regionen und Kundensegmenten ausgerichtet. Zu grobe Aggregate verdecken lokale Ausfälle, zu feine Ziele erzeugen unübersichtlichen Betrieb. Health Signals zeigen Zustand; Root-Cause-Analyse erklärt die Ursache mit korrelierten Logs und Traces.',why:'Was nicht aus Nutzerperspektive gemessen wird, kann trotz grüner Infrastruktur geschäftlich ausgefallen sein.',examples:['Ein Dienst gilt nur dann als verfügbar, wenn Anmeldung und Kerntransaktion innerhalb des vereinbarten Latenzziels erfolgreich sind.'],merksatz:'Verfügbarkeit misst erfolgreiche Nutzung, nicht nur laufende Ressourcen.',sources:['ms-reliability-targets','ms-operations-observability'],tags:['availability-monitoring','sli','health-model']}
};

const relationDefinitions = [
  ['monitoring-rel-001','azure-0094','azure-0098','contains','Manageability umfasst Monitoring und Operations als zentrale Betriebsfähigkeit.',['ms-cloud-operations-functions','ms-cloud-estate-monitor'],0.99],
  ['monitoring-rel-002','azure-0098','azure-0983','uses','Monitoring und Operations verwenden Azure Monitor als zentrale Signale- und Analyseplattform.',['ms-azure-monitor-overview','ms-cloud-estate-monitor'],0.99],
  ['monitoring-rel-003','azure-0983','azure-0985','integrates_with','Azure Monitor Logs verwendet Log Analytics Workspaces als primären Speicher- und Abfragerahmen für Logdaten.',['ms-monitor-logs','ms-log-analytics'],0.99],
  ['monitoring-rel-004','azure-0987','azure-0985','logs_to','Workspacebasiertes Application Insights speichert seine Log- und Trace-Telemetrie in einem Log Analytics Workspace.',['ms-application-insights','ms-monitor-logs'],0.99],
  ['monitoring-rel-005','azure-0985','azure-0984','triggers','Logabfragen in einem Log Analytics Workspace können Log-Search-Alerts auslösen, wenn ihre Bedingung erfüllt ist.',['ms-monitor-alerts','ms-log-analytics'],0.99],
  ['monitoring-rel-006','azure-0987','azure-0351','monitors','Application Insights überwacht Anwendungen auf Azure App Service durch Anwendungsinstrumentierung und korrelierte Telemetrie.',['ms-application-insights'],0.99],
  ['monitoring-rel-007','azure-0989','azure-0987','part_of','Application Performance Monitoring ist eine Kernfähigkeit von Application Insights.',['ms-application-insights'],0.99],
  ['monitoring-rel-008','azure-0990','azure-0987','part_of','Fehler- und Anomalieerkennung wird aus Application-Insights-Telemetrie abgeleitet.',['ms-application-insights'],0.98],
  ['monitoring-rel-009','azure-0983','azure-0442','monitors','Azure Monitor kann Metriken und unterstützte Logs von Virtual Networks und zugehörigen Netzwerkdiensten erfassen.',['ms-azure-monitor-overview','ms-cloud-estate-monitor'],0.96],
  ['monitoring-rel-010','azure-0983','azure-0579','monitors','Azure Monitor erfasst Plattformmetriken und konfigurierte Ressourcenlogs von Storage Accounts.',['ms-azure-monitor-overview','ms-monitor-diagnostic-settings'],0.99],
  ['monitoring-rel-011','azure-0994','azure-0993','part_of','Kategorisierte Optimierungsempfehlungen sind die zentrale Ausgabe von Azure Advisor.',['ms-advisor-overview','ms-advisor-score'],0.99],
  ['monitoring-rel-012','azure-0995','azure-0993','part_of','Die Cloud-Coach-Perspektive beschreibt die beratende, nicht automatisch entscheidende Rolle von Azure Advisor.',['ms-advisor-overview'],0.98],
  ['monitoring-rel-013','azure-0993','azure-0322','monitors','Azure Advisor analysiert unterstützte VM-Konfigurationen und Nutzungssignale für Optimierungsempfehlungen.',['ms-advisor-overview','ms-advisor-score'],0.97],
  ['monitoring-rel-014','azure-0993','azure-0351','monitors','Azure Advisor bewertet unterstützte App-Service-Konfigurationen für Reliability-, Performance-, Security- und Kostenhinweise.',['ms-advisor-overview','ms-advisor-score'],0.96],
  ['monitoring-rel-015','azure-0999','azure-1000','triggers','Relevante Service-Health-Ereignisse können gefilterte Service-Health-Alerts auslösen.',['ms-service-health-overview','ms-monitor-alerts'],0.99],
  ['monitoring-rel-016','azure-0999','azure-0322','monitors','Resource Health als Teil der Service-Health-Erfahrungen meldet den Plattformzustand unterstützter virtueller Maschinen.',['ms-service-health-overview','ms-resource-health-overview'],0.98],
  ['monitoring-rel-017','azure-0933','azure-0983','integrates_with','Defender for Cloud nutzt die gemeinsame Azure-Monitor-Datenplattform und kann Security-Signale in operative Telemetrieflüsse integrieren.',['ms-azure-monitor-overview','ms-defender-overview'],0.96],
  ['monitoring-rel-018','azure-0934','azure-0985','logs_to','Defender-for-Cloud-Signale können für Korrelation und Betriebsanalyse an einen Log Analytics Workspace exportiert werden.',['ms-azure-monitor-overview','ms-defender-overview'],0.95],
  ['monitoring-rel-019','azure-0962','azure-0983','governs','Azure Policy kann Monitoring-Baselines wie Diagnostic Settings und zulässige Konfigurationen prüfen oder bereitstellen.',['ms-policy-overview','ms-monitor-diagnostic-settings'],0.97],
  ['monitoring-rel-020','azure-0114','azure-0983','uses','Disaster-Recovery-Entscheidungen verwenden überwachte Health- und Recovery-Signale zur Auslösung und Validierung.',['ms-reliability-targets','ms-failover-failback'],0.98],
  ['monitoring-rel-021','azure-0107','azure-0983','uses','Fault Tolerance verwendet Monitoring-Signale, um Fehler zu erkennen und vorgesehene Reaktionen zu validieren.',['ms-operations-observability','ms-reliability-targets'],0.99],
  ['monitoring-rel-022','azure-0984','azure-0110','triggers','Ein qualifizierter Azure-Monitor-Alert kann in einem getesteten Runbook automatisches Failover auslösen.',['ms-monitor-alerts','ms-failover-failback'],0.95],
  ['monitoring-rel-023','azure-1042','azure-0983','depends_on','Workload-SLOs und SLA-Berichte benötigen messbare Indikatoren aus einer Monitoring- und Observability-Plattform.',['ms-reliability-targets','ms-operations-observability'],0.98],
  ['monitoring-rel-024','azure-1034','azure-0993','integrates_with','Cost Management und Azure Advisor ergänzen sich bei proaktiver Kostenanalyse und Optimierungsempfehlungen.',['ms-advisor-overview','ms-cloud-estate-monitor'],0.95]
];

for (const source of officialSources) {
  if (sourcesDocument.sources.some(item => item.id === source.id)) throw new Error(`Neue V1.8-Quellen-ID kollidiert mit Bestand: ${source.id}`);
  sourcesDocument.sources.push(source);
}
const typeById = new Map(typesDocument.relation_types.map(type => [type.id, type]));

for (const [id, enrichment] of Object.entries(E)) {
  const node = nodeById.get(id);
  if (!node) throw new Error(`Pilotknoten fehlt: ${id}`);
  if (node.metadata?.enrichment) throw new Error(`${id}: Bereits in V${node.metadata.enrichment.version} angereichert und gegen Überschreiben geschützt.`);
  const originalTitle = node.title;
  node.title = enrichment.title || node.title;
  node.description = {simple:enrichment.simple,technical:enrichment.technical,architecture:enrichment.architecture};
  node.why_important = enrichment.why;
  node.examples = enrichment.examples || [];
  node.merksatz = enrichment.merksatz || '';
  node.analogy = enrichment.analogy || '';
  node.sources = [...new Set([...(node.sources || []), ...enrichment.sources])];
  node.tags = [...new Set([...(node.tags || []), ...(enrichment.tags || []), 'monitoring-operations-pilot-v1.8'])];
  node.aliases = [...new Set([...(node.aliases || []), ...(originalTitle !== node.title ? [originalTitle] : [])])];
  node.metadata = {...node.metadata,status:'published',audit_flags:(node.metadata.audit_flags || []).filter(flag => flag !== 'description_generated_from_title'),enrichment:{version:'1.8',pilot:'monitoring-observability-operations-architecture',content_standard:'1.0',reviewed_at:today,source_policy:'official_microsoft_only'}};
  node.updated_at = today;
}

const existingRelationIds = new Set(relationsDocument.relations.map(relation => relation.id));
const existingTriples = new Set(relationsDocument.relations.map(relation => `${relation.source}|${relation.type}|${relation.target}`));
for (const [id, source, target, type, explanation, sources, confidence] of relationDefinitions) {
  if (existingRelationIds.has(id)) throw new Error(`${id}: Relations-ID kollidiert mit Bestand.`);
  if (!nodeById.has(source) || !nodeById.has(target)) throw new Error(`${id}: Endpunkt fehlt.`);
  const triple = `${source}|${type}|${target}`;
  if (existingTriples.has(triple)) throw new Error(`${id}: Relation ist bereits vorhanden: ${triple}`);
  const typeDefinition = typeById.get(type);
  if (!typeDefinition) throw new Error(`${id}: Typ ${type} fehlt.`);
  for (const sourceId of sources) if (!sourcesDocument.sources.some(item => item.id === sourceId)) throw new Error(`${id}: Quelle ${sourceId} fehlt.`);
  const relation = {schema_version:'1.1',id,source,target,type,inverse_type:typeDefinition.inverse_type,explanation,sources,confidence,status:'accepted',created_by:'knowledge_enrichment_v1.8',created_at:today,reviewed_at:today};
  relationsDocument.relations.push(relation);
  existingRelationIds.add(id);
  existingTriples.add(triple);
  for (const nodeId of [source,target]) {
    const node = nodeById.get(nodeId);
    node.relations = [...new Set([...(node.relations || []), id])];
  }
}

nodesDocument.meta = {...nodesDocument.meta,enrichment_version:'1.8',monitoring_operations_pilot:{node_count:Object.keys(E).length,relation_count:relationDefinitions.length,content_standard:'1.0',reviewed_at:today,focus:'monitoring_observability_operations_architecture',lifecycle:'Plan → Build → Secure → Monitor → Operate → Improve'}};
relationsDocument.meta = {...relationsDocument.meta,relation_count:relationsDocument.relations.length,enrichment_version:'1.8',monitoring_operations_relation_count:relationDefinitions.length};
sourcesDocument.meta = {...sourcesDocument.meta,count:sourcesDocument.sources.length,generated_at:today,enrichment_version:'1.8'};
typesDocument.meta = {...typesDocument.meta,type_count:typesDocument.relation_types.length,updated_at:today,enrichment_version:'1.8'};

write('nodes.json',nodesDocument);
write('relations.json',relationsDocument);
write('sources.json',sourcesDocument);
write('relation-types.json',typesDocument);

console.log(JSON.stringify({enriched_nodes:Object.keys(E).length,explanation_texts:Object.keys(E).length*3,added_relations:relationDefinitions.length,total_relations:relationsDocument.relations.length,added_relation_types:0,total_relation_types:typesDocument.relation_types.length,added_sources:officialSources.length,total_sources:sourcesDocument.sources.length},null,2));
