import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonical = path.join(project, 'data/canonical');
const today = '2026-08-11';
const read = name => JSON.parse(fs.readFileSync(path.join(canonical, name), 'utf8'));
const write = (name, value) => fs.writeFileSync(path.join(canonical, name), `${JSON.stringify(value, null, 2)}\n`);

const nodesDocument = read('nodes.json');
const relationsDocument = read('relations.json');
const sourcesDocument = read('sources.json');
const typesDocument = read('relation-types.json');
const nodeById = new Map(nodesDocument.nodes.map(node => [node.id, node]));

const officialSources = [
  {id:'ms-storage-intro',title:'Introduction to Azure Storage',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-account',title:'Storage account overview',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-authorization',title:'Authorize access to data in Azure Storage',url:'https://learn.microsoft.com/en-us/azure/storage/common/authorize-data-access',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-sas',title:'Grant limited access with shared access signatures (SAS)',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-private-endpoints',title:'Use private endpoints for Azure Storage',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-encryption',title:'Azure Storage encryption for data at rest',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-service-encryption',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-redundancy',title:'Azure Storage redundancy',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-storage-disaster-recovery',title:'Azure Storage disaster recovery planning and failover',url:'https://learn.microsoft.com/en-us/azure/storage/common/storage-disaster-recovery-guidance',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-blob-overview',title:'Introduction to Azure Blob Storage',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-blob-access-tiers',title:'Access tiers for blob data',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-blob-lifecycle',title:'Azure Blob Storage lifecycle management overview',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-blob-data-protection',title:'Data protection overview for Azure Blob Storage',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/data-protection-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-files-overview',title:'Introduction to Azure Files',url:'https://learn.microsoft.com/en-us/azure/storage/files/storage-files-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-file-sync',title:'Introduction to Azure File Sync',url:'https://learn.microsoft.com/en-us/azure/storage/file-sync/file-sync-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-queue-overview',title:'Introduction to Azure Queue Storage',url:'https://learn.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-table-overview',title:'Introduction to Azure Table storage',url:'https://learn.microsoft.com/en-us/azure/storage/tables/table-storage-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-data-lake-overview',title:'Introduction to Azure Data Lake Storage',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-data-box',title:'Microsoft Azure Data Box overview',url:'https://learn.microsoft.com/en-us/azure/databox/data-box-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-azure-migrate',title:'About Azure Migrate',url:'https://learn.microsoft.com/en-us/azure/migrate/migrate-services-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-azure-sql-overview',title:'What is Azure SQL?',url:'https://learn.microsoft.com/en-us/azure/azure-sql/azure-sql-iaas-vs-paas-what-is-overview?view=azuresql',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-cosmos-resource-model',title:'Databases, containers, and items in Azure Cosmos DB',url:'https://learn.microsoft.com/en-us/azure/cosmos-db/resource-model',publisher:'Microsoft Learn',accessed_at:today,type:'official'},
  {id:'ms-dms-overview',title:'What is Azure Database Migration Service?',url:'https://learn.microsoft.com/en-us/azure/dms/dms-overview',publisher:'Microsoft Learn',accessed_at:today,type:'official'}
];

const E = {
  'azure-0566':{title:'Azure Storage',simple:'Azure Storage ist die verwaltete Speicherplattform von Azure für Dateien, Objekte, Nachrichten, Tabellen und Datenträger. Sie wird verwendet, wenn Anwendungen Daten dauerhaft, skalierbar und sicher in der Cloud ablegen sollen. Azure übernimmt die zugrunde liegende Speicherhardware und deren Betrieb.',technical:'Azure Storage stellt getrennte Datendienste über Storage Accounts und dienstspezifische Endpunkte bereit. Daten werden serverseitig verschlüsselt, mehrfach repliziert und über REST, SDKs, CLI oder dienstspezifische Protokolle angesprochen. Zugriffsschutz entsteht aus Netzwerkregeln, Private Endpoints und Autorisierung über Microsoft Entra ID, SAS oder Shared Key.',architecture:'Architekten wählen zuerst das Datenmodell: Objekt, Datei, Nachricht, Schlüssel-Wert oder Blockgerät. Danach werden Accountgrenzen, Region, Redundanz, Netzwerkpfad, Identität, Schutzfunktionen und Kostenmodell festgelegt. Azure betreibt die Plattform; der Kunde verantwortet Datenklassifikation, Berechtigungen, Schlüsseloptionen, Wiederherstellungsziele und Lifecycle-Regeln.',why:'Fast jede Cloud-Anwendung benötigt dauerhafte Daten, deren Verfügbarkeit, Schutz, Zugriff und Kosten bewusst gestaltet werden müssen.',examples:['Ein Webshop legt Produktbilder in Blob Storage ab, tauscht Aufträge über Queue Storage aus und verwendet Managed Disks für seine VMs.'],merksatz:'Storage-Architektur entscheidet Datenform, Zugriff, Schutz, Redundanz und Lebenszyklus gemeinsam.',sources:['ms-storage-intro','ms-storage-authorization','ms-storage-encryption','ms-storage-redundancy'],tags:['storage-architecture','data-durability','data-protection']},
  'azure-0571':{title:'Azure Blob Storage',simple:'Blob Storage speichert große Mengen unstrukturierter Daten wie Bilder, Videos, Dokumente, Backups oder Logs. Anwendungen greifen auf diese Objekte typischerweise über HTTP oder HTTPS zu. Blobs liegen in Containern innerhalb eines Storage Accounts.',technical:'Blob Storage bietet Block-, Append- und Page-Blobs mit REST-APIs und SDKs. Netzwerkzugriff kann öffentlich, per Firewall oder über Private Endpoint erfolgen; Autorisierung erfolgt vorzugsweise mit Microsoft Entra ID und RBAC, alternativ zeitlich begrenzt per SAS oder über Account Keys. Access Tiers, Lifecycle Management, Versioning und Soft Delete steuern Kosten und Wiederherstellung.',architecture:'Blob Storage ist die Standardwahl für skalierbaren Objektspeicher und eignet sich nicht als vollwertiges relationales Dateisystem oder Datenbank. Account- und Containergrenzen sollten Sicherheits-, Lifecycle- und Complianceanforderungen trennen. Private Access erhöht Isolation, benötigt aber DNS- und Netzwerkdesign; Schutzfunktionen erhöhen Kapazitätskosten.',why:'Blob Storage entkoppelt große Datenmengen von Compute und ist Grundlage für Content, Archive, Backupdaten und Analytics.',examples:['Eine App Service-Anwendung speichert Uploads in einem privaten Blob-Container und greift mit Managed Identity darauf zu.'],merksatz:'Blobs sind Objekte für skalierbare Daten, nicht gemeinsam gemountete Dateien oder relationale Datensätze.',sources:['ms-blob-overview','ms-storage-authorization','ms-storage-private-endpoints','ms-blob-data-protection'],tags:['object-storage','private-access','blob-protection']},
  'azure-0574':{title:'Blob Access Tiers',simple:'Access Tiers ordnen Blobdaten nach ihrer Nutzungshäufigkeit ein. Häufig genutzte Daten liegen im Hot Tier, seltene Daten in Cool und langfristig kaum benötigte Daten im Archive Tier. Die Wahl verschiebt Kosten zwischen Speichern und Abrufen.',technical:'Hot und Cool sind Online-Tiers mit unmittelbarem Zugriff, während Archive offline ist und vor Nutzung rehydriert werden muss. Tierwechsel können manuell oder regelbasiert per Lifecycle Management erfolgen. Mindestaufbewahrung, Abruf-, Transaktions- und vorzeitige Löschkosten gehören zur Gesamtkostenrechnung.',architecture:'Die Tierwahl basiert auf Zugriffsmuster, benötigter Abrufzeit und Aufbewahrungsdauer, nicht nur auf dem günstigsten Preis pro Gigabyte. Lifecycle-Regeln reduzieren manuelle Arbeit, müssen aber mit Backup, Versioning, Soft Delete und rechtlicher Aufbewahrung abgestimmt werden. Unvorhersehbare Zugriffe können Cool oder Archive wirtschaftlich unattraktiv machen.',why:'Bei großen Datenmengen bestimmt der Datenlebenszyklus oft mehr Kosten als die reine Kapazität.',examples:['Produktbilder bleiben 30 Tage im Hot Tier, wechseln danach in Cool und werden nach zwei Jahren regelbasiert gelöscht.'],merksatz:'Je kälter das Tier, desto günstiger das Lagern und desto teurer oder langsamer der Zugriff.',sources:['ms-blob-access-tiers','ms-blob-lifecycle'],tags:['access-tier','lifecycle-management','storage-cost']},
  'azure-0575':{title:'Hot Tier',simple:'Das Hot Tier ist für Blobdaten gedacht, die häufig gelesen oder verändert werden. Es bietet unmittelbaren Online-Zugriff. Dafür sind die laufenden Speicherkosten höher als bei kälteren Tiers.',technical:'Hot ist ein Online-Access-Tier für Block Blobs mit niedrigen Zugriffskosten und höheren Kapazitätskosten. Daten können direkt gelesen und geschrieben werden und lassen sich später in andere unterstützte Tiers verschieben. Redundanz wird unabhängig vom Access Tier am Storage Account gewählt.',architecture:'Hot passt zu aktiven Anwendungsdaten, neuen Uploads und Arbeitsbeständen mit häufigen Transaktionen. Es vermeidet Rehydratisierung, ist für dauerhaft selten gelesene Daten aber oft unnötig teuer. Ein Lifecycle-Übergang sollte erst erfolgen, wenn das Zugriffsmuster stabil genug ist.',why:'Die richtige Hot-Nutzung hält aktive Daten schnell verfügbar, ohne alle historischen Daten zum höchsten Speicherpreis vorzuhalten.',examples:['Die aktuellen Produktbilder eines Onlineshops liegen im Hot Tier und werden direkt an die Webanwendung ausgeliefert.'],merksatz:'Hot bedeutet sofort verfügbar und günstig im Zugriff, aber teurer in der Kapazität.',sources:['ms-blob-access-tiers'],tags:['hot-tier','online-data','frequent-access']},
  'azure-0576':{title:'Cool Tier',simple:'Das Cool Tier speichert Blobdaten, die selten genutzt werden, aber weiterhin sofort verfügbar sein sollen. Die Speicherkosten sind niedriger als im Hot Tier. Abrufe und bestimmte Operationen kosten dafür mehr.',technical:'Cool ist ein Online-Tier mit unmittelbarem Lesen und Schreiben, jedoch höherem Zugriffspreis und einer Mindestaufbewahrungslogik. Es kann als Standardtier oder pro Blob gesetzt und durch Lifecycle-Regeln erreicht werden. Häufige Zugriffe oder frühe Löschung können den Kostenvorteil aufheben.',architecture:'Cool eignet sich für kurzfristige Backups, ältere Inhalte und selten genutzte Daten mit niedriger Latenzanforderung. Architekten sollten Zugriffsfrequenz, Transaktionsvolumen und erwartete Lebensdauer modellieren. Für Daten mit stündlichen Zugriffen bleibt Hot meist wirtschaftlicher.',why:'Cool senkt Kapazitätskosten, ohne Daten für den Abruf erst aus einem Offline-Archiv zurückholen zu müssen.',examples:['Abgeschlossene Monatsreports wechseln nach 30 Tagen von Hot nach Cool, bleiben aber für Audits sofort abrufbar.'],merksatz:'Cool spart beim Lagern, nicht automatisch bei häufigem Lesen.',sources:['ms-blob-access-tiers'],tags:['cool-tier','infrequent-access','online-data']},
  'azure-0578':{title:'Archive Tier',simple:'Das Archive Tier ist für Blobdaten gedacht, die sehr selten gebraucht und lange aufbewahrt werden. Es bietet die niedrigsten Speicherkosten. Vor dem Lesen müssen Daten jedoch rehydriert werden, was Stunden dauern kann.',technical:'Archive ist ein Offline-Tier für unterstützte Block Blobs. Ein archivierter Blob kann weder gelesen noch geändert werden, bis er in ein Online-Tier rehydriert wurde; Abrufpriorität, Transaktionen und vorzeitige Löschung verursachen zusätzliche Kosten. Nicht jede Redundanz- oder Featurekombination unterstützt Archive.',architecture:'Archive passt zu gesetzlicher Langzeitaufbewahrung und historischen Daten mit großzügigem Recovery Time Objective. Es ist ungeeignet für operative Backups oder Incident-Szenarien mit schneller Wiederherstellung. Lifecycle-, DR- und Failoverplanung müssen berücksichtigen, dass archivierte Daten nicht unmittelbar einsatzbereit sind.',why:'Archive ermöglicht sehr kostengünstige Langzeitaufbewahrung, erzwingt aber eine bewusste Entscheidung über Wiederherstellungszeit.',examples:['Abgeschlossene Rohdaten eines Forschungsprojekts werden sieben Jahre im Archive Tier gehalten und nur bei einer Prüfung rehydriert.'],merksatz:'Archive ist billig im Ruhezustand, aber langsam und kostenpflichtig beim Zurückholen.',sources:['ms-blob-access-tiers','ms-storage-disaster-recovery'],tags:['archive-tier','long-term-retention','rehydration']},
  'azure-0579':{title:'Storage Account',simple:'Ein Storage Account ist der Verwaltungs- und Sicherheitsrahmen für Azure-Storage-Daten. Er enthält Dienstendpunkte für Blobs, Files, Queues und Tables und besitzt einen weltweit eindeutigen Namen. Einstellungen für Region, Redundanz, Netzwerk und Zugriff wirken auf die enthaltenen Dienste.',technical:'Der Storage Account stellt einen eindeutigen Namespace und getrennte Datenendpunkte bereit. Auf Account-Ebene werden Typ, Performance, Redundanz, Verschlüsselungsoptionen, Firewall, Private Endpoints und Shared-Key-Zulassung konfiguriert; Datenzugriffe werden über Entra ID/RBAC, SAS oder Account Keys autorisiert. Account Keys geben weitreichenden Zugriff und sollten zugunsten identitätsbasierter Verfahren vermieden oder streng geschützt werden.',architecture:'Accountgrenzen sind zugleich Blast-Radius-, Policy-, Netzwerk-, Schlüssel-, Quota- und teilweise Kosten-/Lifecycle-Grenzen. Workloads mit unterschiedlichen Sicherheits-, Verfügbarkeits- oder Betriebsanforderungen sollten nicht blind einen Account teilen. Private Endpoints vermeiden öffentliche Datenpfade, benötigen aber pro Storage-Dienst passende Endpunkte und DNS-Auflösung.',why:'Eine falsche Accountgrenze koppelt Daten mit unterschiedlichen Schutz- und Betriebsanforderungen und vergrößert den Auswirkungsradius.',examples:['Produktion und Entwicklung erhalten getrennte Storage Accounts; die Produktionsanwendung nutzt Managed Identity und einen privaten Blob-Endpunkt.'],merksatz:'Der Storage Account ist nicht nur ein Behälter, sondern die zentrale Architekturgrenze für Speicher.',sources:['ms-storage-account','ms-storage-authorization','ms-storage-sas','ms-storage-private-endpoints'],tags:['storage-account','account-boundary','shared-key','sas']},
  'azure-0583':{title:'Blob Container',simple:'Ein Blob Container gruppiert Blobs innerhalb eines Storage Accounts. Er schafft einen Namensraum für Objekte und kann eine sinnvolle Grenze für Zugriff und Verwaltung bilden. Container sind keine klassischen Ordner, auch wenn Blobnamen Pfade abbilden können.',technical:'Container gehören zum Blob Service eines Storage Accounts und enthalten Block-, Append- oder Page-Blobs. Berechtigungen können über Azure RBAC, SAS und je nach Konfiguration anonymen Lesezugriff gesteuert werden. Lifecycle-Regeln lassen sich mit Präfixen oder Blob Index Tags auf Teilmengen begrenzen.',architecture:'Container sollten nach Zugriffsmuster, Datenverantwortung, Lifecycle und Schutzbedarf geschnitten werden. Zu wenige Container erschweren differenzierte Policies; zu viele erhöhen Verwaltung und Berechtigungsaufwand. Öffentlicher Zugriff muss eine explizite Ausnahme sein und darf nicht mit einem SAS verwechselt werden.',why:'Container strukturieren Objektdaten und ermöglichen kontrollierbare Grenzen für Berechtigungen und Lebenszyklen.',examples:['Ein Medien-Account verwendet getrennte Container für private Uploads, freigegebene Inhalte und revisionspflichtige Archive.'],merksatz:'Der Account ist die Architekturgrenze, der Container organisiert Blobs innerhalb dieser Grenze.',sources:['ms-blob-overview','ms-storage-authorization','ms-blob-lifecycle'],tags:['blob-container','authorization-scope','data-organization']},
  'azure-0584':{title:'Storage-Redundanz',simple:'Storage-Redundanz hält mehrere Kopien von Daten, damit Hardware-, Zonen- oder Regionsausfälle nicht sofort zu Datenverlust führen. Azure bietet dafür LRS, ZRS, GRS und GZRS. Mehr Schutz kostet mehr und ersetzt keine vollständige Backupstrategie.',technical:'LRS repliziert synchron in einer lokalen Regionseinheit, ZRS synchron über Availability Zones. GRS kopiert zusätzlich asynchron in eine zweite Region; GZRS kombiniert Zonenredundanz in der Primärregion mit Georeplikation. Read-Access-Varianten erlauben Lesezugriff auf die sekundäre Kopie; Failoververhalten und unterstützte Features unterscheiden sich.',architecture:'Die Auswahl folgt Ausfallmodell, RPO, RTO, Datenresidenz, Kosten und Dienstunterstützung. ZRS schützt vor Zonenausfall, aber nicht vor Regionsverlust; Georedundanz verbessert DR, kann wegen asynchroner Replikation dennoch Datenverlust bei ungeplantem Failover bedeuten. Redundanz schützt Infrastrukturkopien, während Backup gegen längere oder logisch getrennte Verlustszenarien absichert.',why:'Die Redundanzoption bestimmt, gegen welche physische Ausfallklasse die Datenplattform ausgelegt ist.',examples:['Ein regionaler Geschäftsdienst nutzt ZRS; ein kritischer Datensatz mit regionalem DR-Plan nutzt GZRS und getestetes Failover.'],merksatz:'Redundanz hält Kopien verfügbar; Backup hält Wiederherstellungspunkte getrennt.',sources:['ms-storage-redundancy','ms-storage-disaster-recovery','ms-blob-data-protection'],tags:['redundancy','availability','durability','disaster-recovery']},
  'azure-0585':{title:'LRS – Locally Redundant Storage',simple:'LRS hält mehrere synchrone Datenkopien an einem einzelnen physischen Standort innerhalb der Primärregion. Es schützt vor lokalen Hardwarefehlern. Gegen den Ausfall einer Availability Zone oder ganzen Region ist es nicht ausgelegt.',technical:'Locally Redundant Storage repliziert Daten synchron innerhalb eines Datacenterstandorts in der gewählten Region. Schreibvorgänge gelten nach Replikation der lokalen Kopien als erfolgreich. LRS hat die geringsten Redundanzkosten, aber den kleinsten geografischen Fehlerschutz.',architecture:'LRS eignet sich für reproduzierbare, unkritische oder anderweitig gesicherte Daten und kostenorientierte Workloads. Es sollte nur gewählt werden, wenn Zonen- und Regionsausfall durch Anwendung, Backup oder akzeptiertes Risiko abgedeckt sind. Für geschäftskritische produktive Daten ist die Kostenersparnis gegen höhere Wiederherstellungsverantwortung abzuwägen.',why:'LRS ist die Basisoption und macht sichtbar, welches Ausfallrisiko zugunsten niedriger Kosten akzeptiert wird.',examples:['Temporäre Verarbeitungsergebnisse liegen in LRS, weil sie aus den Quelldaten erneut erzeugt werden können.'],merksatz:'LRS schützt vor lokaler Hardware, nicht vor Zonen- oder Regionsausfall.',sources:['ms-storage-redundancy'],tags:['lrs','local-redundancy','cost-tradeoff']},
  'azure-0587':{title:'ZRS – Zone-Redundant Storage',simple:'ZRS verteilt synchrone Datenkopien über mehrere Availability Zones einer Region. Dadurch bleiben Daten auch beim Ausfall einer Zone verfügbar. Die Daten verlassen dabei nicht die primäre Region.',technical:'Zone-Redundant Storage repliziert synchron über getrennte physische Zonen mit unabhängiger Strom-, Kühlungs- und Netzwerkinfrastruktur. Anwendungen verwenden weiterhin denselben Storage-Endpunkt; Azure übernimmt die Replikation und den Zonenfehler. Feature- und Regionsunterstützung müssen für den gewählten Accounttyp geprüft werden.',architecture:'ZRS ist eine starke Standardwahl für regionale Hochverfügbarkeit, wenn Datenresidenz in einer Region bleiben soll. Es schützt nicht vor einem vollständigen Regionsausfall und benötigt für dieses Szenario zusätzlich DR oder Georedundanz. Gegenüber LRS entstehen höhere Kosten, dafür sinkt die Abhängigkeit von einem Standort.',why:'ZRS schützt zustandsbehaftete Daten gegen Zonenausfälle, ohne dass die Anwendung selbst Speicher replizieren muss.',examples:['Ein geschäftskritischer File Share verwendet ZRS, damit ein Zonenausfall den regionalen Dateizugriff nicht unterbricht.'],merksatz:'ZRS verteilt synchron über Zonen, aber nicht über Regionen.',sources:['ms-storage-redundancy'],tags:['zrs','zone-redundancy','high-availability']},
  'azure-0589':{title:'GRS – Geo-Redundant Storage',simple:'GRS hält lokale Kopien in der Primärregion und repliziert Daten zusätzlich in eine zweite Region. Es schützt damit auch gegen schwere regionale Ausfälle. Die Replikation in die zweite Region erfolgt asynchron.',technical:'Geo-Redundant Storage verwendet LRS in Primär- und Sekundärregion und überträgt Änderungen asynchron in die gekoppelte Sekundärregion. Ohne Read-Access-Variante ist der sekundäre Endpunkt normalerweise nicht für Anwendungen lesbar. Bei ungeplantem Failover können noch nicht replizierte Schreibvorgänge verloren gehen.',architecture:'GRS ist sinnvoll, wenn regionales Disaster Recovery wichtiger ist als Zonenresilienz in der Primärregion oder ZRS nicht unterstützt wird. RPO und Failoverprozess müssen wegen asynchroner Replikation explizit geplant und getestet werden. Georeplikation ist weder Anwendungsfailover noch Schutz vor versehentlicher logischer Löschung.',why:'GRS erweitert den Schutzradius von lokaler Infrastruktur auf regionale Katastrophen.',examples:['Ein Archiv-Account nutzt GRS und einen dokumentierten Failoverprozess für den Verlust der Primärregion.'],merksatz:'GRS kopiert in eine zweite Region, aber die letzte Änderung kann beim Notfall noch unterwegs sein.',sources:['ms-storage-redundancy','ms-storage-disaster-recovery'],tags:['grs','geo-redundancy','rpo']},
  'azure-0592':{title:'GZRS – Geo-Zone-Redundant Storage',simple:'GZRS kombiniert Zonenredundanz in der Primärregion mit einer zusätzlichen Kopie in einer zweiten Region. Es schützt sowohl gegen den Ausfall einer Zone als auch gegen regionale Katastrophen. Dafür ist es teurer und nicht in jeder Kombination verfügbar.',technical:'Geo-Zone-Redundant Storage schreibt synchron über Availability Zones der Primärregion und repliziert asynchron in eine Sekundärregion, in der die Daten lokal redundant gespeichert werden. RA-GZRS kann zusätzlich Lesezugriff auf den sekundären Endpunkt ermöglichen. Failover, Featureunterstützung und letzter Synchronisationsstand müssen beachtet werden.',architecture:'GZRS passt zu kritischen Daten mit hohen Anforderungen an regionale Verfügbarkeit und Disaster Recovery. Es reduziert Infrastruktur-Ausfallrisiken, ersetzt aber weder anwendungsseitiges Multi-Region-Design noch Backup, Wiederherstellungstests und Datenresidenzprüfung. Der Mehrpreis ist gegen den Geschäftsschaden eines Zonen- oder Regionsausfalls zu bewerten.',why:'GZRS bietet den breitesten integrierten Redundanzschutz der vier Grundmodelle.',examples:['Ein kundenkritischer Storage Account nutzt GZRS, während Anwendung und Runbook auch den regionalen Failover abdecken.'],merksatz:'GZRS schützt zuerst zonenweit und kopiert zusätzlich regionsweit.',sources:['ms-storage-redundancy','ms-storage-disaster-recovery'],tags:['gzrs','zone-and-geo-redundancy','business-continuity']},
  'azure-0596':{title:'Azure Files',simple:'Azure Files stellt verwaltete Dateifreigaben in der Cloud bereit. Anwendungen und Benutzer können sie über bekannte Protokolle wie SMB oder NFS einbinden. Mehrere Systeme können gemeinsam auf dieselben Dateien zugreifen.',technical:'Azure Files läuft im File Service eines Storage Accounts und bietet SMB-, NFS- und REST-Zugriff abhängig von Account- und Sharekonfiguration. Identitätsbasierte SMB-Autorisierung, SAS oder Shared Key sowie Netzwerkregeln und Private Endpoints steuern den Zugriff. Snapshots, Soft Delete, Backup und Redundanzoptionen unterstützen Wiederherstellung und Verfügbarkeit.',architecture:'Azure Files eignet sich für Lift-and-Shift-Anwendungen, gemeinsam genutzte Konfigurationen und hybride Fileserver. Gegenüber Blob Storage bietet es Dateifreigabe-Semantik, ist aber an Protokoll-, Netzwerk- und Performancegrenzen gebunden. Architekten müssen Sharegröße, IOPS, Authentifizierung, Port-/DNS-Erreichbarkeit, Backup und DR gemeinsam planen.',why:'Azure Files ermöglicht gemeinsame Dateispeicherung ohne eigenen Fileserver-Cluster.',examples:['Mehrere VMs binden dieselbe private SMB-Freigabe für gemeinsam genutzte Anwendungsdateien ein.'],merksatz:'Azure Files ist eine gemountete Freigabe; Blob Storage ist ein Objektdienst.',sources:['ms-files-overview','ms-storage-private-endpoints','ms-blob-data-protection'],tags:['azure-files','smb','nfs','shared-files']},
  'azure-0601':{title:'Azure File Sync',simple:'Azure File Sync verbindet Windows-File-Server mit einer zentralen Azure-Files-Freigabe. Häufig benötigte Dateien können lokal bleiben, während seltene Daten in Azure liegen. So bleibt die gewohnte lokale Dateifreigabe erhalten.',technical:'Ein Storage Sync Service gruppiert Sync Groups mit einem Azure File Share als Cloud Endpoint und registrierten Windows-Serverpfaden als Server Endpoints. Der Agent synchronisiert Änderungen; Cloud Tiering ersetzt selten genutzte lokale Dateien durch Platzhalter und lädt Inhalte bei Bedarf nach. Betrieb umfasst Agentpflege, Netzwerk, Konfliktbehandlung, Quotas und DR-Abhängigkeiten.',architecture:'File Sync passt zu hybriden Standorten, die lokale SMB-Performance und zentrale Cloudkopien benötigen. Es ist kein beliebiger Multi-Master-Dateidienst und erfordert sorgfältige Planung für Namespace, Bandbreite, Backup und regionales Failover. Vollständige Cloudmigration ohne lokale Abhängigkeit kann Azure Files direkt einfacher machen.',why:'File Sync modernisiert bestehende Fileserver schrittweise, ohne alle Benutzer und Anwendungen sofort umzustellen.',examples:['Drei Niederlassungen cachen aktive Projektdateien lokal und synchronisieren den gemeinsamen Datenbestand in eine Azure-Files-Freigabe.'],merksatz:'Azure Files ist der Cloud-Hub, Windows Server der lokale Cache.',sources:['ms-file-sync','ms-files-overview','ms-storage-disaster-recovery'],tags:['file-sync','hybrid-storage','cloud-tiering']},
  'azure-0616':{title:'Azure Data Lake Storage',simple:'Azure Data Lake Storage speichert sehr große Mengen roher und aufbereiteter Daten für Analysen. Es baut auf Blob Storage auf und ergänzt eine hierarchische Ordnerstruktur. Analysewerkzeuge können dadurch effizient mit großen Datenbeständen arbeiten.',technical:'Data Lake Storage aktiviert einen hierarchischen Namespace im Storage Account und kombiniert Blob-Skalierung mit Datei- und Verzeichnissemantik sowie ACLs. Anwendungen nutzen Blob- oder DFS-Endpunkte, SDKs und kompatible Analytics-Dienste. Private Endpoints müssen bei manchen Workflows für beide Endpunkttypen geplant werden.',architecture:'Data Lake Storage ist die Speicherbasis für Lakehouse-, Data-Engineering- und Analytics-Plattformen, nicht automatisch deren Katalog, Governance oder Compute-Schicht. Zonen, Dateiformate, Partitionierung, Zugriffsmodell und Lebenszyklus bestimmen Leistung und Betrieb. HNS bringt Analyticsvorteile, kann aber die Unterstützung einzelner Blobfeatures beeinflussen.',why:'Ein Data Lake entkoppelt langlebige Unternehmensdaten von wechselnden Analyse- und Compute-Werkzeugen.',examples:['Rohdaten landen unverändert in einer Ingestion-Zone und werden später in kuratierte Parquet-Datensätze für Analytics transformiert.'],merksatz:'Data Lake Storage ist Blob Storage mit Analytics-orientierter Dateisystemsemantik.',sources:['ms-data-lake-overview','ms-storage-private-endpoints','ms-storage-authorization'],tags:['data-lake','analytics-storage','hierarchical-namespace']},
  'azure-0624':{title:'Azure Queue Storage',simple:'Queue Storage speichert Nachrichten, die später von einer Anwendung verarbeitet werden. Sender und Empfänger müssen nicht gleichzeitig laufen. Dadurch lassen sich Anwendungsteile entkoppeln und Lastspitzen abfedern.',technical:'Eine Queue im Storage Account enthält per HTTP/HTTPS adressierbare Nachrichten, die Clients senden, abrufen, aktualisieren und löschen. Die Verarbeitung verwendet Sichtbarkeitstimeouts und sollte idempotent gestaltet werden, weil eine exakte Einmalzustellung nicht zugesichert wird. Nachrichtengröße und erweiterte Messagingfunktionen sind begrenzt.',architecture:'Queue Storage ist eine kostengünstige Wahl für einfache asynchrone Work-Queues mit sehr großem Backlog. Für Topics, Sessions, Transaktionen, strikte Reihenfolge oder komplexes Enterprise Messaging ist Azure Service Bus meist geeigneter. Architekten planen Retry, Poison Messages, Idempotenz, Monitoring und Aufbewahrung in der Anwendung.',why:'Queues verhindern, dass ein langsamer oder vorübergehend ausgefallener Verarbeitungsschritt den gesamten Prozess blockiert.',examples:['Ein Webshop legt Bestellungen in einer Queue ab; skalierbare Worker verarbeiten sie unabhängig vom Checkout.'],merksatz:'Die Queue entkoppelt Tempo und Verfügbarkeit von Sender und Empfänger.',sources:['ms-queue-overview','ms-storage-intro'],tags:['queue-storage','asynchronous-processing','decoupling']},
  'azure-0632':{title:'Azure Table Storage',simple:'Table Storage ist ein einfacher NoSQL-Schlüssel-Wert-Speicher für strukturierte, aber schemalose Daten. Datensätze können unterschiedliche Eigenschaften besitzen. Der Dienst eignet sich für große Mengen einfacher Einträge und schnelle Zugriffe über Schlüssel.',technical:'Tabellen enthalten Entities mit PartitionKey, RowKey, Timestamp und frei wählbaren Properties. PartitionKey und RowKey bilden gemeinsam den eindeutigen Schlüssel; das Partitionsdesign bestimmt Skalierung, Abfragen und atomare Batchoperationen. Komplexe Joins, relationale Constraints und klassische SQL-Funktionen fehlen.',architecture:'Table Storage passt zu kostensensitiven Key-Value- und Metadatenszenarien mit bekannten Zugriffspfaden. Das Datenmodell muss von den Abfragen aus entworfen und häufig denormalisiert werden. Wenn globale Verteilung, stärkere SLAs, automatische Sekundärindizes oder mehrere APIs benötigt werden, ist Azure Cosmos DB zu prüfen.',why:'Table Storage bietet einen einfachen und günstigen NoSQL-Dienst, wenn eine relationale Datenbank unnötig wäre.',examples:['Eine Anwendung speichert Gerätestatus mit Kundennummer als PartitionKey und Geräte-ID als RowKey.'],merksatz:'Bei Table Storage entscheidet der Schlüssel über Skalierung und Abfragefähigkeit.',sources:['ms-table-overview','ms-storage-intro'],tags:['table-storage','nosql','partition-key']},
  'azure-0637':{title:'Datenmigration nach Azure',simple:'Datenmigration überführt bestehende Daten kontrolliert in Azure-Zieldienste. Je nach Datenmenge, Bandbreite und zulässiger Unterbrechung erfolgt sie online oder mit einem physischen Gerät. Vor dem Transfer müssen Ziel, Sicherheit und Validierung feststehen.',technical:'Onlinepfade verwenden Netzwerktransfer, AzCopy, Datenbank- oder Migrationsdienste; Offlinepfade wie Data Box transportieren verschlüsselte Geräte. Eine Migration umfasst Discovery, Assessment, Mapping, initiale Kopie, Delta-Synchronisierung, Cutover und Validierung. Durchsatz, Datenkonsistenz, Verschlüsselung und Rückfallplan sind operative Kernpunkte.',architecture:'Die Wahl folgt Datenvolumen, Änderungsrate, Bandbreite, Downtime, Compliance und Zielmodell. Ein reines Kopieren modernisiert weder Schema noch Anwendung und kann versteckte Abhängigkeiten übernehmen. Große Migrationen brauchen Wellen, Abnahmekriterien, Eigentümer und getesteten Rollback.',why:'Eine technisch schnelle Migration ohne Konsistenz- und Cutoverplan kann Datenverlust oder lange Betriebsunterbrechungen verursachen.',examples:['Ein Unternehmen überträgt 100 TB Archivdaten per Data Box und synchronisiert die letzten Änderungen vor dem Cutover über das Netzwerk.'],merksatz:'Migration ist Kopieren plus Validieren, Umschalten und Rückfallfähigkeit.',sources:['ms-data-box','ms-azure-migrate','ms-dms-overview'],tags:['data-migration','cutover','validation']},
  'azure-0638':{title:'Azure Data Box',simple:'Azure Data Box ist ein physisches Microsoft-Gerät für den Transfer sehr großer Datenmengen nach oder aus Azure. Daten werden lokal auf das Gerät kopiert und das Gerät wird transportiert. Das hilft, wenn die Netzwerkübertragung zu langsam oder zu teuer wäre.',technical:'Data Box wird über den Azure-Dienst bestellt, lokal per Weboberfläche konfiguriert und mit verschlüsselten Daten beladen. Nach Rücksendung liest Microsoft die Daten im Rechenzentrum in unterstützte Azure-Ziele ein; Auftrag und Kopierstatus werden im Portal verfolgt. Gerätekapazität, Region, Zielunterstützung und Versandlaufzeit begrenzen den Prozess.',architecture:'Data Box eignet sich für initiale Bulk-Migration, periodische große Transfers und eingeschränkte Netzanbindung. Es reduziert WAN-Zeit, erzeugt aber logistische Lead Time und ersetzt keine Deltasynchronisierung oder Cutoverplanung. Chain of Custody, Datenklassifikation, Importvalidierung und Restdatenänderungen müssen geklärt sein.',why:'Data Box macht Datenmengen migrierbar, für die ein reiner Onlinepfad praktisch nicht rechtzeitig fertig würde.',examples:['Eine Medienfirma überträgt ihr historisches 200-TB-Archiv per Data Box und lädt neue Dateien bis zum Cutover separat nach.'],merksatz:'Data Box verschiebt den Bulk offline; der kontrollierte Cutover bleibt eine Online- und Betriebsaufgabe.',sources:['ms-data-box','ms-blob-overview'],tags:['data-box','offline-transfer','bulk-migration']},
  'azure-0645':{title:'Azure Migrate',simple:'Azure Migrate hilft, bestehende Server, Anwendungen und Datenbanken für Azure zu erfassen, zu bewerten und zu migrieren. Die Plattform bündelt Inventar, Abhängigkeitsanalyse, Zielbewertung und Migrationswerkzeuge. Sie unterstützt damit die Planung eines kontrollierten Umzugs.',technical:'Ein Azure-Migrate-Projekt sammelt Discovery- und Assessmentdaten über Appliances, Agents oder integrierte Werkzeuge. Assessments bewerten Readiness, Sizing, Abhängigkeiten und Kosten; spezialisierte Tools führen Server-, Web-App- und Datenbankmigrationen aus. Unterstützte Quellen, Zielpfade und Downtime unterscheiden sich je Workload.',architecture:'Azure Migrate ist ein Steuerungs- und Entscheidungsrahmen, kein automatischer Ersatz für Zielarchitektur. Vor jeder Welle ist zwischen Rehost, Replatform und Refactor abzuwägen und eine passende Landing Zone bereitzustellen. Daten, Identität, Netzwerk, Sicherheit, Betrieb und Rollback müssen gemeinsam geplant werden.',why:'Migrationsentscheidungen benötigen belastbares Inventar und Abhängigkeiten statt Schätzungen einzelner Server.',examples:['Ein Unternehmen gruppiert abhängige Web-, VM- und Datenbankkomponenten in eine Migrationswelle und bewertet zuerst Azure-Zielgrößen und Kosten.'],merksatz:'Azure Migrate findet und bewertet den Weg; die Zielarchitektur entscheidet, wohin er führt.',sources:['ms-azure-migrate','ms-dms-overview'],tags:['azure-migrate','assessment','migration-wave']},
  'azure-0724':{title:'Azure Cosmos DB',simple:'Azure Cosmos DB ist eine vollständig verwaltete NoSQL-Datenbank für moderne, global verteilte Anwendungen. Sie speichert flexible Datenmodelle und kann Durchsatz sowie Daten über Regionen verteilen. Der Dienst ist für niedrige Latenz und hohe Skalierung ausgelegt.',technical:'Ein Cosmos-DB-Account enthält Datenbanken, Container und Items und kann mehrere Regionen sowie APIs unterstützen. Container verteilen Daten anhand eines Partition Keys; Throughput wird manuell oder per Autoscale bereitgestellt, Konsistenz ist wählbar. Azure übernimmt Infrastruktur, Patching, Replikation und Backups, während Datenmodell und Partitionierung beim Kunden bleiben.',architecture:'Cosmos DB passt zu globalen NoSQL-Workloads mit vorhersehbarer niedriger Latenz, elastischem Durchsatz und flexiblen Schemas. Partition Key, Konsistenz, Regionslayout und Request Units bestimmen Skalierbarkeit und Kosten. Für relationale Transaktionen, komplexe Joins oder klassische SQL-Workloads ist Azure SQL Database oft geeigneter.',why:'Cosmos DB verbindet globalen Betrieb und horizontale Skalierung in einem verwalteten Datenbankdienst.',examples:['Eine weltweit genutzte Produktanwendung verteilt Katalog-Items über Regionen und partitioniert sie nach Mandant.'],merksatz:'Cosmos DB skaliert über Partitionen und Regionen; ein schlechter Partition Key skaliert Probleme mit.',sources:['ms-cosmos-resource-model','ms-storage-private-endpoints'],tags:['cosmos-db','nosql','global-distribution','partitioning']},
  'azure-0731':{title:'Azure SQL Database',simple:'Azure SQL Database ist eine vollständig verwaltete relationale Datenbank in Azure. Sie speichert strukturierte Daten in Tabellen und unterstützt SQL sowie Transaktionen. Azure übernimmt viele Aufgaben wie Patching, Hochverfügbarkeit und automatische Backups.',technical:'Azure SQL Database ist ein PaaS-Datenbankdienst mit logischen Servern, einzelnen Datenbanken und Elastic Pools. Die Engine stellt T-SQL, ACID-Transaktionen, integrierte Hochverfügbarkeit, automatische Sicherungen, Skalierungsoptionen und Sicherheitsfunktionen bereit. Der Kunde verantwortet Schema, Abfragen, Zugriffsmodell, Leistungsdimensionierung und Wiederherstellungsanforderungen.',architecture:'Azure SQL Database ist die Standardwahl für relationale Anwendungen, die keine Betriebssystem- oder vollständige SQL-Server-Instanzkontrolle benötigen. Gegenüber SQL auf einer VM reduziert sie Betriebsverantwortung, bringt aber Plattformgrenzen und weniger Instanzkontrolle. Private Endpoint, Entra-Authentifizierung, Datenklassifikation, Skalierungsmodell und Geo-DR gehören zum Design.',why:'Der Dienst liefert relationale Konsistenz und verwalteten Datenbankbetrieb, ohne dass Teams eigene SQL-Server patchen und hochverfügbar betreiben.',examples:['Eine Geschäftsanwendung speichert Bestellungen relational in Azure SQL Database und erreicht sie privat aus App Service.'],merksatz:'Azure SQL Database verwaltet die Plattform; das Datenmodell und die Abfragen bleiben Kundenverantwortung.',sources:['ms-azure-sql-overview','ms-storage-private-endpoints'],tags:['azure-sql-database','relational-database','paas']},
  'azure-0738':{title:'Azure Database Migration Service',simple:'Azure Database Migration Service unterstützt die Übertragung bestehender Datenbanken zu Azure-Datenplattformen. Er hilft, Daten mit möglichst wenig Unterbrechung zu verschieben. Quelle, Ziel und unterstützter Migrationsmodus müssen dabei zusammenpassen.',technical:'DMS orchestriert unterstützte Offline- oder Online-Migrationspfade und bewegt Schema- und Datenbestand abhängig vom Datenbanktyp und verwendeten Werkzeug. Onlinepfade halten Quelle und Ziel während einer Synchronisationsphase angenähert, bevor der Cutover erfolgt. Vorbedingungen, Netzwerkkonnektivität, Berechtigungen, Kompatibilität und Validierung bleiben projektspezifisch.',architecture:'DMS ist sinnvoll, wenn ein unterstützter Pfad die technische Datenübertragung standardisiert; es ersetzt keine Schema-, Performance- oder Anwendungsanalyse. Rehost, Replatform und Modernisierung haben unterschiedliche Test- und Downtimeprofile. Der Architekt definiert Zielplattform, Cutover, Rückfall, Datenabgleich und Betriebsübergabe.',why:'Datenbankmigrationen benötigen kontrollierte Synchronisation und Validierung, weil ein einfacher Export selten den gesamten Betriebswechsel abdeckt.',examples:['Eine SQL-Server-Datenbank wird nach Azure SQL migriert, während das Team vor dem Cutover Abfragen, Benutzer und Datenstände validiert.'],merksatz:'DMS bewegt Datenbanken; Kompatibilität, Cutover und Abnahme bleiben Architekturarbeit.',sources:['ms-dms-overview','ms-azure-migrate','ms-azure-sql-overview'],tags:['database-migration-service','database-cutover','data-validation']}
};

const relationDefinitions = [
  ['storage-rel-001','azure-0566','azure-0571','contains','Azure Storage umfasst Blob Storage als Objektspeicherdienst für unstrukturierte Daten.',['ms-storage-intro','ms-blob-overview'],0.99],
  ['storage-rel-002','azure-0566','azure-0596','contains','Azure Storage umfasst Azure Files als verwalteten Dienst für SMB-, NFS- und REST-Dateifreigaben.',['ms-storage-intro','ms-files-overview'],0.99],
  ['storage-rel-003','azure-0566','azure-0616','contains','Data Lake Storage baut auf Blob Storage und damit auf der Azure-Storage-Plattform auf.',['ms-storage-intro','ms-data-lake-overview'],0.99],
  ['storage-rel-004','azure-0566','azure-0624','contains','Azure Storage umfasst Queue Storage für asynchrone Nachrichten zwischen Anwendungskomponenten.',['ms-storage-intro','ms-queue-overview'],0.99],
  ['storage-rel-005','azure-0566','azure-0632','contains','Azure Storage umfasst Table Storage als schemalosen Key-Value-Datendienst.',['ms-storage-intro','ms-table-overview'],0.99],
  ['storage-rel-006','azure-0579','azure-0583','contains','Ein Storage Account enthält im Blob Service Container, die Blobs logisch gruppieren.',['ms-storage-account','ms-blob-overview'],0.99],
  ['storage-rel-007','azure-0574','azure-0571','part_of','Access Tiers steuern Kosten und Abrufverhalten unterstützter Blobdaten.',['ms-blob-access-tiers'],0.99],
  ['storage-rel-008','azure-0575','azure-0574','part_of','Hot ist das Online-Tier für häufig gelesene oder geänderte Blobdaten.',['ms-blob-access-tiers'],0.99],
  ['storage-rel-009','azure-0576','azure-0574','part_of','Cool ist das Online-Tier für selten genutzte Blobdaten mit unmittelbarem Zugriff.',['ms-blob-access-tiers'],0.99],
  ['storage-rel-010','azure-0578','azure-0574','part_of','Archive ist das Offline-Tier für selten abgerufene Langzeitdaten.',['ms-blob-access-tiers'],0.99],
  ['storage-rel-011','azure-0584','azure-0579','part_of','Die Redundanzkonfiguration wird am Storage Account gewählt und bestimmt die Replikation seiner Daten.',['ms-storage-redundancy','ms-storage-account'],0.99],
  ['storage-rel-012','azure-0585','azure-0584','part_of','LRS ist die lokal redundante Grundoption innerhalb eines Standorts der Primärregion.',['ms-storage-redundancy'],0.99],
  ['storage-rel-013','azure-0587','azure-0584','part_of','ZRS ist die zonenredundante Option innerhalb der Primärregion.',['ms-storage-redundancy'],0.99],
  ['storage-rel-014','azure-0589','azure-0584','part_of','GRS ist die georedundante Option mit asynchroner Kopie in einer Sekundärregion.',['ms-storage-redundancy'],0.99],
  ['storage-rel-015','azure-0592','azure-0584','part_of','GZRS kombiniert synchrone Zonenredundanz in der Primärregion mit asynchroner Georeplikation.',['ms-storage-redundancy'],0.99],
  ['storage-rel-016','azure-0601','azure-0596','uses','Azure File Sync verwendet eine Azure-Files-Freigabe als zentralen Cloud Endpoint.',['ms-file-sync','ms-files-overview'],0.99],
  ['storage-rel-017','azure-0351','azure-0571','uses','Eine App-Service-Anwendung kann persistente Objektdaten und Uploads in Blob Storage speichern, statt sie an den kurzlebigen App-Instanzen zu binden.',['ms-blob-overview','ms-storage-authorization'],0.98],
  ['storage-rel-018','azure-0881','azure-0579','connects_to','Ein Storage Private Endpoint stellt einem konkreten Storage-Dienst eine private IP aus dem VNet bereit; öffentliche Erreichbarkeit wird separat am Account gesteuert.',['ms-storage-private-endpoints'],0.99],
  ['storage-rel-019','azure-0964','azure-0579','governs','Azure RBAC steuert identitätsbasierte Management- und unterstützte Datenzugriffe auf Storage-Ressourcen; Datenrollen und Scope müssen passend zugewiesen werden.',['ms-storage-authorization','ms-rbac'],0.99],
  ['storage-rel-020','azure-0947','azure-0579','connects_to','Eine Azure-Anwendung kann ihre Managed Identity für tokenbasierte, schlüssellose Datenzugriffe auf unterstützte Storage-Dienste verwenden.',['ms-storage-authorization','ms-managed-identities'],0.99],
  ['storage-rel-021','azure-0962','azure-0579','governs','Azure Policy kann Storage-Account-Konfigurationen wie Netzwerkzugriff, Verschlüsselungsoptionen oder erlaubte Einstellungen prüfen und durchsetzen.',['ms-policy-overview','ms-storage-account'],0.98],
  ['storage-rel-022','azure-0980','azure-0579','organizes','Azure Resource Tags klassifizieren den Storage Account für Ownership, Kostenanalyse und Betrieb; sie markieren nicht automatisch die enthaltenen Datenobjekte.',['ms-resource-tags','ms-storage-account'],0.99],
  ['storage-rel-023','azure-0638','azure-0566','uses','Azure Data Box überträgt große Datenmengen offline in unterstützte Azure-Storage-Ziele.',['ms-data-box','ms-blob-overview'],0.99],
  ['storage-rel-024','azure-0645','azure-0738','uses','Azure Migrate bindet Database Migration Service als spezialisiertes Werkzeug für unterstützte Datenbankmigrationen ein.',['ms-azure-migrate','ms-dms-overview'],0.98],
  ['storage-rel-025','azure-0881','azure-0724','connects_to','Azure Cosmos DB kann über einen Private Endpoint privat aus einem VNet erreicht werden.',['ms-storage-private-endpoints','ms-cosmos-resource-model'],0.97],
  ['storage-rel-026','azure-0964','azure-0571','governs','Azure RBAC kann Datenzugriff auf Blob Storage mit Storage-Datenrollen und geeignetem Scope autorisieren.',['ms-storage-authorization','ms-rbac'],0.99]
];

for (const source of officialSources) {
  const index = sourcesDocument.sources.findIndex(item => item.id === source.id);
  if (index >= 0) sourcesDocument.sources[index] = source;
  else sourcesDocument.sources.push(source);
}
const typeById = new Map(typesDocument.relation_types.map(type => [type.id, type]));

for (const [id, enrichment] of Object.entries(E)) {
  const node = nodeById.get(id);
  if (!node) throw new Error(`Pilotknoten fehlt: ${id}`);
  if (node.metadata?.enrichment) throw new Error(`${id}: Bereits in V${node.metadata.enrichment.version} angereichert und gegen Überschreiben geschützt.`);
  const originalTitle = node.title;
  node.title = enrichment.title || node.title;
  node.description = {simple:enrichment.simple,technical:enrichment.technical,architecture:enrichment.architecture};
  node.why_important = enrichment.why;
  node.examples = enrichment.examples || [];
  node.merksatz = enrichment.merksatz || '';
  node.analogy = enrichment.analogy || '';
  node.sources = [...new Set([...(node.sources || []), ...enrichment.sources])];
  node.tags = [...new Set([...(node.tags || []), ...(enrichment.tags || []), 'storage-pilot-v1.6'])];
  node.aliases = [...new Set([...(node.aliases || []), ...(originalTitle !== node.title ? [originalTitle] : [])])];
  node.metadata = {...node.metadata,status:'published',audit_flags:(node.metadata.audit_flags || []).filter(flag => flag !== 'description_generated_from_title'),enrichment:{version:'1.6',pilot:'storage-data-architecture',content_standard:'1.0',reviewed_at:today,source_policy:'official_microsoft_only'}};
  node.updated_at = today;
}

const pilotRelationIds = new Set(relationDefinitions.map(([id]) => id));
relationsDocument.relations = relationsDocument.relations.filter(relation => !pilotRelationIds.has(relation.id));
for (const node of nodesDocument.nodes) node.relations = (node.relations || []).filter(id => !pilotRelationIds.has(id));
for (const [id, source, target, type, explanation, sources, confidence] of relationDefinitions) {
  if (!nodeById.has(source) || !nodeById.has(target)) throw new Error(`${id}: Endpunkt fehlt`);
  const typeDefinition = typeById.get(type);
  if (!typeDefinition) throw new Error(`${id}: Typ ${type} fehlt`);
  for (const sourceId of sources) if (!sourcesDocument.sources.some(item => item.id === sourceId)) throw new Error(`${id}: Quelle ${sourceId} fehlt`);
  const relation = {schema_version:'1.1',id,source,target,type,inverse_type:typeDefinition.inverse_type,explanation,sources,confidence,status:'accepted',created_by:'knowledge_enrichment_v1.6',created_at:today,reviewed_at:today};
  relationsDocument.relations.push(relation);
  for (const nodeId of [source,target]) {
    const node = nodeById.get(nodeId);
    node.relations = [...new Set([...(node.relations || []), id])];
  }
}

nodesDocument.meta = {...nodesDocument.meta,enrichment_version:'1.6',storage_pilot:{node_count:Object.keys(E).length,relation_count:relationDefinitions.length,content_standard:'1.0',reviewed_at:today,focus:'storage_and_data_architecture'}};
relationsDocument.meta = {...relationsDocument.meta,relation_count:relationsDocument.relations.length,enrichment_version:'1.6',storage_relation_count:relationDefinitions.length};
sourcesDocument.meta = {...sourcesDocument.meta,count:sourcesDocument.sources.length,generated_at:today,enrichment_version:'1.6'};
typesDocument.meta = {...typesDocument.meta,type_count:typesDocument.relation_types.length,updated_at:today,enrichment_version:'1.6'};

write('nodes.json',nodesDocument);
write('relations.json',relationsDocument);
write('sources.json',sourcesDocument);
write('relation-types.json',typesDocument);

console.log(JSON.stringify({enriched_nodes:Object.keys(E).length,added_relations:relationDefinitions.length,total_relations:relationsDocument.relations.length,added_relation_types:0,total_relation_types:typesDocument.relation_types.length,added_sources:officialSources.length,total_sources:sourcesDocument.sources.length},null,2));
